### ISSUE TITLE
Join in OpenLab

### ISSUE THREAD

**Issue by dakangsiji** [theopenlab/openlab#1026]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
dakangsiji

### Github account id
dakangsiji

### Email
dakangsiji@163.com

**Comment by wangxiyuan** [comment]
openlab is now under maintenance mode. There is no need to join the team.
