### ISSUE TITLE
Build a tool to check Nodepool provider under right configuration

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#103]
- Network
- Subnet
- Router
- Security group
- Security group rule (22, ICMP, 19885)
- Floating ip
- Quota limits
- Flavor

openlab-zuul-jobs used resource name format: `openlab-jobs-xxx`, like: openlab-jobs-net
nodepool config used resource name format: `openlab-xxx`, like: openlab-net

Let's try to finished this task before 2019-04-04 @Yikun

**Comment by kiwik** [comment]
@Yikun Terraform is an option to do it

**Comment by Yikun** [comment]
For now, we have added the support for security group check and cirros image check, and the result as the above snap. See more detail in [labcheck](https://github.com/Yikun/labchecker) .

![image](https://user-images.githubusercontent.com/1736354/54519802-54569200-49a2-11e9-8223-7baba3209bb5.png)

**Comment by Yikun** [comment]
After F2F discussion with @kiwik , below features should be included in the labchecker:

### 1.NodePool Check

- [ ] **Authority check**
Validate the ``cloud.yaml`` using ``openstack token issue``
- [ ] **Network check/recover** 
Check network name openlab-net  --> openlab-subnet --> 192.168.199.0/24
Network Auto create 
- [ ] **Security Group check/recove** 
Check security group: openlab-sg
Check security group rules: ICMP, 22, 19885
- [ ] **Flavor check**
Print the flavor name of 4U8G/8U8G (normal test), 1U2G/2U2G (ut test)
- [ ] **Quota check** 
Print the quota info
- [ ] **Sync nodepool.yaml**
sync the yaml to template

### 2. Zuul-Jobs
- [ ] **Image check**
Check the cirros image
Check the ubuntu 16.04
- [ ] **Network check**
openlab-jobs-net/sg/subnet

### Other idea
1. labchecker --type [nodepool|zuul-jobs] --cloud otc
2. the clouds info should be loaded from cloud.yaml
3. the result should gather by Cloud level, and then the item level.

**Comment by Yikun** [comment]
Auto Recover
![image](https://user-images.githubusercontent.com/1736354/54810022-ea026200-4cbf-11e9-9e59-91b10fc2c64f.png)

Check again
![image](https://user-images.githubusercontent.com/1736354/54810011-deaf3680-4cbf-11e9-9370-8edca437ee95.png)

**Comment by kiwik** [comment]
All related PR merged now

**Comment by Yikun** [comment]
The labchecker v1.0 have been merged in:
https://github.com/theopenlab/labkeeper/tree/master/labchecker

The future feature and other thought (or any new feedback) is tracked in https://github.com/theopenlab/openlab/issues/232
