### ISSUE TITLE
Update quota maxTotalVolumeGigabytes of VEXXHOST to 5000G if possible

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#107]
We use V1 flavor of VEXXHOST `v1-standard-8` in OpenLab nodepool as test executing VM, it is 8 vCPUs, 8192 RAM, 200G disk. It's nice to use V2 flavor `v2-highcpu-8` to instead of `v1-standard-8`.

We estimated test executing node need 100G disk for building devstack, creating large volume and storing glance image in node, so need to launch boot-from-volume instances with flavor `v2-highcpu-8` in VEXXHOST, but now quota `maxTotalVolumeGigabytes` is only 1000G, only 10 instance is available under this limits.

So we hope to update quota maxTotalVolumeGigabytes of VEXXHOST to 5000G if possible, other way is continuing to use boot-from-image instance with flaovr `v1-standard-8`, it's ok to me.

**Comment by mrhillsman** [comment]
@mnaser is this reasonable/can be done?

**Comment by mrhillsman** [comment]
@mnaser thank you very much as always, our project ID is 69b5f56c11e84927abebfdca8039b48b

**Comment by mnaser** [comment]
The quota has been updated.

**Comment by mrhillsman** [comment]
@kiwik I am not sure what credentials are providing you those details but GUI and CLI looks fine:

![screen shot 2018-11-21 at 2 50 23 am](https://user-images.githubusercontent.com/3989695/48829621-4f593d00-ed38-11e8-98df-2bbce031ce3f.png)

```
~ ❯❯❯ openstack limits show --absolute                                                                                                                                                                                                                                                                                                                                 ✘ 2
+--------------------------+--------+
| Name                     |  Value |
+--------------------------+--------+
| maxServerMeta            |    128 |
| maxTotalInstances        |     -1 |
| maxPersonality           |      5 |
| totalServerGroupsUsed    |      0 |
| maxImageMeta             |    128 |
| maxPersonalitySize       |  10240 |
| maxTotalRAMSize          | 163840 |
| maxServerGroups          |     10 |
| maxSecurityGroupRules    |     20 |
| maxTotalKeypairs         |    100 |
| totalCoresUsed           |    122 |
| totalRAMUsed             | 124928 |
| maxSecurityGroups        |     10 |
| totalFloatingIpsUsed     |      0 |
| totalInstancesUsed       |     16 |
| maxServerGroupMembers    |     10 |
| maxTotalFloatingIps      |     10 |
| totalSecurityGroupsUsed  |      1 |
| maxTotalCores            |     -1 |
| totalSnapshotsUsed       |      0 |
| maxTotalBackups          |     10 |
| maxTotalVolumeGigabytes  |   5120 |
| maxTotalSnapshots        |     10 |
| maxTotalBackupGigabytes  |   1000 |
| totalBackupGigabytesUsed |      0 |
| maxTotalVolumes          |     50 |
| totalVolumesUsed         |      0 |
| totalBackupsUsed         |      0 |
| totalGigabytesUsed       |      0 |
+--------------------------+--------+
```

**Comment by kiwik** [comment]
@mrhillsman , sorry, my fault, I did not add `region_name` into clouds.yaml.

**Comment by mrhillsman** [comment]
ok cool

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
