### ISSUE TITLE
Transfer theopenlab/ocean and theopenlab/joinin content into theopenlab/openlab

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#109]
We plan to merge theopenlab/ocean and theopenlab/joinin content into theopenlab/openlab, and use label to mark different processes, should copy legacy unfinished content into new location, then we will deprecated the following repo.
- https://github.com/theopenlab/ocean/issues
- https://github.com/theopenlab/joinin/issues

Related-Bugs: theopenlab/openlab#100
Related-Bugs: theopenlab/openlab#105
Related-Bugs: theopenlab/publications#1

**Comment by kiwik** [comment]
Hi @mrhillsman @liu-sheng and @h00130372 , I have completed the following things to migrate history `new member` and `test request`, please follow new OpenLab workflow in https://docs.openlabtesting.org/

1. I have moved all of issues from ocean and joinin into theopenlab/openlab, see https://github.com/theopenlab/openlab/labels/new%20member and https://github.com/theopenlab/openlab/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration+case%22 
2. Invite these new members to join OpenLab github org
3. Remove theopenlab/joinin repo, only my issue at here, no impact to others
4. Will remove theopenlab/ocean repo in next month(2018.12.01), make the `Test Request` owner can check the history.

**Comment by liu-sheng** [comment]
great jobs! 👍

**Comment by mrhillsman** [comment]
👍

**Comment by kiwik** [comment]
ocean repo is removed, all of tasks DONE.
