### ISSUE TITLE
Resource Request

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#115]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

Owner: @Mandar17 https://github.com/theopenlab/openlab/issues/114

### What is your focus?
- [x] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
Yes and ONAP 

### Brief project description
Open Network Automation Platform is the opens source project by Linux foundation and we want test some of the use cases on top of it as academic study.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes. onap.org 

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
1 Baremetal server
vCPU - 50  

### What OS are you planning to use?
Ubuntu 16.04

### Any special network configuration you expect or anticipate implementing?
No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
RAM 250GB 
--min-cpu-platform "Intel Haswell" 
--boot-disk-size 1000GB 
--local-ssd interface=scsi 

### What testing are you planning to implement or need assistance implementing?
ONAP Use Cases such as virtual Firewall, virtual CPE, etc.

### How will this testing advance application and/or tooling built on-top of open infrastructure?
-         Identify defects and
-         improve implementation efficiency
-         increase documentation

### Will you publish blog or paper from your testing?
· Yes we will publish the test result on ONAP wiki and improve the documentation

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
Will update if any.

**Comment by kiwik** [comment]
Move from https://github.com/theopenlab/ocean/issues/7

**Comment by kiwik** [comment]
Copy @mrhillsman 's comments:
> @Mandar17 please work with Raj and Prof. Ali to add more detail to this.

**Comment by kiwik** [comment]
Hi @Mandar17 and @mrhillsman , which scenario we plan to test? I can not find out available information from this issue.

**Comment by mrhillsman** [comment]
Unfortunately the team had issues getting ONAP to actually deploy according to its documentation and they are very much open to having some help but for the time they have moved on to another project; I believe the following guide was used:

https://docs.onap.org/en/casablanca/guides/onap-developer/settingup/index.html

If anyone is interested in ONAP use case please update with a comment to revive this request or start a new one if this is not sufficient for your use case.

**Comment by kiwik** [comment]
No updates for long time, close it.

Feel free to reopen this issue or commit new one when you have same test requests.
