### ISSUE TITLE
Flavio Percoco join in OpenLab

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#116]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
Flavio Percoco
### Github account id
@flaper87
### Email
flaper87@flaper87.org
### Company/Organization
N/A
### IRC nickname (Optional)
N/A
### Job Title(optional)
N/A
### Phone(optional)
N/A
### Any additional questions, concerns, or comments?
N/A

**Comment by kiwik** [comment]
Move from https://github.com/theopenlab/ocean/issues/5

**Comment by flaper87** [comment]
@kiwik awesome, thanks!

**Comment by kiwik** [comment]
@flaper87 you are welcome :)

**Comment by kiwik** [comment]
@flaper87 in team now
