### ISSUE TITLE
Usery Sandbox Testing Facilities

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#121]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

Owner: @lhaig https://github.com/theopenlab/openlab/issues/120

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [x] Multi-Cloud
- [x] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
Usery is a portal for users to create sandbox accounts on clouds for testing and learning about the cloud
### Brief project description
Usery allows users to request sandbox access to an openstack cloud, these users will then have a single project with default quota to test out using the cloud. The systems allows for accounts to be disabled after a set number of days and then deleted after that.
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes the project is 100% opensource
https://github.com/lhaig/usery
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
The current need is to have a current version of openstack to access through the portal.
The future needs will be federated openstack systems and kubernetes cluster
### What OS are you planning to use?
Ubuntu
### Any special network configuration you expect or anticipate implementing?
No
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
Nothing special
### What testing are you planning to implement or need assistance implementing?
I would be using unit testing to test the current usery codebase.
I need to have cloud scenarios to test against.
### Will you publish blog or paper from your testing?

- [ ] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
The aim with usery is to create a tool that enterprises and cloud providers could utilise to speed up the adoption of clouds within their private / public cloud strategy.

The initial plan is to get Openstack working and then to add features that might come up once people start using it.
The Road map will then include expanding into Kubernetes and Docker Swarm.

**Comment by kiwik** [comment]
Copy from @mrhillsman 's comments:
> Hey @lhaig
> 
> Thanks for the request. We will work on getting you access to an environment and respond here when ready. If you have any extra feedback, questions, or concerns let us know.
> 
> We do require that something like a blog post, whitepaper, etc be provided after use. We can discuss how to ensure this gets done once things are underway. In your case it is easy to imagine at least a blog post can be done.

Copy from @lhaig 's comments
> I will write a blog post on how things are progressing with the advancement of Usery and the status at each step.
> Thanks for looking into this.

Copy from @mrhillsman 's comments:
> Hi @lhaig
> 
> Apologies for the delay. You should have an email with a verification code for access. Let me know when you have completed verification via email info@openlabtesting.org and I will walk you through resource usage and we can discuss how to ensure you are providing the expected feedback for justification.
> 
> Thanks again for the request and talk with you soon.

Copy from @mrhillsman 's comments:
> @lhaig let me know if you have any questions; i am closing this issue for now, feel free to re-open it.

Copy from @lhaig 's comments:
> I had trouble finding out who to use the tool-set. So I was not able to start using the lab.

Copy from @mrhillsman 's comments:
> @lhaig no worries, please jump in #askopenlab on freenode IRC or if Slack works best http://bit.ly/openlab-slack and we can more quickly help you resolve issue(s)

**Comment by kiwik** [comment]
Move from https://github.com/theopenlab/ocean/issues/1

**Comment by lhaig** [comment]
I will work on automating the current tests with openlab cicd

**Comment by kiwik** [comment]
Thank you @lhaig , when you face any question, feel free to raise it in OpenLab IRC channel #askopenlab in freenode
