### ISSUE TITLE
Run Acc tests of native terraform-provider-openstack against OTC, Telefonica, Orange and Huaweicloud

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#125]
### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [x] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
Yes, it is terraform-provider-openstack
### Brief project description
A terraform cloud provider, that can operate OpenStack cloud resources.
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://github.com/terraform-providers/terraform-provider-openstack
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VMs
### What OS are you planning to use?
No special limit
### Any special network configuration you expect or anticipate implementing?
No
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
No
### What testing are you planning to implement or need assistance implementing?
Now we have jobs to test terraform-provider-openstack against native OpenStack,  we should also test against some public clouds, like: OpenTelekomCloud, TelefonicaCloud, OrangeCloud, HuaweiCloud, and add these jobs into periodic pipeline.
- terraform-provider-openstack-acceptance-test-opentelekomcloud
- terraform-provider-openstack-acceptance-test-telefonica
- terraform-provider-openstack-acceptance-test-orange
- terraform-provider-openstack-acceptance-test-huaweicloud
### How will this testing advance application and/or tooling built on-top of open infrastructure?
Verify compatibility of terraform-provider-openstack with following public clouds:
- OpenTelekomCloud
- TelefonicaCloud
- OrangeCloud
- HuaweiCloud
### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

Test result will be shown in OpenLab CI build history http://status.openlabtesting.org/builds
### Any other relevant details we should know about while preparing the infrastructure?
No

**Comment by jtopjian** [comment]
Hello,

Related to https://github.com/terraform-providers/terraform-provider-openstack/pull/491, I'm not really sure that PR (or any similar) should be merged in with the OpenStack provider. In the [documentation](https://www.terraform.io/docs/providers/openstack/index.html#openstack-releases-and-versions) we state:

> This provider aims to support "vanilla" OpenStack. This means that we do all testing and development using the official upstream OpenStack code. If your OpenStack environment has patches or modifications, we do our best to accommodate these modifications, but we can't guarantee this.

All of the clouds you've listed have their own providers:

* https://github.com/terraform-providers/terraform-provider-telefonicaopencloud
* https://github.com/terraform-providers/terraform-provider-opentelekomcloud
* https://github.com/terraform-providers/terraform-provider-huaweicloud
* https://github.com/khdegraaf/terraform-provider-orangecloud

These all use forked/modified copies of the upstream Gophercloud library.

So we're in a situation where the OpenStack provider guarantees support for "vanilla" OpenStack but you want to test it on public clouds that have deviated away from standard API compatibility. In addition, creating test jobs like this might imply that the OpenStack provider fully supports and is compatible with these clouds, which is a claim I cannot in any way make.

How about implementing OpenLab integration with each of the individual providers instead?

Perhaps there is a larger discussion with more details about this integration that I'm not aware of?

**Comment by kiwik** [comment]
Hi @jtopjian , We did not plan to merged these jobs into terraform-provider-openstack, @h00130372 misunderstand my opinion, She will abandon https://github.com/terraform-providers/terraform-provider-openstack/pull/491 .

Let me add some background information, you know these public clouds support compatibility for standard OpenStack API, and support some additional APIs and functionalities. Some users only want to use standard OpenStack API on these public clouds, those standard OpenStack APIs are supported by terraform-provider-openstack, users didn't want to use cloud specific providers, so we plan to run these jobs in OpenLab periodic pipeline to try whether that can worked. Of course, that don't imply  OpenStack provider fully supports and is compatible with these clouds, this documents is clear.
> This provider aims to support "vanilla" OpenStack. This means that we do all testing and development using the official upstream OpenStack code. If your OpenStack environment has patches or modifications, we do our best to accommodate these modifications, but we can't guarantee this.

**Comment by jtopjian** [comment]
@kiwik Perfect - thank you for the clarification :)

I'd be more than happy to help coordinate testing any way I can. The misunderstanding on my part was my assumption that these were going to be first-class test jobs merged into the provider.

**Comment by kiwik** [comment]
@h00130372 own this part of works, these jobs will be added into OpenLab periodic pipeline, so if you are interested in that, please check OpenLab CI status history to check the result, jobs will be executed three times in one day

http://status.openlabtesting.org/builds
