### ISSUE TITLE
Add meetbot into #askopenlab IRC channel

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#127]
### Describe the bug
We plan to hold OpenLab biweekly meeting in team own IRC channel #askopenlab on freenode.org
- Update team status at same point
- If somebody can't attend team meeting, they can check meeting log history at later
- Follow [4 Opens](https://www.openstack.org/four-opens/)

OpenLab is a cross community project, we will try to use OpenStack community meetbot and log server, because current team members are familiar with it. Of course, it's up to whether OpenStack infra team can accept OpenLab as Non-OpenStack community project to join.
https://wiki.openstack.org/wiki/Meetings

### Related Job information
N/A

### Steps to reproduce the issue
N/A

**Comment by kiwik** [comment]
Commit OpenStack meetbot support at
- https://review.openstack.org/#/c/619432/
- https://review.openstack.org/#/c/619446/

**Comment by mrhillsman** [comment]
Done

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
