### ISSUE TITLE
VMs in Citynetwork Cloud in "ERROR" state and cannot be deleted by nodepool

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#132]
### Describe the bug
There are 2 VMs in Citynetwork Cloud in "ERROR" state and cannot be deleted by nodepool:
`982aab52-fbe0-47e8-88c9-dd8d494bd644` and `91214ebc-4b6a-4ac0-814b-6f1e1845a67b`

Related log message of `nodepool-luancher`:
```
2018-11-27 02:47:19,504 INFO nodepool.DeletedNodeWorker: Deleting deleting instance 982aab52-fbe0-47e8-88c9-dd8d494bd644 from citynetwork-openlab
2018-11-27 02:52:12,388 ERROR nodepool.NodeDeleter: Exception deleting instance 91214ebc-4b6a-4ac0-814b-6f1e1845a67b from citynetwork-openlab:
Traceback (most recent call last):
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/launcher.py", line 81, in delete
    manager.waitForNodeCleanup(node.external_id)
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/driver/openstack/provider.py", line 361, in waitForNodeCleanup
    "server %s deletion" % server_id):
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/nodeutils.py", line 41, in iterate_timeout
    raise exc("Timeout waiting for %s" % purpose)
nodepool.exceptions.ServerDeleteException: Timeout waiting for server 91214ebc-4b6a-4ac0-814b-6f1e1845a67b deletion
```

![image](https://user-images.githubusercontent.com/5335434/49055670-636ad600-f233-11e8-802b-7b5d1392b570.png)

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:
NA

**Comment by mrhillsman** [comment]
@tobberydberg please review

**Comment by mrhillsman** [comment]
Please delete 982aab52-fbe0-47e8-88c9-dd8d494bd644 and 91214ebc-4b6a-4ac0-814b-6f1e1845a67b

**Comment by kiwik** [comment]
Add openstack server show output
```
| fault                       | {'created': '2018-11-27T06:49:08Z', 'code': 500, 'message': "Unable to establish connection to http://int-lon1.citycloud.com:9696/v2.0/ports?device_id=91214ebc-4b6a-4ac0-814b-6f1e1845a67b: HTTPConnectionPool(host='int-lon1.citycloud.com', port=9696): Max retries exceeded with url: /v2.0/ports?device_id=91214ebc-4b6"} |
```

**Comment by tobberydberg** [comment]
Thanks for the error report folks. Servers are deleted!

**Comment by mrhillsman** [comment]
@tobberydberg thank you again for the support! also, is there a proper way to go about reporting these according to CityNetwork policy? i would hate to keep pinging you directly if there is a protocol in place.

**Comment by liu-sheng** [comment]
@tobberydberg thank you 😄

**Comment by mrhillsman** [comment]
@tobberydberg thanks buddy, really appreciate it!
