### ISSUE TITLE
Member application for Sean McGinnis

### ISSUE THREAD

**Issue by stmcginnis** [theopenlab/openlab#134]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name

Sean McGinnis

### Github account id

stmcginnis

### Email

sean.mcginnis@huawei.com

### Company/Organization

Huawei

### IRC nickname (Optional)

smcginnis

### Job Title(optional)

Principal Architect

**Comment by liu-sheng** [comment]
Welcom Sean 👏

**Comment by kiwik** [comment]
Welcome @stmcginnis, let me inviting you into team

**Comment by mrhillsman** [comment]
@stmcginnis I have added you to all teams and provided admin access to the org; please let me know if anything is missing.

**Comment by kiwik** [comment]
@stmcginnis in team now
