### ISSUE TITLE
Terraform/Gophercloud: Updates to environment variables

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#139]
Hi all,

There's an upcoming PR that will be making changes to the environment variables required to run the acceptance tests: https://github.com/gophercloud/gophercloud/pull/1343

This PR is making the appropriate updates to the following file: https://github.com/gophercloud/gophercloud/pull/1343/files#diff-394d8cdf0589dc1534fcd748c0d11e10

Before I merge this PR, I want to make sure that this isn't going to break testing for Terraform and Gophercloud. Do both projects use the `stackenv` script? Or do you folks need to make changes on your side?

**Comment by kiwik** [comment]
Thank you @jtopjian to raise this, actually we do not use this environment variables `OS_SHARE_NETWORK_ID`, we set it as fake string to run tests. like https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/terraform-provider-openstack-acceptance-test/run.yaml#L37 , so upstream changes do not impact our jobs, and I plan to draft a PR to remove `OS_SHARE_NETWORK_ID` usage in OpenLab side.

**Comment by kiwik** [comment]
OK @jtopjian , thank you very much :)

**Comment by jtopjian** [comment]
@liu-sheng @kiwik thank you both!

/cc @kayrus
