### ISSUE TITLE
Gophercloud/Terraform: Manilla / Shared Filesystem Support

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#142]
### Describe the bug

It looks like the default configuration devstack for both Gophercloud and Terraform include basic support for Manila. However, we're getting an error when creating a share.

### Related Job information

If the bug is related a CI job, put the job information below:
* job name: terraform-provider-openstack-acceptance-test 
* job build log link: http://logs.openlabtesting.org/logs/25/525/d2254325345acd449f364c9c58227ba40a510dcf/check/terraform-provider-openstack-acceptance-test/3509fce/
* error log piece:

```
openstack_sharedfilesystem_share_v2.share_1: Error waiting for share a24fb1e6-1e88-4777-a301-0ed864b12b6b to become available: unexpected state 'error', wanted target 'available'. last error: %!s(<nil>)
```

### Steps to reproduce the issue

1. A basic `recheck` will trigger the error.

### Additional context

Related PR: https://github.com/terraform-providers/terraform-provider-openstack/pull/525

If additional configuration to devstack is required, then we're totally fine with having manila be split into a separate set of tests, similar to how Trove/DBaaS is.

**Comment by kayrus** [comment]
Here are more details from manila messages (logs):

```
User message: create: Could not find an existing share server or allocate one on the share network provided. You may use a different share network, or verify the network details in the share network and retry your request. If this doesn't work, contact your administrator to troubleshoot issues with your network.
```

**Comment by mrhillsman** [comment]
@kayrus @jtopjian i have reviewed and the issue appears to be with the way manila is deployed and will need some additional time to resolve. Unfortunately it is the weekend so will not get much help right now more than likely.

**Comment by jtopjian** [comment]
@mrhillsman Thank you for looking into it! No problem at all - whenever you folks have time.

**Comment by kayrus** [comment]
Hi @mrhillsman, is there a chance to take a look on this before Christmas?

**Comment by mrhillsman** [comment]
hey @kayrus yes, i have been looking into it still off and on. currently the generic driver is broken in master and i have not tried stable/rocky or older. i discussed with the manila team and they suggested using the lvm driver instead. i was able to get a share created using it with dhss_false share-type but not the default or dhss_true share-type (both have dhss_true). dhss_true does not work with the lvm driver neither does default as a consequence. i have not reviewed the gophercloud acceptance tests for manila but if you could (i am not as versed with golang) or @jtopjian and let me know if we set the jobs to use lvm instead of generic will that suffice? if yes, then i can work to modify the jobs to do that and things will work. personally i think having the acceptance tests use lvm driver is best since the generic driver is broken and honestly i am not sure if it is a reasonable expectation or implementation to use it at all. unfortunately i am not entirely familiar with manila nor have i used it irl to be able to determine if the acceptance tests should be adjusted or the generic driver fixed to really make implementation useful.

**Comment by jtopjian** [comment]
> if yes, then i can work to modify the jobs to do that and things will work.

I'm also not terribly familiar with Manila, but if this is a solution that _might_ work, then let's try it. If you'd be able to have this in place then @kayrus might be able write some tests and try it out. If it's still not working, then let's just wait until after the holidays to proceed further.

I don't mean to impede on @kayrus's work, but if you aren't able to get this in place by whenever your holiday starts, let's just reconvene after the holidays. 

If you also think that there's a slight chance this might affect the other tests from running (configuring LVM somehow inadvertently causes other services to fail), then let's hold off until after the holidays. I'd rather have Manila continue to not be fully functional while everything else is running fine for the next 1-2 weeks.

**Comment by mrhillsman** [comment]
just for reference:
https://github.com/tombarron/vagrant-libvirt-devstack/blob/master/templates/local.conf.j2
http://paste.openstack.org/show/737931/
http://paste.openstack.org/show/737932/

**Comment by mrhillsman** [comment]
@jtopjian ack
will see how far i get today; probably will not be much further than understanding the problem a bit more and hacking on some attempts to fix in a staging environment.

**Comment by mrhillsman** [comment]
@kiwik @h00130372 please reference new documentation submitted by Manila team based on discussion I had with them today - https://docs.openstack.org/manila/latest/contributor/development-environment-devstack.html

**Comment by kayrus** [comment]
@mrhillsman thanks, will take a look later today

**Comment by kayrus** [comment]
@h00130372 it is better to use this PR for tests: https://github.com/gophercloud/gophercloud/pull/1360
It has additional manila messages support.

**Comment by kayrus** [comment]
With an `dhss_false` share type I get:

> allocate host: No storage could be allocated for this share request, Capabilities filter didn't succeed.

**Comment by h00130372** [comment]
@kayrus Not sure we can set the share type to "dhss_false" in  driver_handles_share_servers=True mode?

**Comment by kayrus** [comment]
See @mrhillsman comment above, where he was able to create a share using dhss_false share type

**Comment by h00130372** [comment]
Openlab config manila with option2(driver_handles_share_servers=True) when install devstack, see configuration: http://logs.openlabtesting.org/logs/25/525/039eed81c04b4314f9c96aab676b487a53141c54/check/terraform-provider-openstack-acceptance-test/a6d55b1/logs/etc/manila/
I followed the manila docs to repeat this in my devstack, if following the steps as terraform acctest does (1. create a network 2. create a subnet 3. create a share-network  4. create a share ) then there is an error raised: ERROR oslo_messaging.rpc.server ServiceInstanceException: Subnet must have gateway.
Then I create the share-network in 'private' network, and there is another error raised when creating a share with the share-network: ERROR paramiko.transport [-] Exception: Error reading SSH protocol banner: SSHException: Error reading SSH protocol banner; And seems there was a bug registered recently: https://bugs.launchpad.net/manila/+bug/1807126

**Comment by h00130372** [comment]
Sorry, correct it:
I followed the manila docs to repeat this in my devstack, if following the steps as terraform acctest does (1. create a network 2. create a subnet 3. create a share-network 4. create a share ) then there is an error raised: ERROR oslo_messaging.rpc.server ServiceInstanceException: Subnet gateway is not attached to the router.

**Comment by h00130372** [comment]
And I executed the ssh cmd manually success: http://paste.openstack.org/show/738345/

**Comment by jtopjian** [comment]
@jtopjian That all sounds fine to me - we should be able to tailor the acceptance tests to fit the environment. Thank you for your help with this.

**Comment by kayrus** [comment]
@h00130372 @mrhillsman,  thanks for your time on investigating the issue. Now I can create manila shares and extend them. However it seems impossible to shrink the share, I get `shrinking_error` state.

**Comment by h00130372** [comment]
@jtopjian, would you mind if I closed this issue now? :)

**Comment by jtopjian** [comment]
Please go ahead - thank you all for your help with this! It's very appreciated.

**Comment by h00130372** [comment]
@jtopjian, thank you:)

**Comment by kayrus** [comment]
Thanks, guys. Happy New year.
