### ISSUE TITLE
Terraform/Gophercloud: Merge Failed Errors

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#143]
### Describe the bug

All of our PRs in Terraform and Gophercloud are reporting:

```
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.
```

### Related Job information

https://github.com/terraform-providers/terraform-provider-openstack/pull/513

### Steps to reproduce the issue

1. Just open a PR in either 

* https://github.com/terraform-providers/terraform-provider-openstack
* https://github.com/gophercloud/gophercloud

**Comment by kayrus** [comment]
@mrhillsman, thanks for looking into this

**Comment by jtopjian** [comment]
@mrhillsman Thank you so much for quickly fixing this - I really appreciate the help on a Sunday :smile:

**Comment by mrhillsman** [comment]
@jtopjian you're very welcome my friend 😉
