### ISSUE TITLE
osb-checker job need to adjust to osb-checker refactor

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#144]
Let's make things better!

### Describe the bug
As osb-checker repo has been refactored, need also to run `npm install` under `osb-checker/common/`.

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by kiwik** [comment]
Fix it in theopenlab/openlab-zuul-jobs#393
