### ISSUE TITLE
Terraform: Limited to 100 tests?

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#148]
Hello,

I might be misreading this, but it looks like either only 100 tests are being run or 100 tests are being logged?

```
xargs -t -n100 sh -c 'OS_DEBUG=1 TF_LOG=DEBUG TF_ACC=1 go test ./openstack -v -timeout 120m -run $(echo "$@" | tr " " "|")' argv0
```

source: http://logs.openlabtesting.org/logs/59/559/057ff4b6513490b6725610eb6104b547cd94f173/check/terraform-provider-openstack-acceptance-test/88bd5b2/

Would someone be able to confirm/clarify this?

Thank you :slightly_smiling_face:

**Comment by h00130372** [comment]
@jtopjian, we use xargs -n100 to split acctests into several batches, and every batch we execute 'sh -c ......' cmd up to 100 tests. You can find now we there are 243 acctests, and them are splited to 3 batches: 1. first 100 acctests 2. the second 100 acctests 3. the last 43 acctests

**Comment by jtopjian** [comment]
Ah - yes, I understand. I was indeed reading the command wrong. Thank you for clarifying :)

**Comment by kiwik** [comment]
OK, thank you @h00130372 's clarification.
