### ISSUE TITLE
Integrate ManageIQ with FusionCloud

### ISSUE THREAD

**Issue by huangtianhua** [theopenlab/openlab#165]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [x] Multi-Cloud
- [x] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
We want to verify ManageIQ against FusionCloud
- https://github.com/ManageIQ/manageiq-providers-openstack

### Brief project description
[FusionCloud](https://e.huawei.com/en/cloud-computing/private-cloud) is Huawei private cloud solution, support OpenStack standard APIs, some users use manageiq on FusionCloud, so we want to verify whether they can integrate with manageiq to drive their business.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, 
- https://github.com/ManageIQ/manageiq-providers-openstack

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VM
### What OS are you planning to use?
No limit
### Any special network configuration you expect or anticipate implementing?
NA
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
NA
### What testing are you planning to implement or need assistance implementing?
NA
### How will this testing advance application and/or tooling built on-top of open infrastructure?
Test API compatibility and grow OpenStack API ecosystem in multi-cloud and hyper-cloud.
### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
N/A

**Comment by kiwik** [comment]
Out of scope for OpenLab governance

https://github.com/theopenlab/governance/blob/master/CHARTER.md#1-mission-and-scope-of-the-openlab-project
