### ISSUE TITLE
Support to deploy native Kubernetes in openlab-zuul-jobs

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#175]
Let's make things better!

### Describe the bug
Now OpenLab support to deploy native OpenStack by using role `install-devstack` and `create-devstack-local-config` to test some ecosystem tools that base on OpenStack API. Another tools are built on Kubernetes API, like: Kubeflow, Istio and so on. OpenLab should support testing these tools, so we should build some roles to deploy native Kubernetes in OpenLab, plan to use deploy tools `kubeadmin` or `minikube`, and support Kubernetes version: `master` and `lastest-release`

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by mrhillsman** [comment]
https://github.com/kubernetes-sigs/kind

**Comment by kiwik** [comment]
Thank you @mrhillsman sharing this information, @h00130372 please compare these k8s deploying tools to choose a most sutiable one for OpenLab
