### ISSUE TITLE
Super Patrol

### ISSUE THREAD

**Issue by presstartgs** [theopenlab/openlab#179]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [x] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [x] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

**Comment by mrhillsman** [comment]
Hi, @presstartgs can you provide us more detail? There are quite a few questions not answered.

**Comment by kiwik** [comment]
Lack key information to test, close because of inactivity, feel free to reopen it.
