### ISSUE TITLE
Test request: kops openstack integration

### ISSUE THREAD

**Issue by zetaab** [theopenlab/openlab#181]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it? 

yes, kubernetes/kops

### Brief project description

The easiest way to get a production grade Kubernetes cluster up and running.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?

https://github.com/kubernetes/kops

### What kind of machines (VMs or Baremetal) and how many do you expect to use?

vms, for start we need to create 5 machines. That is minimal test setup, which contains 1 bastion, 3 masters and 1 normal node.

### What OS are you planning to use?

debian

### Any special network configuration you expect or anticipate implementing?

lbaas is needed, haproxy or octavia

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?

not really, this does not need much resources

### What testing are you planning to implement or need assistance implementing?

we are planning to implement kops openstack PR tests. I think we do not need help for that.

### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?

The test results is available in single PRs in kops repository

**Comment by dims** [comment]
lgtm!

**Comment by zetaab** [comment]
1 x Bastion: 1cpu 1GB, 10GB disk
3 x Master: 2cpu 4GB, 10GB disk
2 x Node: 2cpu 4GB, 10GB disk

cinder volume is needed as well, I think something like 20GB is enough for that.

(I increased node number from 1 -> 2 that we can test scaling)
Total quota needed: 12 cpu, 24GB, cinder 20GB

**Comment by drekle** [comment]
This is a kind of quota for my somewhat standard deployment:
- 4 floating ip ( 2 for loadbalancer deploys 4 for non lb deploys )
- 1 LB Listener
- 1 LB Pool
- 1 loadbalancer
- 1 network
- 8 port
- 1 router
- 1 key/pair
- 3 security groups
- 5 server groups ( 4 Needed)

**Comment by kiwik** [comment]
/lgtm @zetaab 
Please follow the [guide](https://docs.openlabtesting.org/contributors/development-guide). It's easy to enable PR and periodic triggered jobs, if you want to support PR triggered jobs, you should install OpenLab github APP in kubernetes/kops project, and commit integration job PR in [openlab-zuul-jobs](https://github.com/theopenlab/openlab-zuul-jobs), when the two steps are completed, @theopenlab/ops team will enable config in zuul side, then OpenLab testing resources will be free for your project.

You mentioned multiple nodes deployment and enable octavia, luckily OpenLab have support both of them, please refer to https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L2077-L2095 and https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml#L6-L9
