### ISSUE TITLE
Join in OpenLab: Maxime Guyot

### ISSUE THREAD

**Issue by Miouge1** [theopenlab/openlab#182]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
Maxime Guyot
### Github account id
miouge1
### Email
maxime@root314.com
### Company/Organization
kubernetes-sigs/Kubespray
### IRC nickname (Optional)
miouge
### Job Title(optional)
DevOps

**Comment by kiwik** [comment]
Welcome to OpenLab @Miouge1 , let me to join you into team.

**Comment by Miouge1** [comment]
I got the invite, thank you @kiwik I will mark this issue as resolved.
