### ISSUE TITLE
Terraform: Trove Failing

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#183]
### Describe the bug

The `recheck trove` job seems to be failing.

### Related Job information

If the bug is related a CI job, put the job information below:
* job name: `recheck trove`
* job build log link: 

* http://logs.openlabtesting.org/logs/71/671/832a4773b230ebd19bad9bbddcd5046c35aad689/recheck-trove/terraform-provider-openstack-acceptance-test-trove/ae4993c/
* http://logs.openlabtesting.org/logs/71/671/832a4773b230ebd19bad9bbddcd5046c35aad689/recheck-trove/terraform-provider-openstack-acceptance-test-trove/6aa6422/

* error log piece: not sure

### Steps to reproduce the issue

Describe how to reproduce the issue:

Run `recheck trove` at https://github.com/terraform-providers/terraform-provider-openstack/pull/671

**Comment by kiwik** [comment]
Hi @liu-sheng , do you have time to fix this?

**Comment by jtopjian** [comment]
We're still seeing trove failures: https://github.com/terraform-providers/terraform-provider-openstack/pull/671

**Comment by kiwik** [comment]
Sorry, @jtopjian , still exist issue, I am trying to address it

**Comment by jtopjian** [comment]
@kiwik No problem at all - thank you 🙂

**Comment by jtopjian** [comment]
It looks like this is working. Thank you very much for fixing it!
