### ISSUE TITLE
Request to join OpenLab

### ISSUE THREAD

**Issue by ZhengZhenyu** [theopenlab/openlab#184]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name

Zhenyu Zheng

### Github account id

ZhengZhenyu

### Email

zheng.zhenyu@outlook.com

### Company/Organization

Huawei Technology

**Comment by liu-sheng** [comment]
welcome

**Comment by kiwik** [comment]
Welcome, let me to invent you into @theopenlab/dev team

**Comment by kiwik** [comment]
@ZhengZhenyu in team now
