### ISSUE TITLE
bzhaoopenstack Join in openlab

### ISSUE THREAD

**Issue by bzhaoopenstack** [theopenlab/openlab#185]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
Bo Zhao

### Github account id
bzhaoopenstack

### Email
bzhaojyathousandy@gmail.com

### Company/Organization
Huawei

### IRC nickname (Optional)
bzhao

### Job Title(optional)
N/A

### Phone(optional)
N/A

### Any additional questions, concerns, or comments?
N/A

**Comment by kiwik** [comment]
Welcome, let me to invent you into @theopenlab/dev team

**Comment by kiwik** [comment]
@bzhaoopenstack in team now
