### ISSUE TITLE
Yikun Jiang join in OpenLab

### ISSUE THREAD

**Issue by Yikun** [theopenlab/openlab#186]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
Yikun Jiang

### Github account id
yikun

### Email
yikunkero@gmail.com

### Company/Organization
Huawei Technology

### IRC nickname (Optional)
yikun

**Comment by kiwik** [comment]
Welcome, let me to invent you into @theopenlab/dev team

**Comment by kiwik** [comment]
@Yikun in team now
