### ISSUE TITLE
wangxiyuan join in OpenLab

### ISSUE THREAD

**Issue by wangxiyuan** [theopenlab/openlab#187]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name

Xiyuan Wang

### Github account id

wangxiyuan

### Email

wangxiyuan1007@gmail.com

### Company/Organization

Huawei

### IRC nickname (Optional)

wxy-xiyuan

**Comment by kiwik** [comment]
Welcome, let me to invent you into @theopenlab/dev team

**Comment by kiwik** [comment]
@wangxiyuan in team now.
