### ISSUE TITLE
Test Request: Running Spark on native k8s cluster

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#188]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [x] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
yes, apache spark
### Brief project description
Spark is a fast and general cluster computing system for Big Data. It provides high-level APIs in Scala, Java, Python, and R, and an optimized engine that supports general computation graphs for data analysis. It also supports a rich set of higher-level tools including Spark SQL for SQL and DataFrames, MLlib for machine learning, GraphX for graph processing, and Spark Streaming for stream processing.
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
yes, https://github.com/apache/spark
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
1 VM per testing job
### What OS are you planning to use?
Ubuntu xenial
### Any special network configuration you expect or anticipate implementing?
NA
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
NA
### What testing are you planning to implement or need assistance implementing?
NA
### How will this testing advance application and/or tooling built on-top of open infrastructure?
NA
### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?
Testing result in PR coments

**Comment by kiwik** [comment]
We should support spark versions:
1. v2.4.0
2. v3.0.0 (master)

**Comment by liu-sheng** [comment]
done
