### ISSUE TITLE
Fix TestReadConfig test case in OCCM

### ISSUE THREAD

**Issue by animationzl** [theopenlab/openlab#19]
TestReadConfig test case will modify the openstack credential envs, which causes the subsequent 3 test cases TestNewOpenStack/TestLoadBalancer/TestVolumes skipped at openstack credential verification [1]

[1] https://github.com/dims/openstack-cloud-controller-manager/blob/master/pkg/cloudprovider/providers/openstack/openstack_test.go#L90

**Comment by kiwik** [comment]
I think the issue should be fixed in dims/openstack-cloud-controller-manager, not in OpenLab.

**Comment by kiwik** [comment]
Have been fixed in upstream https://github.com/kubernetes/kubernetes/pull/61352 , and sync to https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack_test.go#L93-L94
