### ISSUE TITLE
Gophercloud Issues

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#192]
Let's make things better!

### Describe the bug

Gophercloud acceptance tests are currently failing.

### Related Job information

If the bug is related a CI job, put the job information below:
* job name: gophercloud-acceptance-test
* job build log link: http://logs.openlabtesting.org/logs/67/967/2a9c0ae3785f12fe39c9a6b042c973f1b31d96d8/check/gophercloud-acceptance-test/d96bc8d/
* error log piece:

Not sure

### Steps to reproduce the issue

Describe how to reproduce the issue:

Run recheck here: https://github.com/gophercloud/gophercloud/pull/967

### Additional context

We also have a second issue. Prior to the above failures, we were getting a failure with the `TestVolumeActionsUploadImageDestroy` job. This job began failing in the past week - no changes happened to the code around it. 

http://logs.openlabtesting.org/logs/67/967/2a9c0ae3785f12fe39c9a6b042c973f1b31d96d8/check/gophercloud-acceptance-test/d36112a/job-output.txt.gz

I created a clean devstack environment and confirmed that the job passes.

**Comment by kiwik** [comment]
@bzhaoopenstack please help to address this

**Comment by bzhaoopenstack** [comment]
The log shows that octavia failed to setup by fail to build image. This looks a diskimage error. Octavia just uses its CLI to genarate a image file.  No more error details found. I will try to login the env to check why call diskimage failed.

**Comment by jtopjian** [comment]
@bzhaoopenstack Thank you for looking into this.

I'm going to disable the Octavia tests for the time being.

**Comment by moo-ai** [comment]
@jtopjian Hi, OpenStack upstream team decided to fix it through a yappi release right now. 
Please check:
https://review.openstack.org/#/c/638489/
So there is no problem for this issue. Could you please tag this as closed? Thanks

**Comment by jtopjian** [comment]
Yes, looks like the tests are now passing. However, I've run into another error and I'll open a new issue for it.

Thank you!
