### ISSUE TITLE
Support GPU accelerated nodes pool

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#196]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [x] Machine Learning
- [x] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
yes
### Brief project description
Adding GPU accelerated nodes pool for AI/ML integration
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
NA
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VMs with GPU, nodeset currently:

- ubuntu-xenial-gpu

### What OS are you planning to use?
Ubuntu
### Any special network configuration you expect or anticipate implementing?
NA
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
GPU
### What testing are you planning to implement or need assistance implementing?
NA
### How will this testing advance application and/or tooling built on-top of open infrastructure?
NA
### Will you publish blog or paper from your testing?

- [ ] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
NA

**Comment by liu-sheng** [comment]
after check, I found that currently, the OpenTelekomCloud can support that type of instance; vexxhost also support, but not found the gpu specific flavor in current account; the Packet also announced supporting gpu instance, also not found the gpu specific flavor in current account.

**Comment by liu-sheng** [comment]
@stmcginnis @mrhillsman @dims @kiwik please help to review this request, thanks.

**Comment by liu-sheng** [comment]
also cc @hogepodge :)

**Comment by mrhillsman** [comment]
@liu-sheng we may want to name the nodeset {os}-{version}-{provider}-{type(arch|feature|etc)}
ubuntu-xenial-vxh-gpu

will check with packet and vexxhost for allocation and report back here

**Comment by hogepodge** [comment]
I'm always game for adding new capacity that meets testing needs.

**Comment by liu-sheng** [comment]
@mrhillsman maybe it is better to define nodeset without specific `cloud provider` field. usually, jobs don't need to know nodes with the label in which provider. and if we add `provider` in nodeset, we need to distinguish different jobs in differences provider.

**Comment by stmcginnis** [comment]
LGTM

Agree with @liu-sheng that it's probably better to keep provider out of it.

**Comment by kiwik** [comment]
+1 for @liu-sheng 's suggestion, job do not need to know which provider give the labeled resource.

**Comment by kiwik** [comment]
@wangxiyuan @bzhaoopenstack please enable GPU label in nodepool

**Comment by wangxiyuan** [comment]
GPU node is supported in huaweicloud provider.  We can add more provider for GPU if needed in the future.

**Comment by kiwik** [comment]
We have multiple cloud providers and multiple GPU types in each cloud provider (M * N), so there are too many details about GPU card type, GPU driver, linux-headers version and NVIDIA driver version. We use pre-build cloud images in each cloud provider to hide this details for AI/DL users, they only need to config label `ubuntu-xenial-gpu` to get GPU nodes from nodepool, this label is available now. http://status.openlabtesting.org/labels
