### ISSUE TITLE
Machine Learning environment reproduction on Openlab via ML metadata description file

### ISSUE THREAD

**Issue by wangxiyuan** [theopenlab/openlab#197]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [X] Machine Learning
- [x] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
Yes
### Brief project description
Allow Machine Learning operators to reproduce the ML environment via a ML metadata description file for training or inferring .
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes.
https://github.com/moo-ai/moo-ai.github.io
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VMs with GPU support. 3-4 VMs are fine.
### What OS are you planning to use?
Ubuntu
### Any special network configuration you expect or anticipate implementing?
The VMs should have public IP. So that operators can login or host  inference server for a while.
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
GPU is needed.
### What testing are you planning to implement or need assistance implementing?
We'll test the ability for reproducing ML environment via ML metadata file.
### How will this testing advance application and/or tooling built on-top of open infrastructure?
N/A
### Will you publish blog or paper from your testing?

- [ ] Yes
- [X ] No - if no, how will you present your results?
Via webpage: https://moo-ai.github.io
### Any other relevant details we should know about while preparing the infrastructure?
N/A

**Comment by dims** [comment]
LGTM

**Comment by mrhillsman** [comment]
@hogepodge @stmcginnis

**Comment by stmcginnis** [comment]
LGTM

**Comment by hogepodge** [comment]
LGTM

**Comment by kiwik** [comment]
All related PR merged now
