### ISSUE TITLE
Add ARM nodesets

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#198]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
NA
### Brief project description
Add arm resource pool
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
NA
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
ARM VM
### What OS are you planning to use?
- ubuntu-xenial
- ubuntu-bionic
- centos-7
### Will you publish blog or paper from your testing?

- [ ] Yes
- [ ] No - if no, how will you present your results?

**Comment by kiwik** [comment]
@mrhillsman , ARM node is available in OpenLab nodepool, you can continue your PR to add it in openlab-zuul-jobs http://status.openlabtesting.org/labels

**Comment by kiwik** [comment]
https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/nodesets.yaml

`ubuntu-xenial-arm64` nodeset is available.
