### ISSUE TITLE
Add k8s jobs to CityCloud

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#199]
CityCloud provides Octavia now in Lon region along with Barbican and Magnum.

- [ ] Setup non-prod OpenLab CI
- [ ] Duplicate K8s jobs from prod OpenLab CI
- [ ] Run non-prod jobs against CityCloud
- [ ] Update prod OpenLab CI to use CityCloud
- [ ] Verify OpenLab CI is sending K8s jobs to CityCloud

**Comment by mrhillsman** [comment]
Will need to use the Frankfurt region as it supports Octavia

**Comment by kiwik** [comment]
We run `cloud-provider-openstack` jobs on VEXXHOST stably, no plan to move it again.
