### ISSUE TITLE
CloudFoundry Integration (BOSH, Service Broker API, etc)

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#20]

**Comment by mrhillsman** [comment]
We have reached out to Marco Volz (PM OpenStack CPI, developer@SAP)

- Use case(s) - installation on newer (multiple) versions of OpenStack is sufficient
- Marco is currently working to reduce the amount of tests to what can run on devstack
- Once we get the above line item we will have base to build on

**Comment by mrhillsman** [comment]
Summary of discussion with Marco and tracking within BOSH community can be found here:
https://www.pivotaltracker.com/n/projects/1456570/epics/3920170

**Comment by mrhillsman** [comment]
Adding this comment for tracking purposes only between repos - https://github.com/cloudfoundry-incubator/cf-openstack-validator/issues/28

**Comment by mrhillsman** [comment]
@animationzl @liu-sheng @kiwik the team working on the cpi provided a playbook:
https://github.com/ansd/openlab-zuul-jobs/blob/cpi-openstack-compatibility/playbooks/bosh-openstack-cpi-release-acceptance-test/run.yaml

**Comment by mrhillsman** [comment]
via Slack:

Manuel [1 day ago]
You can find the current (unfinished) state of our scripts at https://github.com/ansd/openlab-zuul-jobs/blob/cpi-openstack-compatibility/playbooks/bosh-openstack-cpi-release-acceptance-test/run.yaml .

Before being able to run this, you may need to create the terraform resources https://github.com/cloudfoundry-incubator/cf-openstack-validator/tree/master/ci/terraform

**Comment by animationzl** [comment]
@mrhillsman we have wrote a playbook to run the cf-openstack-validator validation test at https://github.com/theopenlab/cf-openstack-validator/pull/1, you can see the log at the bottom of this link, please note that the job fails with 5 errors and the reason of each is issued here:
https://github.com/cloudfoundry-incubator/cf-openstack-validator/issues/26
https://github.com/cloudfoundry-incubator/cf-openstack-validator/pull/22
https://github.com/cloudfoundry-incubator/cf-openstack-validator/issues/30
https://github.com/cloudfoundry-incubator/cf-openstack-validator/issues/29

**Comment by voelzmo** [comment]
@animationzl any advice on how we  can iterate on https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cf-openstack-validator-acceptance-test/run.yaml? I'm curious how we would test this e.g. with regard to the timeout issues and other things you reported in our project.

Ideally, this playbook would live in our project and we would make changes until it passes on your CI. Is that possible? If so, how?

**Comment by animationzl** [comment]
@voelzmo yes, this is also what we would like to do

To achieve this, first you need to follow these steps [1] to build connection between OpenLab and cf-openstack-validator [2], then our team will submit a PR including playbooks, job/project definition, etc to cf-openstack-validator [2] repo, after this PR merged, all subsequent PRs will be tested automatically in OpenLab CICD.

But before we start to do this, we should identify the plan and range of integration between OpenLab and CLoudFoundry, this is what we currently working on and we believe will figure it out soon.

[1] https://github.com/theopenlab/cicd-howto#connect-to-openlab
[2] https://github.com/cloudfoundry-incubator/cf-openstack-validator

**Comment by liu-sheng** [comment]
For the [bosh-acceptance-tests](https://github.com/cloudfoundry/bosh-acceptance-tests) repo integration, we have done in https://github.com/theopenlab/openlab-zuul-jobs/pull/226, but there is an issue that cause 1 test case failed, I have reported the issue in https://github.com/cloudfoundry/bosh-acceptance-tests/issues/42

**Comment by kiwik** [comment]
Finished.
