### ISSUE TITLE
Request an account and join openlab

### ISSUE THREAD

**Issue by YangLiang3** [theopenlab/openlab#206]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
YangLiang
### Github account id
YangLiang3
### Email
liang3.yang@intel.com
### Company/Organization
Intel OTC
### Any additional questions, concerns, or comments?
Could you please give me an account ASAP?

**Comment by kiwik** [comment]
Welcome to OpenLab, let me to invite you into team

**Comment by kiwik** [comment]
@YangLiang3 have been in OpenLab Team now.
