### ISSUE TITLE
request an test on baremetal for clearlinux

### ISSUE THREAD

**Issue by YangLiang3** [theopenlab/openlab#207]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [x] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [x] Machine Learning
- [x] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### What OS are you planning to use?
clear linux
### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?

**Comment by kiwik** [comment]
Duplicate with https://github.com/theopenlab/openlab/issues/208, close this one.
