### ISSUE TITLE
Add support for KinD

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#211]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [x] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
KinD

### Brief project description
Kubernetes IN Docker - local clusters for testing Kubernetes https://kind.sigs.k8s.io/
kind is a tool for running local Kubernetes clusters using Docker container "nodes".
kind is primarily designed for testing Kubernetes 1.11+, initially targeting the conformance tests.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/kubernetes-sigs/kind

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VMs - 2-4

### What OS are you planning to use?
Ubuntu

### Any special network configuration you expect or anticipate implementing?
No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
aarch64

### What testing are you planning to implement or need assistance implementing?
CI for KinD

### How will this testing advance application and/or tooling built on-top of open infrastructure?
Kubernetes is the de-facto standard in container orchestration. KinD is a tool the Kubernetes community is expecting projects to use and it is promoting KinD. Having KinD work on multiple architectures will help to increase adoption across broader market.

### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?
Results can be found by viewing the build logs.

**Comment by mrhillsman** [comment]
- [ ] Add aarch64 (ARM64) nodes to nodepool
- [ ] Examine steps provided by @dims - https://etherpad.openstack.org/p/dims-arm64
- [ ] Break up steps into job components
- [ ] Add job components into pipeline for KinD
- [ ] Initiate triggers for job(s)
- [ ] Ensure jobs succeed in reporting results (success or failure)
- [ ] Trigger periodic runs and report upstream for signaling

**Comment by stmcginnis** [comment]
Looks good to me. This fits our mission, so I think it would be a great addition.

**Comment by vielmetti** [comment]
The upstream issue is https://github.com/kubernetes-sigs/kind/issues/188

**Comment by hogepodge** [comment]
lgtm

My primary feedback would be that although there's no specific result to publish, having some sort of feedback or user experience that OpenLab and other affiliates could publish (say on SuperUser Blog) would be nice exposure for both the project and OpenLab

**Comment by dims** [comment]
@hogepodge there are a few Arm64 CI reports in https://testgrid.k8s.io/ These are run by @lubinsz (from ARM) and post just results to the kubernetes test-grid. it reports the minimum of details and we don't know exactly how things are stood up / versions of things etc. 

This job would be the first Arm64 CI job which is totally run by community process with every bit of setup/install/testing code in public. It uses Kubeadm running inside Kind and runs e2e tests (all from master branches to start with). So would give an excellent view for the SIG-release about failures on other platforms. 

Just for context to whoever may be looking, just to get this working, we had to
- add support for Arm64 in kind
- fix build issues in k/k for bazel and docker based builds for Arm64
- add support in kubetest for alternate base image

among other things. Once we have the CI up, we will basically ensure none of these things will go stale (cross my fingers)

Thanks,
Dims

**Comment by vielmetti** [comment]
When there is reporting to testgrid, this is the data that could (and should) feed a future specific arm64 CI dashboard, akin to what the CNCF does on https://cncf.ci (except specific to arm64).

**Comment by dims** [comment]
related to https://github.com/kubernetes-sigs/kind/issues/188

**Comment by hogepodge** [comment]
thanks @dims

**Comment by kiwik** [comment]
After @ZhengZhenyu resolve https://github.com/theopenlab/openlab/issues/230 , kind job is available in OpenLab now http://status.openlabtesting.org/builds?job_name=kind-integration-test-arm64

**Comment by kiwik** [comment]
OpenLab have supported kind job on ARM arch now, closed. https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/projects.yaml#L140-L145
