### ISSUE TITLE
Test Request: Integration Helm with native k8s cluster

### ISSUE THREAD

**Issue by h00130372** [theopenlab/openlab#212]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [x] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
helm/charts
helm/helm
helm/chart-testing

### Brief project description
Helm is a tool for managing Kubernetes charts. Charts are packages of pre-configured Kubernetes resources. And chart-testing(ct) is the the tool for testing Helm charts. 
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
yes, 
https://github.com/helm/helm
https://github.com/helm/charts
https://github.com/helm/chart-testing

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
1 VM per testing job
### What OS are you planning to use?
Ubuntu xenial
### Any special network configuration you expect or anticipate implementing?
NA
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
NA
### What testing are you planning to implement or need assistance implementing?
We will add two jobs of integration test of helm with native k8s cluster which use v2.2.0 chart-testing tool, in which the helm version is 2.12.2:
1. job testing in kubernetes 1.14.0
2. job testing in kubernetes 1.12.7

### How will this testing advance application and/or tooling built on-top of open infrastructure?
NA
### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?
Testing result in PR coments

**Comment by hogepodge** [comment]
I'm not exactly certain what's being asked for here. Which charts? Why on an old version of Kubernetes?

**Comment by h00130372** [comment]
Now I only select four charts to test: stable/mysql,stable/postgresql,stable/etcd-operator,stable/coredns.
We suppose user's Kubernetes is in an old version and don't want to upgrade, and want to use helm maybe the latest version, so I add a job for test this situation.
