### ISSUE TITLE
Provide k8s version for create-single-k8s-cluster-with-kubeadm role

### ISSUE THREAD

**Issue by h00130372** [theopenlab/openlab#213]
Let's make things better!

### Is your feature enhancement related to a problem? Please describe.
Role create-single-k8s-cluster-with-kubeadm now only create the latest version of k8s cluster, so it will be better to provide parameters to specify the versions of k8s.

### Describe the solution you'd like
Add a parameter "kubernetes_version" for role, and keep the default value "latest".

**Comment by kiwik** [comment]
Thank you @h00130372 to add this feature, would you like to add `create-single-k8s-cluster-with-minikube` role to support specific k8s version? refer to https://kubernetes.io/docs/setup/minikube/#specifying-the-kubernetes-version

**Comment by h00130372** [comment]
sure, will add it.
