### ISSUE TITLE
Is OpenLab Down?

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#214]
### Describe the bug

* Test suites aren't running here: https://github.com/gophercloud/gophercloud/pull/1498
* In addition, http://status.openlabtesting.org/status isn't loading.

### Related Job information

If the bug is related a CI job, put the job information below:

* job name: Gophercloud acceptance tests
* job build log link: https://github.com/gophercloud/gophercloud/pull/1498

### Steps to reproduce the issue

Describe how to reproduce the issue:

Run "recheck" in the above PR.

**Comment by kiwik** [comment]
Hi @jtopjian , we maintain OpenLab CI today, system will recover later, I raise this thing in OpenLab IRC channel #askopenlab in this morning, sorry. 
@liu-sheng @h00130372

**Comment by kiwik** [comment]
Need @mrhillsman to map status.openlabtesting.org and logs.openlabtesting.org to new IP 185.52.159.19, other works have done now

**Comment by mrhillsman** [comment]
@jtopjian IP was updated and should be fine now. if not the change is still propagating.

**Comment by jtopjian** [comment]
@kiwik @mrhillsman Thank you both.

Just to update: running "recheck" on https://github.com/gophercloud/gophercloud/pull/1498 isn't triggering a recheck. I'll try again in a few hours.

**Comment by kiwik** [comment]
OpenLab CI have been recovered http://status.openlabtesting.org/builds

**Comment by jtopjian** [comment]
Thank you both so much!
