### ISSUE TITLE
Gophercloud and Terraform Acceptance tests are failing.

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#216]
### Describe the bug
I'm not sure if this is a continuation of #214 or something new, but the acceptance tests are failing for both Gophercloud and Terraform.

I believe the cause is a Designate error.

### Related Job information
If the bug is related a CI job, put the job information below:
* job name: 
  * https://github.com/terraform-providers/terraform-provider-openstack/pull/559
  * https://github.com/gophercloud/gophercloud/pull/1498
 
I was able to get the tests to successfully run by disabling Designate: https://github.com/gophercloud/gophercloud/pull/1506

I _think_ the `devstacklog.txt.gz` file of the failed PRs is pointing to a Designate error.

It's strange, though, because for Terraform, we have a separate test for Designate, so I'm not sure why it's running in the "default" test suite.

### Steps to reproduce the issue
Describe how to reproduce the issue:

* Run `recheck` in the above links

**Comment by kiwik** [comment]
@jtopjian it's a designate config issue, no related with #214 , @h00130372 have fixed it in theopenlab/openlab-zuul-jobs#462, latest testing pass https://github.com/terraform-providers/terraform-provider-openstack/pull/559#issuecomment-472259127

**Comment by jtopjian** [comment]
Thank you both!
