### ISSUE TITLE
OpenLab CI multiple nodes deployment across multiple cloud providers

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#218]
Let's make things better!

### Is your feature enhancement related to a problem? Please describe.
Now OpenLab CI is deployed in one cloud provider (public cloud), include: Zuul and Nodepool, this deployment mode exist shortcoming. The issues of cloud provider might impact OpenLab CI services, like: network can not accessed, booting instance error, or OpenLab CI instance is deleted unexpectedly.

### Describe the solution you'd like
We should address this single point issue for OpenLab CI system, try to deploy OpenLab (Zuul and Nodepool) in multiple node mode across multiple cloud provider.
Let's try to finished this task before 2019-04-04 @wangxiyuan @bzhaoopenstack @ZhengZhenyu 

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by wangxiyuan** [comment]
Yeah, we are trying to make openlab deployment support HA across cloud providers so that once a deployment is done again, the openlab service is still working on another cloud.

Work items:
- [ ] Nodepool HA
- [ ] Zuul HA
- [ ] ZooKeeper HA
- [ ] MySQL HA
- [ ] Logs data(Like NFS or something else) HA
- [ ] DNS HA

I'll refresh the progress at any time.

**Comment by mrhillsman** [comment]
@kiwik @wangxiyuan be sure to check with #zuul in IRC for any existing work. the most recent zuul update email had discussion about HA

**Comment by wangxiyuan** [comment]
@mrhillsman sure, thanks for your information.

**Comment by kiwik** [comment]
Hi @wangxiyuan and @ZhengZhenyu I add the task `System health checking after Master/Slave switch` to check Zuul and Nodepool OK after Master/Slave switch.

**Comment by kiwik** [comment]
Master/Slave checking and switching workflow edited by @wangxiyuan https://www.processon.com/view/link/5caaeb3be4b031d022603711

**Comment by kiwik** [comment]
We have enabled OpenLab HA deployment today, map **_http://status.openlabtesting.org_** to new floating ip of new deployment, please refresh your host and browser DNS cache to open OpenLab CI website, PR trigger and periodic trigger jobs are OK in new HA deployment. @theopenlab/dev 

```
Master：
  citynework-openlab-zuul:          4c-8G-400G               4C-8G-400G                   37.153.173.247
  citynetwork-openlab-nodepool:     4c-8G-100G               4C-8G-100G                   37.153.173.155
Slave:
  switch-openlab-zuul:              4c-8G-80G + 400G         m1.large                     86.119.28.137
  switch-openlab-nodepool:          4c-8G-80G                m1.large                     86.119.28.245
Zookeeper:
  vexxhost-openlab-zookeeper:       2c-1G-40G                v1-standard-1                199.204.45.18
```

**Comment by wangxiyuan** [comment]
@mrhillsman @stmcginnis  FYI, The OpenLab environment has been changed to HA mode. The new cluser topology is shown as below：

**Master**：
```
citynework-openlab-zuul       4c-8G-400G    37.153.173.247
citynetwork-openlab-nodepool  4c-8G-100G    37.153.173.155
```
**Slave**:
```
switch-openlab-zuul      4c-8G-80G + 400G     86.119.28.137
switch-openlab-nodepool  4c-8G-80G            86.119.28.245
```
**Zookeeper**:
```
vexxhost-openlab-zookeeper       2c-1G-40G              199.204.45.18
```
