### ISSUE TITLE
Add extra infrastructure providers

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#22]
We have two additional clouds we need to add to nodepool: 

SWITCH
CityNetwork

**Comment by animationzl** [comment]
@mrhillsman 
1. cloud you please show us the portals of SWITCH/CityNetwork, it's sometimes useful to check and operate resources via portal.
2. please let us know if you have any plan on using these two providers, otherwise we will use them as normal providers in nodepool

**Comment by kiwik** [comment]
The resources of SWITCH and CityNetwork have been added into OpenLab, DONE
