### ISSUE TITLE
Gophercloud: Unable to find image with name

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#222]
### Describe the bug

For some reason the `TestVolumeActionsUploadImageDestroy` test keeps failing in Gophercloud and I'm not sure why.

I created a local devstack environment and the test passes for me, so it's hard for me to troubleshoot.

### Related Job information

If the bug is related a CI job, put the job information below:

* job name: gophercloud-acceptance-test 
* job build log link: http://logs.openlabtesting.org/logs/12/1512/1328949142b15973176f2930e053a44b39fd5a91/check/gophercloud-acceptance-test/1bf1760/
* error log piece:

```
=== RUN   TestVolumeActionsUploadImageDestroy
--- FAIL: TestVolumeActionsUploadImageDestroy (55.54s)
    blockstorage.go:50: Attempting to create volume: ACPTTESTOkYVfh6vavC6VZFJ
    tools.go:72: {
          "id": "db04593b-61bd-4fa8-b89e-7d2c53d0a24f",
          "status": "creating",
          "size": 1,
          "availability_zone": "nova",
          "attachments": [],
          "name": "ACPTTESTOkYVfh6vavC6VZFJ",
          "description": "ACPTTEST-DESCgPmk3vB5G1M97Uhh",
          "volume_type": "lvmdriver-1",
          "snapshot_id": "",
          "source_volid": "",
          "metadata": {},
          "user_id": "0f8d6741e3bd45a08e9ba69708409289",
          "bootable": "false",
          "encrypted": false,
          "replication_status": "",
          "consistencygroup_id": "",
          "multiattach": false
        }
    blockstorage.go:73: Successfully created volume: db04593b-61bd-4fa8-b89e-7d2c53d0a24f
    extensions.go:35: Uploading volume db04593b-61bd-4fa8-b89e-7d2c53d0a24f as volume-backed image ACPTTESTY6Gta3TJ6kSgHo6q
    extensions.go:41: Uploaded volume db04593b-61bd-4fa8-b89e-7d2c53d0a24f as volume-backed image ACPTTESTY6Gta3TJ6kSgHo6q
    tools.go:72: {
          "id": "db04593b-61bd-4fa8-b89e-7d2c53d0a24f",
          "container_format": "bare",
          "disk_format": "raw",
          "display_description": "ACPTTEST-DESCgPmk3vB5G1M97Uhh",
          "image_id": "456930b0-922e-4b07-921d-d46b092a32ab",
          "image_name": "ACPTTESTY6Gta3TJ6kSgHo6q",
          "size": 1,
          "status": "uploading",
          "volume_type": {
            "id": "9ee7c4c7-c452-4c8a-b111-2663a2eb0804",
            "name": "lvmdriver-1",
            "display_description": "",
            "is_public": true,
            "extra_specs": {
              "volume_backend_name": "lvmdriver-1"
            },
            "qos_specs_id": "",
            "deleted": false
          }
        }
    extensions.go:54: Getting image id for image name ACPTTESTY6Gta3TJ6kSgHo6q
    convenience.go:35: ESC[1;31mFailure in volumeactions_test.go, line 33: unexpected error ESC[0mESC[1;33m"Unable to find image with name ACPTTESTY6Gta3TJ6kSgHo6q"ESC[0mESC[1;31mESC[0m
    blockstorage.go:121: Attempting to delete volume: db04593b-61bd-4fa8-b89e-7d2c53d0a24f
    blockstorage.go:128: Successfully deleted volume: db04593b-61bd-4fa8-b89e-7d2c53d0a24f
```

### Steps to reproduce the issue

Describe how to reproduce the issue:

* Run `recheck` at https://github.com/gophercloud/gophercloud/pull/1512

### Additional context

I don't know if this is an OpenLab issue specifically. But since I can't reproduce the issue in a devstack environment, I'm not sure how else I can troubleshoot. Any pointers are appreciated 🙂

**Comment by jtopjian** [comment]
Also, if it's easier for me to disable this test, I'm happy to do that, too.

**Comment by jtopjian** [comment]
The test has passed here: http://logs.openlabtesting.org/logs/14/1514/61c1f12b2de3192f5f8d36fbf7cd56681ea95f3c/check/gophercloud-acceptance-test/e84daca/

So I'm really confused on why it's failing sometimes. Maybe there are certain nodes that have characteristics which are making the test fail?

In any case, I'm just going to disable this test. I know it passes under normal circumstances and that's good enough for now.

**Comment by kiwik** [comment]
@jtopjian sorry to reply late, @bzhaoopenstack would you please to check this issue, sound like bug exist.

**Comment by bzhaoopenstack** [comment]
I post a recheck in the above PR, but I found @jtopjian had skipped the test. Also my colleage and I check the logs of previous 3 fail tests from openlab-ci, but seems the related LOG missed, we can not find any related error message towards that testcase. The passed one used with the same cloud provider "switch-openlab", and the other things are the same all the time. So I agree with you about "Maybe there are certain nodes that have characteristics which are making the test fail" now, but for more clear, I need to reproduce the issue for moving forward.

**Comment by jtopjian** [comment]
Hi all,

Thank you for looking into this 🙂 

I have opened https://github.com/gophercloud/gophercloud/pull/1519 which re-enables this test.

I'm curious about what you find, but there is no rush on resolving this issue.

**Comment by bzhaoopenstack** [comment]
Hi @jtopjian ,  I have comments on https://github.com/gophercloud/gophercloud/pull/1519 
Please try to change the local conf and fix. I saw the devstack logic, when we enable glance-api, it will set the loopback device(which used by swift) as a default size(2G), so we can set "SWIFT_LOOPBACK_DISK_SIZE" in devstack local.conf for fix it. Thank you

**Comment by jtopjian** [comment]
> Please try to change the local conf and fix

OK, where do I make this change?

**Comment by moo-ai** [comment]
Hi @jtopjian ,
I think something like:
- role: install-devstack
  enviroment:
     DEVSTACK_LOCAL_CONF: 'SWIFT_LOOPBACK_DISK_SIZE=5G'
More details about this please see: http://git.openstack.org/cgit/openstack-infra/devstack-gate/tree/devstack-vm-gate.sh#n634  
Some other examples: https://github.com/theopenlab/openlab-zuul-jobs/blob/1c2d440f108bfeaec15d912ebec6eb8a161ea851/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml#L8

I think we can add the related setting in https://github.com/gophercloud/gophercloud/blob/master/.zuul/playbooks/gophercloud-acceptance-test/run.yaml#L13

**Comment by bzhaoopenstack** [comment]
Hi @jtopjian,
I will fix in openlab for this issue. Sorry for confused.

**Comment by jtopjian** [comment]
> I will fix in openlab for this issue. Sorry for confused.

No problem at all - thank you very much!
