### ISSUE TITLE
pulling docker.io/k8scloudprovider/cinder-csi-plugin:latest has outdated images occasionally

### ISSUE THREAD

**Issue by danielraad** [theopenlab/openlab#223]
### Describe the bug

pulling docker.io/k8scloudprovider/cinder-csi-plugin:latest and I am getting version 0.2.0 of csi-cinderplugin, there might be a job pushing an outdated version.

please view: https://github.com/kubernetes/cloud-provider-openstack/issues/537

### Steps to reproduce the issue
```
docker run -i -t docker.io/k8scloudprovider/cinder-csi-plugin:latest /bin/sh

setsh-4.2# /bin/cinder-csi-plugin --cloud-config test --endpoint test --nodeid test
I0320 20:44:05.831579      64 driver.go:49] Driver: csi-cinderplugin version: 0.2.0
````

`csi-cinderplugin version: 1.0.X` is expected from cinder-csi-plugin:latest

**Comment by kiwik** [comment]
Looks this's root reason, if the periodic job run on branch v1.10 of cloud-provider-openstack, that will push "latest" image, but 0.2.0 actually.

https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml#L156

Solution:
1. Only run periodic jobs on master branch
2. Get and set actual version from source code in ansible script, then push image

**Comment by kiwik** [comment]
Related with #173
