### ISSUE TITLE
ClearLinux DL Stack

### ISSUE THREAD

**Issue by YangLiang3** [theopenlab/openlab#226]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [v ] Performance
- [ v] Scale
- [ ] Reliability
- [ ] Resiliency
- [ v] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [v ] Machine Learning
- [v ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
Yes, ClearLinux - https://clearlinux.org
### Brief project description
Clear Linux OS is an open source, rolling release Linux distribution optimized for performance and security, from the Cloud to the Edge, designed for customization, and manageability. I am testing ClearLinux DL stack for presenting to others during hackathon for their understanding of the stack and participation in making it better.
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://github.com/clearlinux
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
1 Baremetal
### What OS are you planning to use?
Ubuntu 16.04
### Any special network configuration you expect or anticipate implementing?
multi-users login
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
GPU
### What testing are you planning to implement or need assistance implementing?
    ClearLinux is a great OS for AI/ML/DL workloads. In particular, I want to increase the usability of ClearLinux's DL reference stack - https://clearlinux.org/stacks. The stack includes highly tuned software components across the operating system (Clear Linux OS), deep learning framework (TensorFlow*, PyTorch*), deep learning libraries (Intel® Math Kernel Library for Deep Neural Networks (MKL-DNN)) and other software components. More information on the DL stack can be found here - https://clearlinux.org/documentation/clear-linux/tutorials/dlrs
### How will this testing advance application and/or tooling built on-top of open infrastructure?
   ClearLinux DL reference stack utilizes open source infrastructure components. Having a full stack that works well reduces friction to the adoption of deep learning with open source infrastructure components. Also, testing should make it easier to identify components that can be swapped with other open source infrastructure components or commercial products that can be augmented with open source infrastructure components.
### Will you publish blog or paper from your testing?

- [ v] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
1.It need be permitted login the server by muti-users. 
2. please give the using right until 22th April.
thanks

**Comment by YangLiang3** [comment]
@mrhillsman  please help assign a host server based on ubuntu 16.04. Thanks :)

**Comment by mrhillsman** [comment]
@hogepodge @stmcginnis please review and approve

**Comment by mrhillsman** [comment]
I believe this issue can be closed, re-open if necessary
