### ISSUE TITLE
Add support for contianerd

### ISSUE THREAD

**Issue by Yikun** [theopenlab/openlab#227]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
containerd 

### Brief project description
containerd is available as a daemon for Linux and Windows. It manages the complete container lifecycle of its host system, from image transfer and storage to container execution and supervision to low-level storage to network attachments and beyond.

As of February 28, 2019, containerd is officially a graduated project within the Cloud Native Computing Foundation.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/containerd/containerd

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
ARM VMs

### What OS are you planning to use?
Ubuntu

### Any special network configuration you expect or anticipate implementing?
No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
aarch64/arm64

### What testing are you planning to implement or need assistance implementing?
ARM CI for containerd

### How will this testing advance application and/or tooling built on-top of open infrastructure?
https://github.com/containerd/containerd/issues/2901
Add the arm release support

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
Nothing special

**Comment by Yikun** [comment]
The support for containerd arm64 build has been added the OpenLab, there are two way to trigger:

1. [**Periodic  job**](http://status.openlabtesting.org/builds?job_name=envoy-build-arm64): The periodic job had been enabled, now you can see the periodic `containerd-build-arm64` job for `containerd/containerd` in [OpenLab dashboard](http://status.openlabtesting.org/builds?job_name=envoy-build-arm64) [1], the arm build job of `containerd/containerd` master branch will be ran everyday.

2. [**PR triggered job**](https://github.com/theopenlab/containerd/pull/3): you can also do some test on PR triggered in repo [theopenlab/containerd](https://github.com/theopenlab/containerd) [2], the demo like [PR](https://github.com/theopenlab/containerd/pull/3) [3]

So maybe we can close this issue now.

**Comment by kiwik** [comment]
https://github.com/containerd/containerd/pull/3242 PR have been merged into containerd master, close.
