### ISSUE TITLE
Labchecker version 1.1

### ISSUE THREAD

**Issue by Yikun** [theopenlab/openlab#232]
### 1. Zuul-Jobs check
- [x]  Image and recover check
Recover the cirros image

### 2. Enable periodic check of Labchecker
- [x]  Add the labchecker call after deploy.
- [x]  Add the periodic check using crontab.
- [x]  Add the check to ansible role.
- [x]  Add the “theopenlab/ops” to notification list.

### 3. Cloud provider tenant resource purge
- [ ] Clean up all of related resource when cloud provider tenant EOL, like: network, router, image, servers ,keypair

(yikun) The cleanup cmds are dangerous operations, so I'd like to introduce a command like "openlab hints cleanup" in here.

**Comment by kiwik** [comment]
Hi @Yikun , I add a new request about `Cloud provider tenant resource purge`

**Comment by kiwik** [comment]
@Yikun Any updates?

**Comment by Yikun** [comment]
@kiwik Thanks for reminder, I didn't get enough time to finish this, I am going to try to complete it before May 31.

**Comment by Yikun** [comment]
Add VM create validation
