### ISSUE TITLE
Test Request: ChubaoFS demo setup

### ISSUE THREAD

**Issue by sjzlsr** [theopenlab/openlab#233]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [x] Performance
- [x] Scale
- [x] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?

Yes, https://github.com/chubaofs/cfs

### Brief project description

CFS(Chubao File System) is a distributed fle system that is designed to natively support large scale container platforms, with the following features: scale-out metadata management; strong consistency; multiple volumes; POSIX-compatible.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?

Yes, https://github.com/chubaofs/cfs

### What kind of machines (VMs or Baremetal) and how many do you expect to use?

Baremetal.

4 nodes for master, metanode and datanode. (64G RAM, 1T storage)
1 node for client. (8G RAM)

### What OS are you planning to use?

CentOS 7

### Any special network configuration you expect or anticipate implementing?

No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?

No

### What testing are you planning to implement or need assistance implementing?

We are eastablishing a demo deployment for the 9th Open Source Hackathon in Shenzhen, so that attenders can try it out during the session.

### How will this testing advance application and/or tooling built on-top of open infrastructure?

CFS is a distributed file system with POSIX-compitible interface. Mounting a client and use it just like local file systems. Strong consistency and high availability is handled in the backend.

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

**Comment by kiwik** [comment]
Hi @stmcginnis , @mrhillsman , please help reviewing this test request.

**Comment by mrhillsman** [comment]
@hogepodge please review

**Comment by mrhillsman** [comment]
@sjzlsr is this still required?

**Comment by sjzlsr** [comment]
I guess not. Thanks anyway.
