### ISSUE TITLE
cloud-provider-openstack CI Failure

### ISSUE THREAD

**Issue by adisky** [theopenlab/openlab#236]
Thank you for reporting bug!

### Describe the bug
cloud-provider-openstack CI jobs are Failing, i have found following error in kubelet logs
> failed to run Kubelet: invalid kubeconfig: invalid configuration: [unable to read client-cert /var/run/kubernetes/client-kubelet.crt for local-up-cluster due to open /var/run/kubernetes/client-kubelet.crt: no such file or directory, unable to read client-key /var/run/kubernetes/client-kubelet.key for local-up-cluster due to open /var/run/kubernetes/client-kubelet.key: no such file or 
 directory

However i am not able to reproduce the same to my local system, I am able to successfully run local-up-cluster.sh from latest master and latest cloud-provider-openstack. From the job-output.txt, it is copying the file, but kubelet not able to access it, It might be a directory permission issue.
### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
http://logs.openlabtesting.org/logs/82/582/7d3a15a73d4a432e4ee1bd19bed6ef3362485a6e/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/8320df6/
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by adisky** [comment]
cc @mrhillsman @kiwik

**Comment by kiwik** [comment]
hi @h00130372  , please help @adisky to check this cloud-provider-openstack issue, thank you

**Comment by h00130372** [comment]
I found a bug of kubernetes and the pr is merged: https://github.com/kubernetes/kubernetes/pull/76495#issuecomment-483099105

will retest the jobs.

**Comment by adisky** [comment]
@h00130372 Thank you so much for the fix.

**Comment by adisky** [comment]
@h00130372 @lingxiankong seems job for octavia ingress controller still failing
https://logs.openlabtesting.org/logs/78/578/4e22610ef2e3e817af20a53653e2c7ab03176226/cloud-provider-openstack-acceptance-test-lb-octavia/cloud-provider-openstack-acceptance-test-lb-octavia/28345c0/

**Comment by h00130372** [comment]
@adisky 
I think the bug is fixed:) see the job log: https://logs.openlabtesting.org/logs/87/587/b21c6da9064d333c5dbc4dc867644aa019a919ad/cloud-provider-openstack-acceptance-test-lb-octavia/cloud-provider-openstack-acceptance-test-lb-octavia/b6fedc6/

**Comment by h00130372** [comment]
The bug is fixed, close this issue.
