### ISSUE TITLE
Implement shade and openstacksdk

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#24]
- [ ] get OpenLab github app attached to ansible/ansible repo ( for shade-ansible-devel-functional-devstack )
- [ ] setup jobs that can run shade, openstacksdk, and python-openstackclient functional tests against older clouds and report back to openstack gerrit as a 3rd party CI
- [ ] setup jobs that run shade and openstacksdk functional tests against live public cloud endpoints

**Comment by mrhillsman** [comment]
Discussion with Monty Taylor to parse into action items:

run shade's ansible functional tests on patches to ansible in OpenLab
  - hooked up in infra land right now here: http://git.openstack.org/cgit/openstack-infra/project-config/tree/zuul.d/projects.yaml#n4
 - the shade-ansible-devel-functional-devstack job should still be defined in the shade repo

( we'll need to connect with someone at ansible about getting the OpenLab github app attached to the ansible/ansible repo - @mordred )

Additional Notes:
setting up jobs that can run shade, openstacksdk and python-openstackclient functional tests against older clouds and report back to openstack gerrit as a 3rd party CI
 - all three want to be able to continue to support clouds older than what we can spin up in infra
 - as well as deprecated/removed services, like nova-network for example

setting up jobs that run shade and openstacksdk functional tests against live public cloud endpoints
 - will almost CERTAINLY require updates to the functional test suites themselves as they currently make some assumptions about the cloud in question being a devstack cloud

( it seems like making some openlab specific jobs that potentially use shade-functional-devstack and openstacksdk-functional-devstack as a parent )

**Comment by mrhillsman** [comment]
@emonty thanks for taking time to discuss, here is where we will be tracking this.

**Comment by liu-sheng** [comment]
The openlab integration about running ansible tests against shade and openstack sdk has been implemented in https://github.com/theopenlab/openlab-zuul-jobs/pull/245, based on that job definitions, we can expand the supported more different versions.

**Comment by kiwik** [comment]
Like @liu-sheng say, we trace ansible jobs in theopenlab/openlab-zuul-jobs#245 and will try to test against some public cloud in https://github.com/theopenlab/openlab/issues/71 , so we can close this issue to avoid confusion.
