### ISSUE TITLE
Request to Join OpenLab Team

### ISSUE THREAD

**Issue by Savasw** [theopenlab/openlab#240]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
Sapan Vaswani
### Github account id
savasw
### Email
sapan.vaswani@click2cloud.net
### Company/Organization
Click2Cloud Inc
### IRC nickname (Optional)
savasw_

**Comment by kiwik** [comment]
Welcome @Savasw , let me inviting you into team

**Comment by Savasw** [comment]
Thanks @kiwik.

**Comment by liu-sheng** [comment]
welcome @Savasw :)

**Comment by h00130372** [comment]
welcome :)

**Comment by kiwik** [comment]
@Savasw have been in team @theopenlab/dev , close this issue now.
