### ISSUE TITLE
Add arm64 ci testing for kubernetes-sigs/cluster-api

### ISSUE THREAD

**Issue by detiber** [theopenlab/openlab#241]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [x] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [x] Other

### If this is for an open source project what is it?

kubernetes-sigs/cluster-api

### Brief project description

The Cluster API is a Kubernetes project to bring declarative, Kubernetes-style APIs to cluster creation, configuration, and management. It provides optional, additive functionality on top of core Kubernetes.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?

Yes: https://github.com/kubernetes-sigs/cluster-api

### What kind of machines (VMs or Baremetal) and how many do you expect to use?

VMs, expected number unkown.

### What OS are you planning to use?

Linux, no particular preference on distribution.

### Any special network configuration you expect or anticipate implementing?

No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?

arm64

### What testing are you planning to implement or need assistance implementing?

CI for cluster-api running against ARM

### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?

Results will be available in Kubernetes test-grid

**Comment by stmcginnis** [comment]
/lgtm

Thanks!

**Comment by kiwik** [comment]
/lgtm @detiber 
Please follow the [guide](https://docs.openlabtesting.org/contributors/development-guide). It's easy to enable PR and periodic triggered jobs, if you want to support PR triggered jobs, you should install OpenLab github APP in kubespray project, and commit integration job PR in [openlab-zuul-jobs](https://github.com/theopenlab/openlab-zuul-jobs), when the two steps are completed, @theopenlab/ops team will enable config in zuul side, then OpenLab testing resources will be free for your project.

You mentioned test-grid log uploading and ARM support, luckily OpenLab have support both of them, please refer to https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml and https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L1976
