### ISSUE TITLE
Testgrid Results Failing

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#245]
Thank you for reporting bug!

### Describe the bug
Bug is described heavily at the following link: https://github.com/kubernetes/kubernetes/issues/76896#issuecomment-485452736
(finished.json is reporting failure when tests actually pass due to regex in upload_e2e.py)

### Related Job information
If the bug is related a CI job, put the job information below:
* job name: cloud-provider-openstack-acceptance-test-e2e-conformance
* job build log link: N/A
* error log piece: N/A

### Steps to reproduce the issue
Describe how to reproduce the issue:
https://testgrid.k8s.io/conformance-cloud-provider-openstack#periodic-master
https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack

**Comment by kiwik** [comment]
k8s cluster building error cause this issue, and that error have be resolved, https://k8s-testgrid.appspot.com/conformance-cloud-provider-openstack , closed
