### ISSUE TITLE
Test Request: Kubespray

### ISSUE THREAD

**Issue by Miouge1** [theopenlab/openlab#248]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [x] Reliability
- [ ] Resiliency
- [ ] Integration
- [x] Multi-Cloud
- [x] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
Kubespray
### Brief project description
Kubespray is Kubernetes Certified installer focused to deploy a production ready Kubernetes clusters on any platform.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/kubernetes-sigs/kubespray/

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VMs are preferred but we could work with baremetal if you want.

We expect to run CI jobs deploying a 2 or 3 nodes cluster.

### What OS are you planning to use?
Ubuntu, CentOS or CoreOS
### Any special network configuration you expect or anticipate implementing?
We expect to use Neutron network, routers and floating IPs

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?

Each VM would be around 2 vCPU and 2GB of RAM, 2 or 3 VMs per CI job.
This type of CI would be on arm or x86, but since the normal Kubespray CI is already running on x86, it could be cool to do OpenStack CI on ARM64 to cover more grounds.

### What testing are you planning to implement or need assistance implementing?

We plan to use this for CI jobs in order to test:
1. How Kubespray setups OpenStack VMs in: [contrib/terraform/openstack](https://github.com/kubernetes-sigs/kubespray/tree/master/contrib/terraform/openstack)
2. How Kubespray install the OpenStack cloud providers
3. ARM64 compatibility (optional)

Kubespray is a set of Ansible playbook, so we're hoping that the Zuul job description won't be too complicated.

### How will this testing advance application and/or tooling built on-top of open infrastructure?

Adding this type of CI will make sure that Kubespray works smoothly on OpenStack both its terraform recipes and the OpenStack-Kubernetes driver deployed.

### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?

CI results will be available in either periodical jobs or in PRs.

**Comment by mrhillsman** [comment]
Hey @Miouge1 thanks for the submission. There will probably be some delay in review/approval due to the Open Infra Summit but @stmcginnis or @hogepodge will check as soon as possible.

**Comment by stmcginnis** [comment]
lgtm and this would be a great thing to add.

**Comment by kiwik** [comment]
/lgtm @Miouge1 
Please follow the [guide](https://docs.openlabtesting.org/contributors/development-guide). It's easy to enable PR and periodic triggered jobs, if you want to support PR triggered jobs, you should install OpenLab github APP in kubespray project, and commit integration job PR in [openlab-zuul-jobs](https://github.com/theopenlab/openlab-zuul-jobs), when the two steps are completed, @theopenlab/ops team will enable config in zuul side, then OpenLab testing resources will be free for your project.

You mentioned multiple nodes deployment and ARM support, luckily OpenLab have support both of them, please refer to https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L2077-L2095 and https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L1976

**Comment by Miouge1** [comment]
@kiwik OK thank you for the info. I'll dig into it.
