### ISSUE TITLE
Test request for OpenStack provider in Virtual Kubelet

### ISSUE THREAD

**Issue by hongbin** [theopenlab/openlab#255]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
This is for the OpenStack Zun provider for Virtual Kubelet: https://github.com/virtual-kubelet/virtual-kubelet#openstack-zun-provider

### Brief project description
OpenStack Zun provider for Virtual Kubelet connects your Kubernetes cluster with OpenStack in order to run Kubernetes pods on OpenStack Cloud.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes. https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/openstack/README.md

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
One VM per job. Start with one or two jobs. Jobs trigger on incoming pull request in GitHub. Expect to have one pull request per day.

### What OS are you planning to use?
Ubuntu.

### Any special network configuration you expect or anticipate implementing?
None

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
2 VCPU, 8G of RAM in minimum. 4 VCPU, 12G of RAM in desire.

### What testing are you planning to implement or need assistance implementing?
Test the OpenStack provider in Virtual Kubelet

### How will this testing advance application and/or tooling built on-top of open infrastructure?
It verifies Virtual Kubelet works properly with different OpenStack clouds.

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
The test run devstack, install docker/k8s with a devstack plugin. We plan to start from testing docker with a future addition of testing Kata Container (which might not be able to run on VMs).

**Comment by hongbin** [comment]
@mrhillsman @stmcginnis ping for review

**Comment by hongbin** [comment]
@kiwik ping for approval

**Comment by mrhillsman** [comment]
apologies @hongbin this one went under the radar

**Comment by mrhillsman** [comment]
@hongbin for jobs to run on every PR the Github app needs to be installed: https://docs.openlabtesting.org/contributors/development-guide#integrate-with-openlab-ci

**Comment by kiwik** [comment]
/lgtm @hongbin 
Please follow the guide https://docs.openlabtesting.org/contributors/development-guide. It's easy to enable PR triggered jobs, like @mrhillsman say, you should install OpenLab github APP in Virtual Kubelet project, and commit integration job PR in [openlab-zuul-jobs](https://github.com/theopenlab/openlab-zuul-jobs), when the two steps are completed, @theopenlab/ops team will enable config in zuul side.

**Comment by hongbin** [comment]
@mrhillsman @kiwik thanks for providing the links and instructions. I will work on it after Virtual Kubelet split out its provider: https://github.com/virtual-kubelet/virtual-kubelet/issues/494

**Comment by hongbin** [comment]
I tried to install the Github app, but got struck on this: https://ibb.co/wgccQPz . I assume the app requires some permission that needs to be granted by someone?

**Comment by kiwik** [comment]
@hongbin OpenLab Github APP need read access for PR open, reopen event of target repository to trigger testing and write access for PR comments to append testing result in comments, so if you have repository maintainer or admin role, you should be able to install successfully. And you can try to install OpenLab github APP into your owned repository as an example.

https://docs.openlabtesting.org/contributors/connect-to-openlab

**Comment by hongbin** [comment]
@kiwik thanks for the hints. @kevin-zhaoshuai do you have the permission to the app. If not, we need to ask virtual kubelet folks to give us the permission.

**Comment by kevin-zhaoshuai** [comment]
@hongbin Just tried and I find that install OpenLab APP to "virtual-kubelet/openstack-zun" need requests. I've already click the requests

**Comment by hongbin** [comment]
@anubhavmishra @pires @ritazh @vaishnavk @yaron2 

I and @kevin-zhaoshuai are the maintainers of virtual-kubelet/openstack-zun. We want to install the Openlab Github app into our repository, but it looks neither me nor @kevin-zhaoshuai have enough permission to do it. Could you guys help? Please refer @kiwik comment above for details. Appreciate your help.

**Comment by hongbin** [comment]
@anubhavmishra @pires @ritazh @vaishnavk @yaron2

You are members of Virtual Kubelet organization, so I ping you for help. Any remark for my comment above?

**Comment by cpuguy83** [comment]
I've added the openlab app to the VK org for the openstack-zun.

**Comment by hongbin** [comment]
@cpuguy83 thanks

**Comment by hongbin** [comment]
@kiwik I saw the Github app is installed, and I have added the .zuul.yaml file (https://github.com/virtual-kubelet/openstack-zun/blob/master/.zuul.yaml). I submitted a PR (https://github.com/virtual-kubelet/openstack-zun/pull/7) to test if the CI is triggered, but it looks the CI still didn't trigger. Any hints to do the further trouble-shooting?

**Comment by wangxiyuan** [comment]
@hongbin `openstack-zun` is added into openlab now. Please set the branch which need to run CI as the `protected branch` in github and then try `recheck` again.

**Comment by hongbin** [comment]
@wangxiyuan it works. i saw the job was triggered now. thanks.

**Comment by wangxiyuan** [comment]
https://github.com/virtual-kubelet/openstack-zun/pull/7#issuecomment-529272330
CI works now. Please update `.zuul.yaml` next.

Close this issue now.

**Comment by wangxiyuan** [comment]
Feel free to job IRC #askopenlab channel if you have any question.
