### ISSUE TITLE
Test benchmarks of kubeflow/volcano on k8s 1.14 cluster

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#256]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [x] Machine Learning
- [x] Artificial Intelligence
- [x] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
yes

### Brief project description
Volcano: A Kubernetes native system for high performance workload, e.g. AI/ML, BigData, HPC http://volcano.sh

Kubeflow: Machine Learning Toolkit for Kubernetes
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
yes
https://github.com/volcano-sh
https://github.com/kubeflow

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VM

### What OS are you planning to use?
Ubuntu-xenial 

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

**Comment by kiwik** [comment]
https://github.com/theopenlab/openlab-zuul-jobs/pull/514 and related PRs have been merged into openlab-zuul-jobs, closed, thank you @liu-sheng
