### ISSUE TITLE
Enable GCP log uploding in kind-integration-test-arm64 job

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#257]
Thank you for reporting bug!

### Describe the bug
We have run job `kind-integration-test-arm64` in OpenLab for a while, everything looks good and stable. We should update job define and enable E2E log uploading logic, and according to the [discuss](https://github.com/kubernetes-sigs/kind/issues/188#issuecomment-489267455) in kind project side, GCP bucket `gs://k8s-conformance-kind-arm64-openlab` have been created for log storing, and Melvin have added new GCP token secert into openlab-zuul-jobs in https://github.com/theopenlab/openlab-zuul-jobs/pull/511 , let's enabling log uploading.

### Related Job information
If the bug is related a CI job, put the job information below:
* job name: kind-integration-test-arm64
* job build log link: http://status.openlabtesting.org/builds?project=kubernetes-sigs/kind
* error log piece: NA

### Steps to reproduce the issue
NA

### Additional context
NA

**Comment by dims** [comment]
Thanks @kiwik !

**Comment by kiwik** [comment]
@ZhengZhenyu please close the issue, when you complete the config mapping in testgrid side.

**Comment by ZhengZhenyu** [comment]
> @ZhengZhenyu please close the issue, when you complete the config mapping in testgrid side.

ACK

**Comment by ZhengZhenyu** [comment]
https://github.com/kubernetes/test-infra/pull/13273/ merged
