### ISSUE TITLE
Trace multiple CI/nodepool/zk backend ENV will cause nodepool conflict error.

### ISSUE THREAD

**Issue by bzhaoopenstack** [theopenlab/openlab#258]
Thank you for reporting bug!

### Describe the bug
If we have multiple CI env with the same nodepool and openstack cloud configuration. The nodepool will maintain the same scale instances, if one side creates the nodepool instance, the other side will treat this nodepool as a orphan vm, it will remove it. In the end, the nodepool of both sides won't work accuratelly and hit conflict.

### Steps to reproduce the issue
Deploy 2 CI system with the same configuration.
Such as the Online CI system, and another deployment deployed by labkeeper.

### Additional context
https://github.com/openstack-infra/nodepool/blob/master/nodepool/driver/openstack/provider.py#L477

**Comment by kiwik** [comment]
@bzhaoopenstack maybe we can set the unique UUID for the nodepool deployment when we use labkeeper to deploy, just an idea, should verify it.
