### ISSUE TITLE
Can't delete the server of Citynetwork cloud

### ISSUE THREAD

**Issue by h00130372** [theopenlab/openlab#259]
Thank you for reporting bug!

There is a server in Citynetwork cloud can't be deleted.

nodepool list, we can see the node is in deleting and locked:
root@donotdel-openlab-nodepool:/home/ubuntu# nodepool list |grep  5a7bf3cc-4194-4f4f-8009-5bbcd2e76446
| 0000023620 | citynetwork-openlab |                        | 5a7bf3cc-4194-4f4f-8009-5bbcd2e76446 | None           | None | deleting | 00:00:09:02 | locked   |

serer list in citynetwork cloud provider:
openstack --os-cloud citynetwork server list |grep  5a7bf3cc-4194-4f4f-8009-5bbcd2e76446
| 5a7bf3cc-4194-4f4f-8009-5bbcd2e76446 | ubuntu-xenial-citynetwork-openlab-0000023549    | ACTIVE | openlab-net=10.3.0.29                 |                                  | 4C-8GB-100GB   |

And server show we can find the task_state of the server is deleting, and I tried to delete in citynetwork, but it doesn't work, the server can't be deleted.

**Comment by h00130372** [comment]
Hi @mrhillsman , could you help to notify Citynetwork to delete this server and to find what's happened?
And some info(perhaps) related with https://github.com/theopenlab/openlab/issues/258.

**Comment by mrhillsman** [comment]
@tobberydberg could you investigate this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tobberydberg** [comment]
solved!

**Comment by kiwik** [comment]
Thank you @tobberydberg and @mrhillsman for so quick reply, the issue have been resolved.
