### ISSUE TITLE
Metal³ (Metal Kubed) CI and Gating

### ISSUE THREAD

**Issue by intlabs** [theopenlab/openlab#260]
# Metal³ (Metal Kubed) CI and Gating

### What is your focus?
- [ ] Performance
- [ ] Scale
- [x] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [x] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?

This would be for the Metal³ project (pronounced: Metal Kubed).

### Brief project description
Metal³ provides components that allow you to do bare metal host management for Kubernetes. Metal³ works as a Kubernetes application, meaning it runs on Kubernetes and is managed through Kubernetes interfaces.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?

Yes, the code is hosted here: https://github.com/metal3-io

### What kind of machines (VMs or Baremetal) and how many do you expect to use?

Initially, it would make sense to target single machines (either BM or VM's that support nested virtualization) to validate the e2e integration of the project - these would need to be sized to allow three small nested VMs, driven by vbmc as an analog to physical hardware, to be created within them.

### What OS are you planning to use?

The current development/e2e environment targets CentOS, though it would be strongly desirable to support a Debian derived distribution as well.

### Any special network configuration you expect or anticipate implementing?

None

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?

The machines will need to be sized to allow three VMs (4vCPU, 8Gb RAM) to be created in addition to the support services.

### What testing are you planning to implement or need assistance implementing?

The testing will be e2e integration testing of the Metal³ project to manage bare-metal nodes via Kubernetes custom resource objects.

### How will this testing advance application and/or tooling built on-top of open infrastructure?

This testing will enable the validation of bare-metal node management via Kubernetes.

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?

None

**Comment by mrhillsman** [comment]
@intlabs please find general instructions for setting up the CI here - https://docs.openlabtesting.org/publications/contributors/connect-to-openlab

**Comment by intlabs** [comment]
Will by Monday @mrhillsman! Thanks so much for all your help and support :)

**Comment by kiwik** [comment]
@intlabs if you have any question, feel free to raise it in OpenLab IRC channel #askopenlab on freenode, @theopenlab/dev team stand by :)
