### ISSUE TITLE
Add support for Envoy

### ISSUE THREAD

**Issue by Yikun** [theopenlab/openlab#262]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
CNCF project: envoyproxy/envoy

### Brief project description
Envoy is an open source edge and service proxy, designed for cloud-native applications, is a graduated project within the Cloud Native Computing Foundation.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/envoyproxy/envoy

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
ARM VMs

### What OS are you planning to use?
Ubuntu

### Any special network configuration you expect or anticipate implementing?
No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
aarch64/arm64

### What testing are you planning to implement or need assistance implementing?
ARM CI for containerd

### How will this testing advance application and/or tooling built on-top of open infrastructure?
https://github.com/envoyproxy/envoy/issues/1861
https://github.com/envoyproxy/envoy/pull/6981

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
Nothing special

**Comment by kiwik** [comment]
Envoy periodic job have been executed in OpenLab, it's stable and ready to merged into official Envoy project, https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/projects.yaml#L113-L118  and http://status.openlabtesting.org/builds?job_name=envoy-build-arm64

**Comment by kiwik** [comment]
Closed, periodic jobs running looks good, will report and trace issues in envoy side, thank you @Yikun working hard

**Comment by kiwik** [comment]
Append related PR https://github.com/envoyproxy/envoy/pull/6981
