### ISSUE TITLE
[Openlab Web Redesign] set tags for jobs

### ISSUE THREAD

**Issue by huangtianhua** [theopenlab/openlab#264]
Let's make things better!

We decide to redesign the openlab web, and some metadata of jobs have to set in job 'tags',
like: 
- job:
    name: spark-integration-test-kubeadm-k8s-v1.14.0
    parent: init-test
    description: |
      Run integration tests of spark of master against with v1.14.0 k8s cluster deployed by kubeadm
    run: playbooks/spark-integration-test-kubeadm-k8s/run.yaml
    post-run: playbooks/spark-integration-test-kubeadm-k8s/post.yaml
    secrets:
      - openlab_dockerhub
    vars:
      k8s_log_dir: '{{ ansible_user_dir }}/workspace/logs/kubernetes'
      kubernetes_version: 1.14.0
    tags:
      - Category:BigData
      - Project:apache/spark
      - App:Spark@master
      - App:Kubernetes@v1.14.0
      - Arch:X86
      - BuildType:Integration test

**Comment by kiwik** [comment]
Related PR have been merged, close this.
