### ISSUE TITLE
Just to Know the architecture of OpenLab Integration with Zuul. How Zuul is doing CICD with OpenLab Project.

### ISSUE THREAD

**Issue by c2c-engg-20170105** [theopenlab/openlab#271]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

**Comment by kiwik** [comment]
@c2c-engg-20170105 I'm glad to see you are interested in OpenLab. OpenLab use Zuul and Nodepool, just like: [OpenStack](https://www.openstack.org/) community CI, we use Zuul [github connection](https://zuul-ci.org/docs/zuul/admin/drivers/github.html) to integrate github projects with OpenLab, and use Nodepool to manage the testing resources that are donated by some OpenStack public cloud vendors.

**Comment by kiwik** [comment]
Let me inviting you into team @c2c-engg-20170105
