### ISSUE TITLE
This go2xunit's bug will impact report generation of CI system when running gophercloud acctest with all test case opened, either fix it or switch to a new one.

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#28]
https://github.com/tebeka/go2xunit/issues/29
https://github.com/tebeka/go2xunit/issues/50

**Comment by kiwik** [comment]
I hope go2xunit team can address this issue, OpenLab just use this tools as will, or we can find other tools to replace.

**Comment by kiwik** [comment]
No trace in OpenLab
