### ISSUE TITLE
fog-openstack integration

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#29]
Initial conversation started:

https://github.com/fog/fog-openstack/issues/385

**Comment by mrhillsman** [comment]
jobs created in test environment
successfully passing

gitter notification outstanding currently

**Comment by mrhillsman** [comment]
@kiwik @animationzl @liu-sheng hey gentlemen, the app has been installed for fog-openstack as noted in https://github.com/fog/fog-openstack/issues/385

i have also created a PR for adding .zuul.yaml to fog-openstack - https://github.com/fog/fog-openstack/pull/392 - we should update our main.yaml once this PR is merged

**Comment by kiwik** [comment]
https://github.com/fog/fog-openstack/pull/392 have been merged, I think we can close the issue now.
