### ISSUE TITLE
Need virtual machine

### ISSUE THREAD

**Issue by c2c-engg-20170105** [theopenlab/openlab#290]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Other

### If this is for an open source project what is it?
No
### Brief project description
Nee to test source code 
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
No, Source code is not opensource
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
centos 7
### Will you publish blog or paper from your testing?

- [ ] Yes
- [ ] No - if no, how will you present your results?

**Comment by stmcginnis** [comment]
Sorry, we need to deny this. OpenLab is for testing open source projects. This would need to be for setting up open source activities, so this not being open source and just being a request for a VM, that does not meet the mission requirements to be part of OpenLab.

**Comment by hogepodge** [comment]
Agree to deny.
