### ISSUE TITLE
OpenLab Web Redesign

### ISSUE THREAD

**Issue by huangtianhua** [theopenlab/openlab#291]
Let's make things better!

The goal is to make the openlabtesting.org site an easy to use place for these types of users to find the information they need and discover new projects that they can use to meet their needs.
The redesign doc located: https://docs.google.com/document/d/1XYHOBHs5RmjV77pU2AWP2kvLPsjmPHTfLbckqrMoWVQ/edit# 

### Describe the solution you'd like
There are several changes prepare for the web redesign work, refactor jobs using inheritance structure, and put the jobs which scope is release(target project)-against-release(backend) into periodic pipeline, set tags for these jobs, later these jobs will shown on the new web.

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by kiwik** [comment]
All related changes in OpenLab job define have been completed, close this issue.
