### ISSUE TITLE
cluster-api-provider-openstack-image-build job failed to docker login

### ISSUE THREAD

**Issue by hidekazuna** [theopenlab/openlab#301]
Thank you for reporting bug!

### Describe the bug

The cluster-api-provider-openstack-image-build job failed to docker login and push the image in the end, even if job result is SUCCESS.

### Related Job information
If the bug is related a CI job, put the job information below:
* job name
cluster-api-provider-openstack-image-build
* job build log link:
https://logs.openlabtesting.org/logs/periodic-10/22/github.com/kubernetes-sigs/cluster-api-provider-openstack/master/cluster-api-provider-openstack-image-build/fbc5149/job-output.json.gz
* error log piece:
<pre>
"stdout_lines": [
                                    "Error: Cannot perform an interactive login from a non TTY device",
                                    "/bin/bash: line 1: -p: command not found",
                                    "+ set -e",
                                    "+ set -o pipefail",
                                    "+ '[' periodic-10/22 '!=' periodic ']'",
                                    "+ exit 0"
                                ],
</pre>

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by wangxiyuan** [comment]
Thanks for your bug report. I just had a fix a few hours ago. : https://github.com/theopenlab/openlab-zuul-jobs/pull/559

**Comment by hidekazuna** [comment]
Still failing, but message has changed.

* job name
cluster-api-provider-openstack-image-build
* job build log link:
https://logs.openlabtesting.org/logs/periodic-10/22/github.com/kubernetes-sigs/cluster-api-provider-openstack/master/cluster-api-provider-openstack-image-build/b66534a/job-output.json.gz
* error log piece:
<pre>
"Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password",
</pre>

**Comment by wangxiyuan** [comment]
yeah, I saw it. I'll fix it quickly

**Comment by wangxiyuan** [comment]
I updated the user/password in theopenlab/openlab-zuul-jobs#559. But I forgot restarting zuul service to adopt this change.  lol
