### ISSUE TITLE
Support running periodic job of Hive based on ARM64 server

### ISSUE THREAD

**Issue by liusheng** [theopenlab/openlab#303]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [x] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
yes, Apache Hive

### Brief project description
The Apache Hive (TM) data warehouse software facilitates reading, writing, and managing large datasets residing in distributed storage using SQL.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
yes, https://github.com/apache/hive

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VM with ARM64 Arch

### What OS are you planning to use?
Ubuntu xenial

### Any special network configuration you expect or anticipate implementing?
No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
ARM64

### What testing are you planning to implement or need assistance implementing?
Add periodic job to run building process of Hive project on ARM64 server

### How will this testing advance application and/or tooling built on-top of open infrastructure?
Enrich the application echosystem

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

**Comment by kiwik** [comment]
Hive ARM64 periodic job have been executed in OpenLab side for a time, see log [here](http://status.openlabtesting.org/builds?project=apache/hive), it failed because hive depends on `protoc 2.5.0` but no `ARM64` enabled protoc 2.5.0. It make sense to find out `ARM64` related issue in Hive, and we can resolve it to enable more and more projects on ARM host.  we have commit a PR https://github.com/apache/hive/pull/694 in Hive side, and append issue details at here.

```
2019-06-26 08:59:22.426070 | ubuntu-xenial-arm64 | [ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.5.1.1:run (default) on project hive-standalone-metastore-common: Error resolving artifact: com.google.protobuf:protoc:2.5.0: Could not find artifact com.google.protobuf:protoc:exe:linux-aarch_64:2.5.0 in central (https://repo.maven.apache.org/maven2)
```
