### ISSUE TITLE
New "install-docker" role cannot work

### ISSUE THREAD

**Issue by liusheng** [theopenlab/openlab#309]
Thank you for reporting bug!

### Describe the bug
The new imported role `install-docker` has broken the jobs using this role.

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
- docker-machine-v0.16.1-functional-devstack-mitaka
- docker-machine-v0.16.1-functional-devstack-newton
- docker-machine-v0.16.1-functional-devstack-ocata
- docker-machine-v0.16.1-functional-devstack-pike
- docker-machine-v0.16.1-functional-devstack-queens
- docker-machine-v0.16.1-functional-devstack-rocky
- docker-machine-v0.16.1-functional-devstack-stein

* job build log link:
https://logs.openlabtesting.org/logs/periodic-8/20/github.com/docker/machine/master/docker-machine-v0.16.1-functional-devstack-stein/0fd34ea/job-output.txt.gz

https://logs.openlabtesting.org/logs/periodic-8/20/github.com/docker/machine/master/docker-machine-v0.16.1-functional-devstack-mitaka/8330525/job-output.txt.gz
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by liu-sheng** [comment]
hmm, not sure this is the real cause, debuging

**Comment by kiwik** [comment]
docker-machine testing passed now, closed

http://status.openlabtesting.org/builds?project=docker/machine
