### ISSUE TITLE
Diwakar Dogra

### ISSUE THREAD

**Issue by dogradiwakar** [theopenlab/openlab#312]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

**Comment by liu-sheng** [comment]
welcom!

**Comment by kiwik** [comment]
Welcome, @Diwakar, let me to invite you into team, this is  quick start for OpenLab, https://docs.openlabtesting.org

**Comment by kiwik** [comment]
It still a pending invitation, @dogradiwakar please join team when see that message.

**Comment by wangxiyuan** [comment]
No response for long time.
