### ISSUE TITLE
Add CI to Hadoop trunk on ARM64

### ISSUE THREAD

**Issue by ZhengZhenyu** [theopenlab/openlab#313]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [x] Other

### If this is for an open source project what is it?
yes

### Brief project description
The Apache Hadoop software library is a framework that allows for the distributed processing of large data sets across clusters of computers using simple programming models. 

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
yes, https://github.com/apache/hadoop

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
1 VM

### What OS are you planning to use?
Ubuntu

### Any special network configuration you expect or anticipate implementing?
No

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
AArch64

### What testing are you planning to implement or need assistance implementing?
Build & Functional test

### How will this testing advance application and/or tooling built on-top of open infrastructure?
Try to make Hadoop usable on Aarch64

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

**Comment by kiwik** [comment]
LGTM, thank you to help building ARM software ecosystem.
