### ISSUE TITLE
Add CI for apache/spark on aarch64 

### ISSUE THREAD

**Issue by huangtianhua** [theopenlab/openlab#316]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
yes
apache/spark
### Brief project description
Spark is a unified analytics engine for large-scale data processing. It provides high-level APIs in Scala, Java, Python, and R, and an optimized engine that supports general computation graphs for data analysis. It also supports a rich set of higher-level tools including Spark SQL for SQL and DataFrames, MLlib for machine learning, GraphX for graph processing, and Structured Streaming for stream processing.
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
yes
https://github.com/apache/spark
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
1 VM 
### What OS are you planning to use?
Ubuntu
### Any special network configuration you expect or anticipate implementing?
NA
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
aarch64
### What testing are you planning to implement or need assistance implementing?
Build and test of apache/spark
### How will this testing advance application and/or tooling built on-top of open infrastructure?
Make sure apark works on aarch64 platform
### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
NA

**Comment by kiwik** [comment]
LGTM

**Comment by huangtianhua** [comment]
Issue list:
https://issues.apache.org/jira/browse/SPARK-28433
https://issues.apache.org/jira/browse/SPARK-28770  
https://issues.apache.org/jira/browse/SPARK-29286
https://issues.apache.org/jira/browse/SPARK-27721
https://issues.apache.org/jira/browse/SPARK-30057
https://issues.apache.org/jira/browse/SPARK-28519
