### ISSUE TITLE
Job cloud-provider-openstack-acceptance-test-e2e-conformance is broken on master and v1.15

### ISSUE THREAD

**Issue by wangxiyuan** [theopenlab/openlab#317]
Thank you for reporting bug!

### Describe the bug
Job cloud-provider-openstack-acceptance-test-e2e-conformance is broken on master and v1.15
### Related Job information
If the bug is related a CI job, put the job information below:
* job name:cloud-provider-openstack-acceptance-test-e2e-conformance
                 cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.15
* job build log link: 
https://logs.openlabtesting.org/logs/39/639/c4491e0e90d9888007b5c33b8ebb5823a05a98a1/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.15/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.15/c34346f/
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:
cloud-provider-openstack pr CI check

**Comment by kiwik** [comment]
Resovled http://status.openlabtesting.org/builds/builds?job_name=cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.15, close the issue.
