### ISSUE TITLE
https certificate is out of date again

### ISSUE THREAD

**Issue by wangxiyuan** [theopenlab/openlab#319]
Thank you for reporting bug!

### Describe the bug
https certificate is out of date again. We are using Let's Encrypt CA which is free for 90 days. So that we should add a script to resign the certificate every 3 month.

**Comment by wangxiyuan** [comment]
I'll resign the certificate and then add a script in labkeeper. So that it can be done easily next time.

**Comment by wangxiyuan** [comment]
Production env is fixed now.

**Comment by kiwik** [comment]
Yes, https://openlabtesting.org/ is OK now, thank you very much, and I have update commit message of document updating PR theopenlab/labkeeper#172 , the issue will been closed when that PR is merged.

```
Close: theopenlab/openlab#319
```
