### ISSUE TITLE
OpenStack Keymanager V1 environment for terraform-provider-openstack

### ISSUE THREAD

**Issue by ozerovandrei** [theopenlab/openlab#324]
Hello.

Could you please add the OpenStack Keymanager (Barbican) service and the new environment variable `OS_KEYMANAGER_ENVIRONMENT=true` for the [terraform-provider-openstack](https://github.com/terraform-providers/terraform-provider-openstack) acceptance tests.

Reference: [terraform-provider-openstack#807](https://github.com/terraform-providers/terraform-provider-openstack/pull/807)

**Comment by kayrus** [comment]
@wangxiyuan have you added barbican service?

**Comment by wangxiyuan** [comment]
@kayrus if you want to use barbican in self-setup devstack. just add it in your job file.

If you want to use barbican in real cloud. Sorry, there is no public cloud provider in openlab support this service IMO.
