### ISSUE TITLE
RocksDB - ARM64 for building and CI

### ISSUE THREAD

**Issue by adamretter** [theopenlab/openlab#329]
### What is your focus?
- [x] Other
-- Portability

### If this is for an open source project what is it?
Yes, RocksDB - https://github.com/facebook/rocksdb

### Brief project description
High performance LSM key-value store which is optimised for SSD.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://github.com/facebook/rocksdb

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
I am looking for an aarch64 machine, for both compiling releases of the software and also for running a CI, so that we can ensure there are no regressions with compiling on aarch64.

### What OS are you planning to use?
I am not sure what the options on aarch64 are. Preferably, CentOS, otherwise Ubuntu. The older the better fro glibc version compatibility.

### Any special network configuration you expect or anticipate implementing?
N/A

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
Just ARM 64.

### What testing are you planning to implement or need assistance implementing?
That the software compiles.

### How will this testing advance application and/or tooling built on-top of open infrastructure?
We will publish ARM64 builds of RocksDB alongside our existing x86, x86_64, and ppc64le builds.

### Will you publish blog or paper from your testing?
- [x] No - if no, how will you present your results?
-- Directly to our open source users

### Any other relevant details we should know about while preparing the infrastructure?
N/A

**Comment by kiwik** [comment]
LGTM
Thank you doing these in RocksDB for ARM64.
@Yikun please send one ARM64 VM to @adamretter .

**Comment by Yikun** [comment]
@adamretter Cool, thanks for your effort for the RocksDB aarch64 support.

I have sent the VM info to you (adam.retter at googlemail.com). And if you have any question, you could feel free to contact me.
