### ISSUE TITLE
ARM and ARM64 for building, testing and deployment

### ISSUE THREAD

**Issue by click2cloud-apurva** [theopenlab/openlab#331]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [x]  Other

### If this is for an open source project what is it?
Prometheus
### Brief project description
Prometheus, a Cloud Native Computing Foundation project, is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts if some condition is observed to be true.
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, the Prometheus code is 100% open source at https://github.com/prometheus/prometheus
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
ARM and ARM64 Baremetal. I am looking for an aarch64 machine
### What OS are you planning to use?
Centos
### Any special network configuration you expect or anticipate implementing?
All machines need to public IP addresses or a way to ssh
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
Just ARM and  ARM 64.
### What testing are you planning to implement or need assistance implementing?
NA
### How will this testing advance application and/or tooling built on-top of open infrastructure?
NA
### Will you publish blog or paper from your testing?

- [ ] Yes
- [x] No - if no, how will you present your results?
-- Directly to our open source users

### Any other relevant details we should know about while preparing the infrastructure?
NA

**Comment by kiwik** [comment]
Hi @c2c-engg-20170100 , Prometheus ARM testing have been integrated into https://cncf.ci (a CNCF official testing platform), and OpenLab have helped to do it. So that, if you have some testing suggestion, please contribute in Prometheus or cncf.ci project directly.

![image](https://user-images.githubusercontent.com/1562985/62508120-1830aa80-b839-11e9-955b-2b7873928b07.png)
