### ISSUE TITLE
Support of ARM machine for building 

### ISSUE THREAD

**Issue by d-apurva** [theopenlab/openlab#333]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [x] Other

### If this is for an open source project what is it?
Yes
### Brief project description
NA
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
ARM machine
### What OS are you planning to use?
Centos
### Any special network configuration you expect or anticipate implementing?
NA
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
ARM architecture
### Will you publish blog or paper from your testing?

- [ ] Yes
- [ ] No - if no, how will you present your results?

**Comment by wangxiyuan** [comment]
Sorry, you didn't provide which opensoure project you will use ARM for. Close it now. Feel free to re-open if needed.
