### ISSUE TITLE
Add Linaro resources to OpenLab

### ISSUE THREAD

**Issue by Yikun** [theopenlab/openlab#338]
We got the [Linaro Developer Cloud](https://linaro.cloud/) resource in 19.Aug.2019.

Thanks for the help of @kevin-zhaoshuai

Now it's ready (the flavor/sg/network is ready) to add the linaro resource to the OpenLab nodepool

See check result:
```
# openlab check --cloud linaro
1/1. linaro cloud check
================================================
[nodepool] auth------------------------- PASSED
[nodepool] securitygroup---------------- PASSED
[nodepool] network---------------------- PASSED
[nodepool] flavor----------------------- PASSED
Info:
- Flavor 4U8G: ['openjdk.extra.large (128G)', 'm1.large.4C8G (40G)']
- Flavor 8U8G: not found
- Flavor 1U2G: ['rpmfusion.small (25G)']
- Flavor 2U2G: not found
[nodepool] quota------------------------ PASSED
Info:
cores: 128
floating-ips: 10
networks: 100
ram: 132000
subnets: 100
volumes: 10
[nodepool] orphan_resource-------------- PASSED
```

Let's make it happen!

**Comment by kevin-zhaoshuai** [comment]
My pleasure to help deliver the resources to OpenLab. Look forwards to have good corporation with OpenLab on Arm64 servers.

**Comment by kevin-zhaoshuai** [comment]
do you need the - Flavor 4U8G, 8U8G, 1U2G, 2U2G and 16C16G? If yes, I will create the flavors special for OpenLab

**Comment by Yikun** [comment]
@kevin-zhaoshuai Thanks for the help, now we are only using the openlab.medium(16U 16G 80GB) flavor! and other flavor is not necessary. If we have more req of flavor, I will contact you. :)

And now the linaro vm have been used in the OpenLab! Thanks the donation of linaro dev cloud!

**Comment by wangxiyuan** [comment]
Linaro works well now.
