### ISSUE TITLE
hidekazuna join in OpenLab

### ISSUE THREAD

**Issue by hidekazuna** [theopenlab/openlab#339]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name

Hidekazu Nakamura

### Github account id

hidekazuna

### Email

hidekazuna@gmail.com

### Company/Organization

NEC

### IRC nickname (Optional)

hidekazu

### Any additional questions, concerns, or comments?

Currently I am working on #141

**Comment by liusheng** [comment]
welcome @hidekazuna :)

**Comment by hidekazuna** [comment]
@liusheng No action is happening...  What can I do for being Member other than creating this PR?

**Comment by liusheng** [comment]
@hidekazuna Sorry, I have invited you to the team, this is quick start for OpenLab, https://docs.openlabtesting.org

Invite message have been sent, please take a look your github notifications

**Comment by hidekazuna** [comment]
@liusheng Thanks inviting. I joined OpenLab.
