### ISSUE TITLE
Add Multinode CI job for intree cinder driver to CSI driver migration

### ISSUE THREAD

**Issue by adisky** [theopenlab/openlab#342]
### What is your focus?
- [x] Performance
- [ ] Scale
- [x] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
cloud-provider-openstack

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/kubernetes/cloud-provider-openstack

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VM's 3

### What OS are you planning to use?
ubuntu-xenial

### What testing are you planning to implement or need assistance implementing?
All intree volume driver would be eventually removed from Kubernetes, due to strict API policy of kubernetes,intree volume API's cannot be removed, to solve this, all api calls to intree volume API is migrated to corresponding Cinder Driver, to promote  cinder migration to `beta`, we need to setup a consistent running CI jobs, with migration flags enabled
https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190129-csi-migration.md

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

**Comment by hogepodge** [comment]
This is a very important need to fill for the openstack/k8s community, and will have immediate positive impact in both open source communities.

/lgtm

**Comment by wangxiyuan** [comment]
@adisky , the multi node env is ready. What should we do next? Is there anything I can help then?

**Comment by adisky** [comment]
@wangxiyuan basically we need to boostrap a multinode k8s cluster(one master, two/three worker) with CSI Migration flags enabled, deploy CSI driver on that cluster and run all storage e2e tests

**Comment by adisky** [comment]
@wangxiyuan we can work with the existing kubeadm multinode role, just need to setup `/etc/kubernetes/cloud-config `and `kubeadm.conf` (to setup feature gates and provider openstack)
