### ISSUE TITLE
Enable MOO Project

### ISSUE THREAD

**Issue by lyd911** [theopenlab/openlab#354]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [x] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
MOO project
### Brief project description
A web service that can recreate ML workflow
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://moo-ai.github.io/index.html 
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VM, 1
### What OS are you planning to use?
ubuntu16.04
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
CPU, GPU
### What testing are you planning to implement or need assistance implementing?
ML Training and Inferencing workflow
### Will you publish blog or paper from your testing?

- [x] Yes
live demo at the HC 2019 session
- [ ] No - if no, how will you present your results?

**Comment by wangxiyuan** [comment]
fixed by https://github.com/moo-ai/moo-ai.github.io/commit/ae0f9cb04cb3d0983cb1665278975a94e21ebc2d
