### ISSUE TITLE
Gophercloud Acceptance Tests are failing

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#360]
### Describe the bug

It appears the `gophercloud-acceptance-test` test job is consistently failing under multiple pull requests.

### Related Job information

If the bug is related a CI job, put the job information below:

* job name: `gophercloud-acceptance-test `
* job build log link: https://logs.openlabtesting.org/logs/01/1701/40e5e8a782e00af6af862bd80634972d565742d3/check/gophercloud-acceptance-test/19c0380/
* error log piece: Not sure

### Steps to reproduce the issue

Describe how to reproduce the issue:

Just run `recheck` under any Gophercloud PR.

Please let me know if I can provide any other information.

**Comment by jtopjian** [comment]
The behavior of this has changed a little.

OpenLab runs are now getting to the point of running tests, but we're seeing consistent failures in some tests due to `OS_SUBNET_ID` not being available as an environment variable. See the comment here: 

https://github.com/gophercloud/gophercloud/pull/1712#issuecomment-532884488
https://github.com/gophercloud/gophercloud/pull/1712#issuecomment-532885550

If I search the OpenLab playbooks, I only see `OS_SUBNET_ID` only being set on two specific cloud providers: https://github.com/theopenlab/openlab-zuul-jobs/search?q=OS_SUBNET_ID&unscoped_q=OS_SUBNET_ID

Was this unset for Gophercloud-based jobs?

**Comment by kiwik** [comment]
@huangtianhua please check this issue

**Comment by huangtianhua** [comment]
@jtopjian Sorry to reply late. 
First, gophercloud specify NeutronNetID and NeutronSubnetID from env settings: https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/sharedfilesystems/v2/sharenetworks.go#L29-L30  
https://github.com/gophercloud/gophercloud/blob/master/acceptance/clients/clients.go#L67-L68

The envs is not set in OpenLab site, they are set in https://github.com/gophercloud/gophercloud/blob/master/script/stackenv#L17-L18
about the subnet id we get by show api with name 'private_subnet':
https://github.com/gophercloud/gophercloud/blob/master/script/stackenv#L10

But devstack installing a default subnet named 'private-subnet' was created, not 'private_subnet', see:
https://github.com/openstack/devstack/blob/master/lib/neutron_plugins/services/l3#L278
https://github.com/openstack/devstack/blob/master/lib/neutron_plugins/services/l3#L89

And seems it was ok to create share network without subnet id(only with network id), but after the below commit merged it will be fail, and it was merged 10 days ago: https://github.com/openstack/manila/commit/14d3e268a05265db53b5cfd19d9a85a3ba73a271#diff-abf880ab1e61f81d16e3c8fc3c0e80ed

**Comment by jtopjian** [comment]
@huangtianhua Thank you so much for looking into this.

> about the subnet id we get by show api with name 'private_subnet':
> https://github.com/gophercloud/gophercloud/blob/master/script/stackenv#L10

I'm not sure how I missed this - I'm sorry.

> But when devstack installing a default subnet named 'private-subnet' was created, not 'private_subnet', see:

I'll get this fixed.

Thank you again!

**Comment by jtopjian** [comment]
This has been resolved. @huangtianhua Thank you for helping with this - I really appreciate it.
