### ISSUE TITLE
Add rust-osauth and rust-osproto to rust-openstack

### ISSUE THREAD

**Issue by dtantsur** [theopenlab/openlab#367]
Hi folks,

thank you for helping testing rust-openstack all this time. The project has been split into three repositories. In addition to the main rust-openstack there are now rust-osauth (think keystoneauth) and rust-osproto (just a collection of structures generated from API docs). Could you please enable testing for them or point me at how to enable it?

Many thanks

**Comment by wangxiyuan** [comment]
Do these project need openlab any more?

**Comment by dtantsur** [comment]
@wangxiyuan hi, yes, this request is still valid.

**Comment by wangxiyuan** [comment]
Done, you can install the openlab githubapp to these projects and then add .zuul.yaml to define the job now.

**Comment by dtantsur** [comment]
Hi @wangxiyuan! I have finally got to finishing my side of this work item, but it doesn't look like the jobs are triggered: https://github.com/dtantsur/rust-osauth/pull/13. Am I doing something wrong?

**Comment by wangxiyuan** [comment]
@dtantsur comment in the PR

**Comment by wangxiyuan** [comment]
Done
