### ISSUE TITLE
Apache ServiceComb - ARM64 for building and CI

### ISSUE THREAD

**Issue by surechen** [theopenlab/openlab#371]
### What is your focus?
- [x] Other
for Portability

### If this is for an open source project what is it?
Yes, Apache ServiceComb--http://servicecomb.apache.org/

### Brief project description
Open-Source, Full-Stack Microservice Solution.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes. http://servicecomb.apache.org/

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
1 VM for both compiling  and  running a CI

### What OS are you planning to use?
centos or ubuntu

### Any special network configuration you expect or anticipate implementing?
N/A

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
ARM 64

### What testing are you planning to implement or need assistance implementing?
the software compiles   and  running a CI

### How will this testing advance application and/or tooling built on-top of open infrastructure?
Make sure ServiceComb works on aarch64 platform

### Will you publish blog or paper from your testing?
- [x] Yes
- [ ] No - if no, how will you present your results?
### Any other relevant details we should know about while preparing the infrastructure?
N/A

**Comment by wangxiyuan** [comment]
welcome, please follow openlab docs to integrate openlab CI. https://docs.openlabtesting.org/contributors/connect-to-openlab

Let us know if you have any problem.

**Comment by surechen** [comment]
> welcome, please follow openlab docs to integrate openlab CI. https://docs.openlabtesting.org/contributors/connect-to-openlab
> 
> Let us know if you have any problem.

Thanks. I has a repository surechen/servicecomb-service-center which is forked from apache/servicecomb-service-center. I have added .zuul.yaml and installed TheOpenLab CI plugin.

**Comment by wangxiyuan** [comment]
We have to add `servicecomb-service-center` to the CI system once your request is approved. Please wait. Thanks. @kiwik

**Comment by kiwik** [comment]
LGTM, approved.

**Comment by wangxiyuan** [comment]
@surechen  I have added apache/servicecomb-service-center to openlab CI system now. Please either adding a .zuul.yaml file in the repo or contriubing to openlab/openlab-zuul-job repo directly within a PR. Both way works. I suggest the .zuul.yaml way, becuase in this way, you can test the CI job direclty in the PR.

**Comment by surechen** [comment]
> @surechen I have added apache/servicecomb-service-center to openlab CI system now. Please either adding a .zuul.yaml file in the repo or contriubing to openlab/openlab-zuul-job repo directly within a PR. Both way works. I suggest the .zuul.yaml way, becuase in this way, you can test the CI job direclty in the PR.

Hello,thanks. Because I'm not the owner of the project apache/servicecomb-service-center. It`s hard for me to test. Can you help me add my fork surechen/servicecomb-service-center, but not apache/servicecomb-service-center. When I finished test work  I will try to merge to apache/servicecomb-service-center.

**Comment by wangxiyuan** [comment]
close now, enjoy your openlab journey
