### ISSUE TITLE
Question about config-golang/tasks/main.yml 

### ISSUE THREAD

**Issue by surechen** [theopenlab/openlab#372]
Thank you for reporting bug!

### Describe the bug
I try playbooks/golang-test/post.yaml in my computer by cmd:
ansible-playbook ./playbooks/golang-test/post.yaml
I get result :
TASK [config-golang : Merge golang env vars into global env] 
fatal: [192.168.88.64]: FAILED! => {"msg": "|combine expects dictionaries, got AnsibleUndefined"}
Could you tell me how to solve this problem?

The content golang_env  in config-golang/tasks/main.yml 
```bash
- name: Set golang env vars
  set_fact:
    golang_env:
      GOPATH: '{{ ansible_user_dir }}'
      PATH: '/usr/local/go/bin:{{ ansible_user_dir }}/bin:{{ ansible_env.PATH }}'
      TEST_RESULTS_TXT: '{{ ansible_user_dir }}/workspace/test_results.txt'
      TEST_RESULTS_XML: '{{ ansible_user_dir }}/workspace/test_results.xml'
      TEST_RESULTS_HTML: '{{ ansible_user_dir }}/workspace/test_results.html'
```

```bash
- name: Merge golang env vars into global env
  set_fact:
    global_env: '{{ global_env | combine(golang_env) }}'
```

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:
N/A
### Steps to reproduce the issue
Describe how to reproduce the issue:
I try playbooks/golang-test/post.yaml in my computer by cmd:
ansible-playbook ./playbooks/golang-test/post.yaml

### Additional context
N/A

**Comment by wangxiyuan** [comment]
global_env is a variable that defined and used by zuul jobs. So if you use this role directly with ansible, it'll raise error. See: https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L35

You can fake a {{ global_env  }} in your local test first.
