### ISSUE TITLE
Join Request: sbueringer

### ISSUE THREAD

**Issue by sbueringer** [theopenlab/openlab#380]
Welcome to OpenLab!

### Full Name
Stefan Büringer

### Github account id
sbueringer

### Email
sbueringer@gmail.com

### Company/Organization
Daimler TSS GmbH

### Any additional questions, concerns, or comments?
Just fyi, I'd like to take up the work on the ClusterAPI OpenStack testing > https://github.com/theopenlab/openlab/issues/141

**Comment by wangxiyuan** [comment]
Welcome. You can create a test issue and then add PR to `openlab-zuul-job` to add the new job

**Comment by jichenjc** [comment]
@sbueringer thanks for sharing on this ,this is great

**Comment by sbueringer** [comment]
Anything else to do for this membersip request?

**Comment by liusheng** [comment]
Hi @sbueringer,
Welcome! Ihave invited you :)

**Comment by sbueringer** [comment]
Thx :)
