### ISSUE TITLE
Gophercloud: Neutron / Octavia Build Failure

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#382]
Thank you for reporting bug!

### Describe the bug

The gophercloud-acceptance-test job is failing. I think this is due to:

```
2019-10-25 18:17:13.477 | ++ /opt/stack/new/octavia/devstack/plugin.sh:source:701 :   
    die 'The neutron-api/q-svc service must be enabled to use octavia'
```

### Related Job information

If the bug is related a CI job, put the job information below:

* job name: `gophercloud-acceptance-test`
* job build log link: https://logs.openlabtesting.org/logs/58/1758/a1f07f4341d272be1d15f9c1782f5f8df1804154/check/gophercloud-acceptance-test/1359192/
* error log piece:

```
2019-10-25 18:17:13.477 | ++ /opt/stack/new/octavia/devstack/plugin.sh:source:701 :   
    die 'The neutron-api/q-svc service must be enabled to use octavia'
```

### Steps to reproduce the issue

re-run `gophercloud-acceptance-test`

### Additional context

This issue seems to have started 4-5 days ago.

I've tried to resolve this issue at https://github.com/gophercloud/gophercloud/pull/1762 but haven't been able to figure out how to fix it.

**Comment by huangtianhua** [comment]
@jtopjian, sorry, there is bug in a merged commit, I will fix this.

**Comment by jtopjian** [comment]
Looks like everything is working. Thank you so much!
