### ISSUE TITLE
Remove cluster-api-provider-openstack-image-build Job

### ISSUE THREAD

**Issue by sbueringer** [theopenlab/openlab#385]
Sorry none of the existing Issue templates really fit so I used bug :).

I saw that there's a Job called `cluster-api-provider-openstack-image-build`. ClusterAPI provider openstack nowdays builds & releases images via Kubernetes Prow. So in my opinion the `cluster-api-provider-openstack-image-build` job can be removed, because it isn't required anymore. 

@jichenjc @hidekazuna @chrigl @hogepodge  What do you think?

**Comment by wangxiyuan** [comment]
Thanks for the bug report. Any guys from kubernetes-sigs can double check it? If so, i can remove it then.

**Comment by jichenjc** [comment]
I don't know the history, but seems we should remove that image as we are using prow now

**Comment by chrigl** [comment]
@wangxiyuan yes, this is correct. Thanks :)

**Comment by sbueringer** [comment]
> I don't know the history, but seems we should remove that image as we are using prow now

I also don't know how it was created. I just always wondered were the docker hub image came from :). 

But because we're now using Prow like all other ClusterAPI Providers it can definitely be removed :)
