### ISSUE TITLE
Gophercloud: Add job for Magnum / ContainerInfra

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#396]
### Describe the solution you'd like

I'd like to have a Gophercloud test job created for Magnum / ContainerInfra

### Additional context

We currently don't have Magnum / ContainerInfra tested in OpenLab and it'd be a nice feature if we could. If running Magnum in parallel to the other services we test (Manila, Octavia, etc), then having it as a separate job would be fine.

**Comment by wangxiyuan** [comment]
sure, feel free to add the job in openlab-zuul-job

**Comment by jtopjian** [comment]
I can handle the additions to Gophercloud directly (eg amending https://github.com/gophercloud/gophercloud/pull/1778), but it's best if someone from OpenLab handles the addition here (https://github.com/theopenlab/openlab-zuul-jobs/blob/master/roles/create-devstack-local-conf/tasks/main.yml) since you folks know best how to configure devstack appropriately on your infrastructure.
