### ISSUE TITLE
Customization of OpenStack services in zuul jobs

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#41]
Melvin: Can we get a bit more detail here?
RuiChen: Now we use split pipeline to support "recheck stable/pike" and "recheck designate", that cause so many pipeline should be defined for testing on different versions and different services (M * N pipelines), we hope zuul can support "recheck {version} {service}" in comments, and zuul can trigger different jobs in one pipeline define.

**Comment by kiwik** [comment]
I think current OpenLab zuul pipeline setting can fulfill our needs, so close it.
