### ISSUE TITLE
Gophercloud: Acceptance tests are failing

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#412]
### Describe the bug

Acceptance tests are not running.

### Related Job information

* job name: gophercloud-acceptance-test
* job build log link: https://logs.openlabtesting.org/logs/94/1794/1ea0ade76ad0f4fe8a1a4d7091bed93fb802d455/check/gophercloud-acceptance-test/29d756b/
* error log piece: not sure

### Steps to reproduce the issue

Describe how to reproduce the issue:

run "recheck"

### Additional context

This began a few days ago. Please let me know if you need any other information. Thank you!

**Comment by huangtianhua** [comment]
https://github.com/openstack/devstack/commit/893126cd64594b45e61839f71d59b2701ef689c9#diff-4f76c30de6fd72bd49643dbcf1007a61R224
Seems devstack dropped xenial support.

**Comment by wangxiyuan** [comment]
@jtopjian . Thanks for the bug report. We're now setting up new ubuntu18.04 env according to @huangtianhua 's investigation. I'll let you know once it's done.

**Comment by jtopjian** [comment]
Thank you both for your help :)

**Comment by dtantsur** [comment]
rust-openstack is also affected. @wangxiyuan please also let me know when a bionic environment is available.

**Comment by wangxiyuan** [comment]
@ubuntu-bionic works for rust-openstack now. See the recheck result here: https://github.com/dtantsur/rust-openstack/pull/105#issuecomment-570112847  the failure relates to the PR itself, not openlab.

**Comment by dtantsur** [comment]
@wangxiyuan wonderful, thanks!

**Comment by jtopjian** [comment]
Sorry for the late follow-up with this. Gophercloud tests are also now running on bionic. We've got a new test failure and I'm not sure if it's coincidence or something triggered from devstack within bionic, but I'll sort that out and open a new issue here if needed.

As usual, thank you all for your help with this.
