### ISSUE TITLE
Terraform-provider-openstack: lbaas tests are failing

### ISSUE THREAD

**Issue by ozerovandrei** [theopenlab/openlab#419]
### Describe the bug
Load balancer acceptance tests are not running.

### Related Job information
* job name: terraform-provider-openstack-acceptance-test-lbaas
* job build log link: https://logs.openlabtesting.org/logs/45/945/8e472509b54160ac50d2e6fb56e24a21eef81064/recheck-lbaas/terraform-provider-openstack-acceptance-test-lbaas/178ccfc/
* error log piece: 2019-12-14 22:12:07.828973 | ubuntu-xenial | ERROR: the main setup script run by this job failed - exit code: 2

### Steps to reproduce the issue
Describe how to reproduce the issue:

Run `recheck lbaas` in any PR.

### Additional context
I see that other jobs were migrated to `ubuntu-bionic` but lbaas check is still on xenial.

**Comment by wangxiyuan** [comment]
I guess it's fixed now. Feel free to reopen if the error is  still there.

**Comment by ozerovandrei** [comment]
@wangxiyuan thank you!
