### ISSUE TITLE
[Citynetwork node] Master zuul node can not be launched anymore

### ISSUE THREAD

**Issue by bzhaoopenstack** [theopenlab/openlab#446]
The master zuul node on citynetwork can not launch.

For saving the original data, the first step is asking for citynetwork guys to help to launch.
If have no way to rescue it, I will create a new citynetwork node.

@tobberydberg Could you please help to figure out what's going on the zuul node(citynetwork-openlab-zuul)? Thanks

**Comment by bzhaoopenstack** [comment]
@tobberydberg just send you a email by bzhaojyathousandy@gmail.com .Hope could get your concern.

**Comment by bzhaoopenstack** [comment]
@tobberydberg I setup the node via potal. Thanks.

**Comment by tobberydberg** [comment]
Ok. So, issue solved now? If not, please provide me with the UUID of the instance and the region it's located in.

**Comment by bzhaoopenstack** [comment]
@tobberydberg yeah, the issue node is setup(but the data volume can not be mounted), and the arm VM hang with deleting now. Our resources are in London / UK ... Seems that region is in trouble?

**Comment by bzhaoopenstack** [comment]
@tobberydberg Hi, our data volume d65255c0-2cdf-471b-8e8e-43a86de3a9a2 can not be found on instance ace1046c-7381-429a-9377-c72e5a542bdb . Could you please have a look? Thanks

**Comment by tobberydberg** [comment]
Haven't heard of issues in that region....

Can't find that volume, not in the database either ... sure that is the ID @bzhaoopenstack ?

**Comment by tobberydberg** [comment]
Did a miss in my copy/paste... I can see that volume d65255c0-2cdf-471b-8e8e-43a86de3a9a2 is attached to that VM on device /dev/vdb

That is what the information is telling me. So, if you look for /dev/vdb on your server you don't have that? Like just an ls -l /dev/vdb ??

**Comment by bzhaoopenstack** [comment]
@tobberydberg Thanks, I retry it. I can access /dev/vdb now, also fdisk -l. As the volume stored so many data which is useful for us, after the last reboot the VM, I tried to mount it, but failed, and I can not use 'fdisk -l' to see it. Now I'm trying to mount it again.

**Comment by bzhaoopenstack** [comment]
@tobberydberg I success to mount it..Thanks. I restore the data from that volume..
But it's true that VM hange in 'BUILD' status for a day and the backend storage service seems don't work well. Now I will recover the whole openlab env. Thanks for your kind help. If any issue is hit again, I will tell you then.

**Comment by bzhaoopenstack** [comment]
I will close this issue for now. Thanks @tobberydberg
