### ISSUE TITLE
Help wanted on failing CI job for terraform-provider-openstack

### ISSUE THREAD

**Issue by freddebacker** [theopenlab/openlab#492]
I introduced a new feature and corresponding test for terraform-provider-openstack. The new feature allow to use the web-download import method for the Openstack Image API. In the new CI test running in OpenLab, I'm attempting to use the web-download import-method to fetch an image that is commonly used in the other terraform-provider-openstack CI tests (https://releases.rancher.com/os/latest/rancheros-openstack.img). The CI test times-out; I'm suspecting because the host/container/... responsible for fetching the image has no direct internet access.

- Can someone confirm that this is indeed what is happening?
- Any hints on what I can try to overcome the situation?

Example of failing CI test:
https://logs.openlabtesting.org/logs/88/888/5860b5a5cf2a9479fec9c55fc803dcf5469925d2/check/terraform-provider-openstack-acceptance-test/e9e43a3/job-output.txt.gz (look for test TestAccImagesImageV2_webdownload)

The related issue and pull request:
https://github.com/terraform-providers/terraform-provider-openstack/issues/887
https://github.com/terraform-providers/terraform-provider-openstack/pull/888

**Comment by wangxiyuan** [comment]
the node have web access. For exmaple, when install devstack, the node fecth packages from internet.

I have a question: the `TestAccImagesImageV2_webdownload` test rans at 2020-03-12 14:25. But there is no related log in glance-api.log https://logs.openlabtesting.org/logs/88/888/5860b5a5cf2a9479fec9c55fc803dcf5469925d2/check/terraform-provider-openstack-acceptance-test/e9e43a3/logs/screen-g-api.txt

Can you tell me how the test use openstack env?

**Comment by freddebacker** [comment]
Hi,

Not sure I understood your question correctly. The terraform-provider-openstack CI uses the OpenLab Openstack environment to test the various functions of the Terraform provider, i.e. if they can correctly manipulate (CRUD) various Openstack objects.

This particular test should verify that the provider can create a new image in Openstack using the `web-download` import method.

If you compare the test with `TestAccImagesImageV2_basic`, which runs in the same test-run but a bit earlier, the end-goal is the same; i.e. prove that the provider can create the image in Openstack from a given URL (https://releases.rancher.com/os/latest/rancheros-openstack.img).

The difference between them is in the way the image data is acquired:
- The (working) `TestAccImagesImageV2_basic` test has the node running the Terraform script downloading the data from the given URL to a local temporary location, then calls Openstack API's to create (**POST** `/v2/images`) the image (metadata) and finally upload (**PUT** `/v2/images/{image_id}/file`) the image (binary data) from the local copy.
- The (not working) `TestAccImagesImageV2_webdownload` test has the node running the Terraform script just calling Openstack API's to create (**POST** `/v2/images`) the image (metadata), but then asking Openstack to directly download (**POST** `/v2/images/{image_id}/import`, with method `web-download`) the image (binary data) from the given URL. This last API call seems not to work, causing the test to eventually time-out. I could not find any logs related to this API call.

Neither of these 2 tests show any trace of activity in the log you reference, while the former is succeeding and the latter is failing. I'm guessing that that log is not the correct log in debugging the issue, but then again, I'm not very well placed to judge this as I have no clue how the OpenLab testing environment actually works.

Hope this helps you in pinpointing the issue and suggesting me (or the terraform-provider-openstack project maintainers) what to do or where to look...

Regards,
Fred

**Comment by wangxiyuan** [comment]
I know the image import flow. I mean the log is missing, so it's hard for me to know what was happened.

I'm sure the node have web access. From what i can imagine, there is maybe some problem inner Glance. Or the firewall blocked Glance to visit outside.

Let me take the log back first. Please wait more.

Thanks.

**Comment by wangxiyuan** [comment]
@freddebacker I have debugged the image import API, it works as expect. But the flow is very slow.
```
root@ubuntu-bionic-citynetwork-openlab-0000125560:/opt# glance image-show bac93c7d-2da2-4151-a99e-88d5b2a19531
+-------------------------------+----------------------------------------------------------------------------------+
| Property                      | Value                                                                            |
+-------------------------------+----------------------------------------------------------------------------------+
| checksum                      | 443ac0f108670dc8971581306c52f928                                                 |
| container_format              | bare                                                                             |
| created_at                    | 2020-03-28T02:31:39Z                                                             |
| disk_format                   | qcow2                                                                            |
| id                            | bac93c7d-2da2-4151-a99e-88d5b2a19531                                             |
| min_disk                      | 0                                                                                |
| min_ram                       | 0                                                                                |
| name                          | None                                                                             |
| os_glance_failed_import       |                                                                                  |
| os_glance_importing_to_stores |                                                                                  |
| os_hash_algo                  | sha512                                                                           |
| os_hash_value                 | 027ce4a1e6489c4733d3c56cb08c7be490b9a892af2f4664ca6886ff12c05517f28991230bd6eaaf |
|                               | 9c7307ae175858c9f23b839b2c4c9e67f280c5c6730efa4c                                 |
| os_hidden                     | False                                                                            |
| owner                         | 39b7002f6c4244169fc3ac369f4ef11e                                                 |
| protected                     | False                                                                            |
| size                          | 133890048                                                                        |
| status                        | active                                                                           |
| tags                          | []                                                                               |
| updated_at                    | 2020-03-28T02:45:29Z                                                             |
| virtual_size                  | Not available                                                                    |
| visibility                    | shared                                                                           |
+-------------------------------+----------------------------------------------------------------------------------+
```
I created the image at 02:31:39, but it becomes to `active` at 02:45:29Z. It spent 14min
In your test, the test only wait 10min, I think it's the reason.

I'm not sure why Glance spent so much time internally. But Can you choice a small one and try again? For example,  devstack use `cirros` by default which is only 13M.
http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img

**Comment by freddebacker** [comment]
recheck

**Comment by freddebacker** [comment]
Hi @wangxiyuan,

Thanks for taking the time to investigate the issue.

I tried using the 13MB Cirros image and increasing the timeout to 15min, but unfortunately that did not change anything. (Still ongoing while I write this, but the test already failed: https://status.openlabtesting.org/stream/8d2665bc97bf4158a2726686fab6d23e?logfile=console.log)

Also, it seems odd that the `TestAccImagesImageV2_basic` test can complete with a 120MB image in about 20 seconds, and the import one would take minutes...

Anything else I can try?

Regards,
Fred

**Comment by wangxiyuan** [comment]
@freddebacker I get the reason now. The glance image-import works only with `admin` role by default. You use `demo` in the test which lead the failure. You can use `admin` for this test instead, IMO.

**Comment by freddebacker** [comment]
Hi @wangxiyuan ,

Thanks for your feedback.

I can't see in the OpenStack documentation that the `import-image` is restricted to `admin`, but that might be an OpenLab specific thing, right?

Anyway, I flagged the test to require `admin` and now it is just skipped. I'm asking the terraform-provider-openstack maintainers how to proceed...

Regards,
Fred

**Comment by wangxiyuan** [comment]
@freddebacker Oh, yeah. Doubel checked the doc. There is no requirement about `admin` role. Sorry.

But with my test using `demo` role, the glance image-import doesn't work indeed. The image is always in `queued` status.

Then I changed the Glance code:
https://github.com/openstack/glance/blob/master/glance/api/v2/images.py#L196-L197

```
- pool = common.get_thread_pool("tasks_eventlet_pool")
- pool.spawn_n(import_task.run, task_executor)
+ import_task.run(task_executor)
```
i.e. change the async way to sync. Then the API works.

So I guess it's the problem in Glance itself. 

I aslo find the release note in Queue release:
https://docs.openstack.org/releasenotes/glance/queens.html#relnotes-16-0-0-stable-queens-known-issues

It said that image-import doesn't work when Glance runs under uWSGI which is the way devstack run. I don't know if the problem is fixed on master  branch or not. (I prefer **no**) Maybe it's the reason.

I also asked the question in #openstack-glance IRC channel as well. Hope Glance core reviewer can answer me then.

All in all, I don't know how to fix it. Only thing I can ensure is that, the problem is not caused by OpenLab almost.



```

**Comment by freddebacker** [comment]
Thank you @wangxiyuan for troubleshooting on this.

In the specific context, the test fails in OpenLab because of the bug in Glance when installed like DevStack does. The test has been made optional and is skipped in the CI ran on OpenLab. The test can run successfully on other Openstack environments deployed using the Triple-O method.

Closing the issue.

Regards,
Fred
