### ISSUE TITLE
Volume exceed quota 

### ISSUE THREAD

**Issue by wangxiyuan** [theopenlab/openlab#514]
In CPO jobs, when test try to extend the `in-use` volume, sometimes the status of the volume will be changed to `error`. In this case, the volume can't be deleted at once and then it will be remain there even the job is fininshed. It'll lead the number of the volume exceed quota.

We should  delete this kind of volume once the job is finished automatically. Here is one way IMO:

If the volume created by CPO job contain an unique property for each job, like the job's hostname, then OpenLab can know which volume should be deleted once the job is finished. Is it possible for CPO job doing that?

**Comment by wangxiyuan** [comment]
@ramineni @lingxiankong Any thought?

**Comment by lingxiankong** [comment]
Another related issue for CPO is the `cloud-provider-openstack-unittest` job is creating real Cinder volumes which it shouldn't. 

We also need to figure out which jobs are doing `extend the in-use volume` operation so we could fix that one by one.

**Comment by lingxiankong** [comment]
> Another related issue for CPO is the `cloud-provider-openstack-unittest` job is creating real Cinder volumes which it shouldn't.

Trying to fix this one in https://github.com/kubernetes/cloud-provider-openstack/pull/1036

**Comment by ramineni** [comment]
@wangxiyuan As @lingxiankong mentioned , failures related to extend in-use are fixed in the above PR. But still we are facing issues on issues , https://logs.openlabtesting.org/logs/76/976/8f6daa1913d32459133bbd61a3d3527607642d7e/cloud-provider-openstack-multinode-csi-migration-test/cloud-provider-openstack-multinode-csi-migration-test/dd05c16/job-output.txt.gz ,

**Comment by wangxiyuan** [comment]
Thanks. I'll keep looking the test. I'll close the issue once the job runs well.
