### ISSUE TITLE
nkserv

### ISSUE THREAD

**Issue by abdoulk12** [theopenlab/openlab#547]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

**Comment by bzhaoopenstack** [comment]
According to https://docs.openlabtesting.org/contributors/member-application , 
Seems people in group https://github.com/orgs/theopenlab/people?query=role%3Aowner has the priority to make you join. 
@wangxiyuan @liusheng Hi, guys, this seems need your help?

**Comment by wangxiyuan** [comment]
OpenLab is under re-design. Currently, there is no meaning to join the team. i.e. you can do anything with openlab without join the team.(There is no difference)

We'll reopen the join action once the refactor is done.
