### ISSUE TITLE
TestLab

### ISSUE THREAD

**Issue by omyadav1983** [theopenlab/openlab#557]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [X ] Performance
- [ X] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [X ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [X ] Other

### If this is for an open source project what is it? 
OpenStack
### Brief project description
Open source project for demo
### Is project code 100% open source? If so, what is the URL or URLs where it is located?
yes
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VMs
### What OS are you planning to use?
Ubuntu 18.04 LTS
### Any special network configuration you expect or anticipate implementing?
nic
### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
4cpu 16GB
### What testing are you planning to implement or need assistance implementing?
nope
### How will this testing advance application and/or tooling built on-top of open infrastructure?
leverage use of open source in Telco
### Will you publish blog or paper from your testing?
yes
- [ ] Yes
- [ ] No - if no, how will you present your results?

**Comment by bzhaoopenstack** [comment]
Hi @omyadav1983 , thanks for raising this issue. OpenStack is a  very huge system. Could you please tell us the demo? Which project is included? How many VMs is needed? Does a devstack env fitr your requirement?

Thanks
