### ISSUE TITLE
PyTorch and TensorFlow Build Status Badge not working

### ISSUE THREAD

**Issue by AshokBhat** [theopenlab/openlab#558]
### Describe the bug
OpenLab's community build icon is not working in both TensorFlow and PyTorch.

#### TensorFlow
* http://status.openlabtesting.org/builds?project=tensorflow%2Ftensorflow
#### PyTorch
* https://status.openlabtesting.org/builds/builds?project=pytorch%2Fpytorch

### Steps to reproduce the issue
Describe how to reproduce the issue:
#### TensorFlow
* https://github.com/tensorflow/tensorflow/blob/master/README.md points to http://openlabtesting.org:15000/badge?project=tensorflow%2Ftensorflow for Build status. This link is not working and is showing as ERR_CONNECTION_REFUSED.
#### PyTorch
* https://github.com/pytorch/pytorch/blob/master/README.md points to http://openlabtesting.org:15000/badge?project=pytorch%2Fpytorch&job_name=pytorch-arm64-build-daily-master-py36, which is not working.

**Comment by wangxiyuan** [comment]
Fixed now. Big thanks for the reminding.

**Comment by AshokBhat** [comment]
@wangxiyuan  Thanks for fixing it in such a short time :-)

**Comment by bzhaoopenstack** [comment]
Thanks for reminding. @AshokBhat 
Thanks for quick fix. @wangxiyuan
