### ISSUE TITLE
TF CI badge incorrectly setup 

### ISSUE THREAD

**Issue by AshokBhat** [theopenlab/openlab#559]
### Describe the bug
TF CI badge in tensorflow/tensorflow/master/README.md is incorrect.

### Related Job information
TensorFlow CI - http://status.openlabtesting.org/builds?project=tensorflow%2Ftensorflow

### Steps to reproduce the issue
https://raw.githubusercontent.com/tensorflow/tensorflow/master/README.md uses http://openlabtesting.org:15000/badge?project=tensorflow%2Ftensorflow for the nightly build badge.  Instead, it should be using http://openlabtesting.org:15000/badge?project=tensorflow%2Ftensorflow&job_name=tensorflow-arm64-build-daily-master.

This is properly set up for PyTorch CI.

### Additional context
TF CI has been failing for a few days now, but TF in readme.md suggests CI has been working as it points to the wrong badge.

**Comment by wangxiyuan** [comment]
Nice catch. This is the link problem in tf.
now it's http://openlabtesting.org:15000/badge?project=tensorflow%2Ftensorflow

but it should be http://openlabtesting.org:15000/badge?project=tensorflow%2Ftensorflow&job_name=tensorflow-arm64-build-daily-master

@bzhaoopenstack please fix it in tf. Thanks.

**Comment by bzhaoopenstack** [comment]
I know this issue, when the first PR to community, my initial thought is discuss the left 2.0 and 2.1 locations, which is not clear for me. But seems dev team didn't notice the question. Merge it directly. 

This issue will be fixed in the following release CI is ready.

**Comment by wangxiyuan** [comment]
Close the issue now. Feel free to reopen it if there is still the problem
