### ISSUE TITLE
TF community-supported stable release

### ISSUE THREAD

**Issue by AshokBhat** [theopenlab/openlab#560]
### Is your feature enhancement related to a problem? Please describe.
For x86 and PowerPC, TensorFlow provides a community-supported stable release. For Arm, we have a nightly build now. It would be great if we have a stable release for AArch64 as well.

### Describe the solution you'd like
TF community-supported release to support recent TF 2.x and 1.x releases (TF 2.2 and 1.15 as of 15 July 2020).

### Describe alternatives you've considered
None at the moment.

### Additional context
The http://status.openlabtesting.org/builds?project=tensorflow%2Ftensorflow already has TF 2.1 and 2.0 builds available.

**Comment by wangxiyuan** [comment]
@AshokBhat 2.1.0 and 2.0.0 are already there:
https://status.openlabtesting.org/builds?project=tensorflow%2Ftensorflow

you only need to add it to tf doc.

And 1.15 should be supported as well, right? We can add it right now.

**Comment by bzhaoopenstack** [comment]
@AshokBhat @wangxiyuan Thanks guys. Yeah, we never forget to support other versions builds. Will on-board soon. Thanks.

And when the additional builds are ready, let's review them and check whether they are fit for TF community. As we need the direction to how to do and show. Appreciated with your help. Is that OK? ;-)

**Comment by AshokBhat** [comment]
Hello @wangxiyuan @bzhaoopenstack,
Thanks for the quick response. 
Personally, I think having TF 2.1 as a stable release would be great. As you pointed out, this only needs change in TF readme.md, which we are happy to support. When TF 2.3 comes out, might be worth considering upgrading TF 2.1 to TF 2.3. 

As a next step, you may want to consider 1.15 at a later time. We have found it to be working well on Arm (See https://github.com/ARM-software/Tool-Solutions/tree/master/docker/tensorflow-aarch64 for docker recipe).

Thanks for the responsiveness and the good work.
Regards
Ashok

**Comment by bzhaoopenstack** [comment]
Hi @AshokBhat，
Thank you very much for your great advice, we will setup the build recently. For TF 1.15 and 2.1, like powerPC did. Keep the same style with mutiple python version.

Once the whole test is done, we will post a PR in tensorflow community for this release CI. ;-)

**Comment by AshokBhat** [comment]
@bzhaoopenstack Thanks for the quick response and support. Nice to see AArch64 CPU stable releases being part of the community-supported builds.

**Comment by wangxiyuan** [comment]
Feel free to reopen the issue if there is still any problem
