### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by abdelhai7** [theopenlab/openlab#561]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
Abdelhai Mohammed Hassan Bashir
### Github account id
abdelhai7
### Email
dhdooh@gmail.com
### Company/Organization
Syber Technology
### IRC nickname (Optional)
d7d7
### Job Title(optional)
System administration

**Comment by wangxiyuan** [comment]
OpenLab is under re-design. Currently, there is no meaning to join the team.

We'll reopen the join action once the refactor is done.
