### ISSUE TITLE
Gophercloud: Increase timeout of gophercloud-acceptance-test 

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#565]
### Is your feature enhancement related to a problem? Please describe.

The Gophercloud acceptance test suite has gotten large enough that, depending on the underlying node hardware, can take over 3 hours to run.

### Describe the solution you'd like

Increasing the timeout of `gophercloud-acceptance-test` to 4 hours.

Please let me know if anyone has any questions or would like to discuss further.

**Comment by wangxiyuan** [comment]
`gophercloud-acceptance-test` is located in gophercloud repo, you can just increase `timeout` there https://github.com/gophercloud/gophercloud/blob/master/.zuul.yaml

example: https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L275

**Comment by jtopjian** [comment]
@wangxiyuan That's perfect - thank you!
