### ISSUE TITLE
Terraform OpenStack provider acceptance tests are not triggered

### ISSUE THREAD

**Issue by kayrus** [theopenlab/openlab#567]
Thank you for reporting bug!

### Describe the bug

PRs acceptance checks are not triggered.

### Related Job information

https://github.com/terraform-providers/terraform-provider-openstack/pull/1031
https://github.com/terraform-providers/terraform-provider-openstack/pull/1033

/cc @ozerovandrei @wangxiyuan @huangtianhua

**Comment by wangxiyuan** [comment]
@kayrus Sorry about the issue. OpenLab will restart the CI system in 2-3 hours. After that, the Terraform OpenStack provider job will be back. Please wait a few hour and try rechek again.

Thanks.

**Comment by bzhaoopenstack** [comment]
Fix, we add it back. Sorry for my mistake
