### ISSUE TITLE
TensorFlow master build failing since Aug 1

### ISSUE THREAD

**Issue by AshokBhat** [theopenlab/openlab#576]
Thank you for reporting bug!

### Describe the bug
TF master build has been failing since Aug 1

### Related Job information
https://status.openlabtesting.org/builds/builds?project=tensorflow%2Ftensorflow&job_name=tensorflow-arm64-build-daily-master pipeline has been failing since Aug 1

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by bzhaoopenstack** [comment]
Yeah, I already post my fix into upstream, https://github.com/tensorflow/tensorflow/pull/42461 , but seems the communication is not good.

**Comment by cfRod** [comment]
Hi,
We observe the same issue in our internal pipelines. I will have a look into this as well.

**Comment by bzhaoopenstack** [comment]
The upstream PR tensorflow/tensorflow#42461 is committed now, also I tested with that PR in openlab daily job for 5 days. 
see
https://status.openlabtesting.org/builds/builds?project=tensorflow%2Ftensorflow

All builds are success. So close this issue.

**Comment by cfRod** [comment]
thanks @bzhaoopenstack
