### ISSUE TITLE
TensorFlow Build Badge image is not working

### ISSUE THREAD

**Issue by AshokBhat** [theopenlab/openlab#577]
Thank you for reporting bug!

### Describe the bug
Link to the TF build badge cannot be reached.

### Related Job information
Links
- http://openlabtesting.org:15000/badge?project=tensorflow%2Ftensorflow
- http://openlabtesting.org:15000/badge?project=tensorflow%2Ftensorflow&job_name=tensorflow-v1.15.3-cpu-arm64-release-build-show&job_name=tensorflow-v2.1.0-cpu-arm64-release-build-show

### Steps to reproduce the issue
Describe how to reproduce the issue:
The links posted above shows "refused to connect" message.

**Comment by bzhaoopenstack** [comment]
Fixed. The server side dead. Sorry for that.

**Comment by wangxiyuan** [comment]
@bzhaoopenstack  we should add a health check mechanism for badge service

**Comment by bzhaoopenstack** [comment]
Add it. https://github.com/theopenlab/labkeeper/pull/318

**Comment by AshokBhat** [comment]
@bzhaoopenstack  The badge seems to be broken again.
