### ISSUE TITLE
Updating terraform-provider-openstack repository link

### ISSUE THREAD

**Issue by ozerovandrei** [theopenlab/openlab#584]
Hello.

We transferred terraform-provider-openstack to the new Github organization: https://github.com/terraform-provider-openstack/terraform-provider-openstack

This project was migrated to the new repository because of the changes in Hashicorp Terraform providers releasing process.

All providers are moving to https://registry.terraform.io and terraform-providers Github organization is deprecated.

I created the https://github.com/theopenlab/openlab-zuul-jobs/pull/1021 pull request to update the `Project` tag in jobs.

Is it enough to update them or could you please do additional steps so project repository will be updated?

Thanks!

**Comment by wangxiyuan** [comment]
@ozerovandrei the CI works now. Please check it in the new repo

**Comment by ozerovandrei** [comment]
@wangxiyuan it's working great!

Thank you!
