### ISSUE TITLE
Vexxhost VM cannot request metadata from 169.254.169.254

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#60]
see job log: http://logs.openlabtesting.org/logs/65/165/579db7370ad5fbf2d5e0fab972bac115b6e2034d/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/397c583/job-output.txt.gz

I have manually test with a vexxhost vm by curl command, it also cannot request metadata.

**Comment by mrhillsman** [comment]
@liu-sheng @kiwik @animationzl let's switch/add configdrive for nodes in VEXXHOST for these jobs. we tested this morning and metadata service was responding some times and connection refused other times; configdrive should resolve this.

**Comment by mrhillsman** [comment]
@liu-sheng closing, please re-open if issue happens again.
