### ISSUE TITLE
cloud provider openstack CSI cinder failed

### ISSUE THREAD

**Issue by jichenjc** [theopenlab/openlab#603]
Thank you for reporting bug!

### Describe the bug

note: this occurs several times (almost 100%) ,so I created a test PR 
https://github.com/kubernetes/cloud-provider-openstack/pull/1279

https://logs.openlabtesting.org/logs/79/1279/5acfd5dee7de6814cd219bfaa22d529be8ffc66a/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/4a355c9/job-output.txt.gz

I suspect this is the root cause: 

```
2020-10-19 00:12:27.379762 | ubuntu-xenial-citynetwork |   Normal   Provisioning        46s (x9 over 5m1s)  cinder.csi.openstack.org_csi-cinder-controllerplugin-0_27970547-4613-448b-8814-4af7983b2af6  External provisioner is provisioning volume for claim "default/csi-pvc-cinderplugin"
2020-10-19 00:12:27.379799 | ubuntu-xenial-citynetwork |   Warning  ProvisioningFailed  45s (x9 over 5m)    cinder.csi.openstack.org_csi-cinder-controllerplugin-0_27970547-4613-448b-8814-4af7983b2af6  failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Internal desc = CreateVolume failed with error Expected HTTP response code [202] when accessing [POST https://lon1.citycloud.com:8776/v3/06ce5499f716488d985845cddcabdc16/volumes], but got 413 instead
2020-10-19 00:12:27.379827 | ubuntu-xenial-citynetwork | {"overLimit": {"message": "VolumeLimitExceeded: Maximum number of volumes allowed (10) exceeded for quota 'volumes'.", "code": 413, "retryAfter": "0"}}
2020-10-19 00:12:27.379848 | ubuntu-xenial-citynetwork |   Normal  ExternalProvisioning  14s (x21 over 5m1s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator
```

**Comment by wangxiyuan** [comment]
The qouta of volme in openlab is 10.  The problem is that the volume which CPO job create was not cleaned up.

The CPO job should clean up the volume which is created by itself. Please check the POST task for this job to see why it doesn't work.

**Comment by jichenjc** [comment]
um.... it is possible it's caused by previous failed job (job failed but volume not cleaned?)? as you can see, this PR doesn't do any change to the code at all and previously it runs well

**Comment by wangxiyuan** [comment]
yes, it may be caused by any CPO cinder job.

**Comment by jichenjc** [comment]
@wangxiyuan the error comes from 
https://logs.openlabtesting.org/logs/79/1279/5acfd5dee7de6814cd219bfaa22d529be8ffc66a/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/4a355c9/job-output.txt.gz

and it comes from 
https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml#L144

this is the only and first place that create a volume in this job..
can you help to check openstack job ? is there any legacy volume remaining in this project?
less likely caused by CPO side...

**Comment by jichenjc** [comment]
@wangxiyuan can you help to check the cloud/project running the jobs for Cinder CSI? 
as I mentioned, the job seems only create 1 volume.. I can't see the detail info of the cloud so that's my rough guess ,thanks

**Comment by wangxiyuan** [comment]
The problem is not related to the log you point. I'll keep looking for this problem. Currently, I have to clean up the resource by hand.

**Comment by wangxiyuan** [comment]
There is another bug that the new created snapshot in citynetwork can not be deleted, its status is changed to `error_deleting`. Since we don't have the admin role for citynetwork, we can't force delete the snapshot and volume. So currently, there are only 5 quota for CPO volume test. I'll contract citynetwork admin to fix it. If you hit the quota limit error agine, feel free to recheck later.  Thanks

**Comment by jichenjc** [comment]
thanks, I think the test is related to volume and not related to snapshot (because the logs I added here is acceptance test , not e2e ), anyway, I will recheck my original PR and see what happened, thanks

**Comment by jichenjc** [comment]
I met this issue again after retest test for a while..

**Comment by wangxiyuan** [comment]
There is some bugs for volume snapshot in citynetwork, the snapshot which created by CPO jobs can't be deleted. So the quota is limited. We need contract citynetwork fo fix it. Please wait more. I consider to move Cinder related job to other cloud as well. I'll let you know once it is done.

**Comment by jichenjc** [comment]
thanks, I will hold the https://github.com/kubernetes/cloud-provider-openstack/pull/1175
because of the environment issue

please help to solve the current env so that other PR will not be blocked. thanks

**Comment by bzhaoopenstack** [comment]
Open a ticket to citynetwork. Let's wait for the feedback from them

**Comment by jichenjc** [comment]
suffered this again ..
https://logs.openlabtesting.org/logs/40/1240/1281b7f544f0f5d405626866a346b1f5d34a782c/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/813952b/job-output.txt.gz

I did retry several times 
not sure what's the root cause but seems it will happen after the test execute several times (not specific for one PR , maybe multiple PR test lead to this issue? )

**Comment by wangxiyuan** [comment]
as I said before, this is caused by citynetwork itself. the volume can't be deleted automaticly. @bzhaoopenstack has asked citynetwork for help, but there is still no response. We can do nothing bu wait for citynetwork admin's response.

**Comment by jichenjc** [comment]
ok, I thought it's code lead to problem, now I understand it's their env issue
so I will wait .. (because it works early this week so I thought it might be code related issue)

**Comment by jichenjc** [comment]
ok, the situation become better now (previously 3 cases failed with 413 error and now only 1 case failed ) 
https://logs.openlabtesting.org/logs/02/1302/a6a901dea0b61e6be703ee57cede5493dcab1b17/cloud-provider-openstack-multinode-csi-migration-test/cloud-provider-openstack-multinode-csi-migration-test/110eff9/logs/kubernetes/junit_01.xml

```
StorageClass "in-tree": rpc error: code = Internal desc = CreateVolume failed with error Expected HTTP response code [202] when accessing [POST https://lon1.citycloud.com:8776/v3/06ce5499f716488d985845cddcabdc16/volumes], but got 413 instead {"overLimit": {"message": "VolumeLimitExceeded: Maximum number of volumes allowed (10) exceeded for quota 'volumes'.", "code": 413, "retryAfter": "0"}} Nov 2 18:29:06.343: INFO: At 2020-11-02 18:18:46 +0000 UTC - event for vol3-many-volumes-test-0: {cinder.csi.openstack.org_csi-cinder-controllerplugin-0_00a2c583-55e4-4c95-b5f9-1ba56a7cf500 } ProvisioningFailed: failed to provision volume with StorageClass "in-tree": rpc error: code = Internal desc = CreateVolume failed with error Expected HTTP response code [202] when accessing [POST https://lon1.citycloud.com:8776/v3/06ce5499f716488d985845cddcabdc16/volumes], but got 413 instead {"overLimit": {"message": "VolumeLimitExceeded: Maximum number of volumes allowed (10) exceeded for quota 'volumes'.", "code": 413, "retryAfter": "0"}} Nov 2 18:29:06.343: INFO: At 2020-11-02 18:18:46 +0000 UTC - event for vol3-many-volumes-test-0: {persistentvolume-controller } ExternalProvisioning: waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator Nov 2 18:29:06.343: INFO: At 2020-11-02 18:18:46 +0000 UTC - event for vol3-many-volumes-test-0: {cinder.csi.openstack.org_csi-cinder-controllerplugin-0_00a2c583-55e4-4c95-b5f9-1ba56a7cf500 } Provisioning: External provisioner is provisioning volume for claim "pv-6094/vol3-many-volumes-test-0" Nov 2 18:29:06.343: INFO: At 2020-11-02 18:18:47 +0000 UTC - event for vol0-many-volumes-test-0: {cinder.csi.openstack.org_csi-cinder-controllerplugin-0_00a2c583-55e4-4c95-b5f9-1ba56a7cf500 } ProvisioningSucceeded: Successfully provisioned volume pvc-e2a364a1-005c-4d2c-b399-fa045dc35c5e Nov 2 18:29:06.343: INFO: At 2020-11-02 18:18:47 +0000 UTC - event for vol1-many-volumes-test-0: {cinder.csi.openstack.org_csi-cinder-controllerplugin-0_00a2c583-55e4-4c95-b5f9-1ba56a7cf500 } ProvisioningSucceeded: Successfully provisioned volume pvc-a9cb83fb-8c57-419e-9cae-cc8f97863944 Nov 2 18:29:06.343: INFO: At 2020-11-02 18:28:46 +0000 UTC - event for many-volumes-test: {statefulset-controller } SuccessfulDelete: delete Pod many-volumes-test-0 in StatefulSet many-volumes-test successful Nov 2 18:29:06.343: INFO: At 2020-11-02 18:28:46 +0000 UTC - event for many-volumes-test-0: {default-scheduler } FailedScheduling: skip schedule deleting pod: pv-6094/many-volumes-test-0 Nov 2 18:29:06.345: INFO: POD NODE PHASE GRACE CONDITIONS Nov 2 18:29:06.345: INFO: Nov 2 18:29:06.348: INFO: Logging node info for node ubuntu-xenial-citynetwork-citynetwork-openlab-0000154300 Nov 2 18:29:06.351: INFO: Node Info: &Node{ObjectMeta:{ubuntu-xenial-citynetwork-citynetwork-openlab-0000154300 /api/v1/nodes/ubuntu-xenial-citynetwork-citynetwork-openlab-0000154300 2dd97637-6d28-472b-8a01-066356ef4a69 7221 0 2020-11-02 17:58:51 +0000 UTC <nil> <nil> map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:8C-8GB-200GB beta.kubernetes.io/os:linux failure-
```
https://github.com/kubernetes/cloud-provider-openstack/pull/1302 is a quick test
not sure it's becuase limit increased by citynetwork? just record and track here

**Comment by jichenjc** [comment]
@wangxiyuan do you have any update from citynetwork? 
the whole CSI openstack is blocked now ..

**Comment by wangxiyuan** [comment]
@jichenjc   I guss this issue can be closed?

**Comment by jichenjc** [comment]
yes, thanks :)

**Comment by jichenjc** [comment]
sorry, has to reopen this to get further info about snapshot support 

we are still seeing this error 
https://github.com/kubernetes/cloud-provider-openstack/pull/1175#issuecomment-769603116

>>>There is some bugs for volume snapshot in citynetwork, the snapshot which created by CPO jobs can't be deleted. So the quota is limited. We need contract citynetwork fo fix it. Please wait more. I consider to move Cinder related job to other cloud as well. I'll let you know once it is done.

has this been done Yet?

**Comment by wangxiyuan** [comment]
cleaned
