### ISSUE TITLE
cluster-api-provider-openstack job failed due to devstack install 

### ISSUE THREAD

**Issue by jichenjc** [theopenlab/openlab#610]
Thank you for reporting bug!

### Describe the bug

devstack install failed 

https://logs.openlabtesting.org/logs/57/657/b62e3e6797436843be7cedf4bf7dafa072b436d3/check/cluster-api-provider-openstack-current-acceptance-test-v1.18/6145429/logs/devstacklog.txt

retried several times and still fail

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/657

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by jichenjc** [comment]
@wangxiyuan anything might be helpful to check how to proceed on this? thanks

**Comment by wangxiyuan** [comment]
nova-compute raised error: https://logs.openlabtesting.org/logs/57/657/b62e3e6797436843be7cedf4bf7dafa072b436d3/check/cluster-api-provider-openstack-current-acceptance-test-v1.18/6145429/logs/screen-n-cpu.txt

is this a devstack bug?

BTW, feel free to fix any CI problem with your PR. I can't ensure to reply every comment at once.

**Comment by jichenjc** [comment]
I can try to fix issues related to the job but if it's a devstack issue , then I can't handle it :)

**Comment by hidekazuna** [comment]
Now in progress in Nova community.
https://bugs.launchpad.net/nova/+bug/1901383

**Comment by jichenjc** [comment]
@hidekazuna thanks for the info, yes, let's wait for the fix

**Comment by hidekazuna** [comment]
The bug has been fixed and our test succeeded.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/657#issuecomment-718286413
