### ISSUE TITLE
Apply fo ARM64 VM to build FRocksDB

### ISSUE THREAD

**Issue by Myasuka** [theopenlab/openlab#614]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org
### What is your focus?
- [x] Other
    --Portability

### If this is for an open source project what is it?
Yes, FRocksDB - https://github.com/ververica/frocksdb

### Brief project description
RocksDB with modifications specific for Apache Flink

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://github.com/ververica/frocksdb

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
We are looking for an aarch64 machine, for both compiling releases of the software and also for running a CI

### What OS are you planning to use?
Prefer CentOS

### Any special network configuration you expect or anticipate implementing?
N/A

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
ARM 64 should be enough.

### What testing are you planning to implement or need assistance implementing?
That the software compiles.

### How will this testing advance application and/or tooling built on-top of open infrastructure?
We will publish ARM64 builds of FRocksDB alongside our existing x86, x86_64, and ppc64le builds.

### Will you publish blog or paper from your testing?

- [x] No - if no, how will you present your results?
Provide for our customers.

### Any other relevant details we should know about while preparing the infrastructure?
N/A

**Comment by wangxiyuan** [comment]
@Myasuka I‘ve send the VM info to your private email address myasuka@live.com, please check your box. I think it can be used for frocksdb arm64 relaese.

While for arm64 CI, I suggest to use CI systems which support arm64, like Travis , Openlab  and so on.
