### ISSUE TITLE
[Citynetwork issues] Citynetwork volumes can not be removed. 

### ISSUE THREAD

**Issue by bzhaoopenstack** [theopenlab/openlab#623]
Citynetwork Volumes can not be deleted due to the all volume assciated with a snapshot, which status is `error_deleting`, and openlab has no right to operate.  Now, we have 10 volume quota in UK, so this will affect other task which want to test volume resource, especially CPO jobs.

Already post 2 tickets to Citynetwork, no response till now.

So hope @tobberydberg can give some helps. Thank you very much.

Now the affected volumes are
```
root@citynetwork-openlab-nodepool:~# openstack --os-cloud citynetwork volume list
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------+
| ID                                   | Name                                     | Status    | Size | Attached to                                       |
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------+
| 268640f7-3937-43bb-ac3b-6be8c5f862cb | pvc-d67d46ce-6afc-48f4-a74a-9f6ff830b4a0 | available |    1 |                                                   |
| 1ad711c7-2847-43d6-8049-e51a4d106228 | pvc-8be00112-7901-480f-8399-82b3ad120cbf | available |    1 |                                                   |
| 1bb0c86f-f416-430b-bdc7-3c3287dbc350 | pvc-8f48be6a-5590-42ea-a54c-88f2c4d071f9 | available |    1 |                                                   |
| eb8d6cb0-f418-4609-a6e0-a546c4136137 | pvc-1bdd3cb8-0e74-47e6-b7a9-e3ad397a0147 | available |    1 |                                                   |
| 116a40ee-8061-45f3-97db-55c99f5fc5d3 | pvc-e2966327-faff-494c-a14a-039973b76742 | available |    1 |                                                   |
| 27bfed03-d5f6-4fba-8e01-f18b20a47941 | pvc-6993ff62-515b-49dd-b6f6-8865ad7753a7 | available |    1 |                                                   |

```

All of them has a error snapshot, and we have no right to operate more, even delete.

```
root@citynetwork-openlab-nodepool:~# openstack --os-cloud citynetwork snapshot list
This command has been deprecated. Please use "volume snapshot list" instead.
+--------------------------------------+-----------------------------------------------+----------------------------------------+----------------+------+
| ID                                   | Name                                          | Description                            | Status         | Size |
+--------------------------------------+-----------------------------------------------+----------------------------------------+----------------+------+
| e5df9a68-06de-4d19-b19c-ea0255f543fa | snapshot-05d77a17-626a-4ce3-a095-7886fb3170b9 | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| 3fea657f-88bf-4e41-bedc-d926fefe25b5 | snapshot-cefe686c-46e5-434c-9e64-54fd25df3e15 | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| 267afdaf-b792-49ee-a629-ff6c8d2014fa | snapshot-372d13f3-3adf-47d7-b600-de16933f92af | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| c88a9b7a-eac5-4ffe-90a9-a18c44df68df | snapshot-3c1e25e8-6ad2-4617-8953-b01925ce696f | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| 00559fbf-368a-44bb-8145-a8a94c575631 | snapshot-fb605c2d-f88f-4bcb-bca8-e5ba65707bbb | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| f03ce254-c9e0-4ac0-9681-1dcff628acf0 | snapshot-d8053d12-6be0-4408-985a-49eed84941cc | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
+--------------------------------------+-----------------------------------------------+----------------------------------------+----------------+------+

```

**Comment by bzhaoopenstack** [comment]
@jichenjc @lingxiankong  let's waiting for @tobberydberg to help this. 

This is the only way to resolve this now during I search..

**Comment by jichenjc** [comment]
@bzhaoopenstack thanks 

I guess it's related to e2e test PR but not sure ,so need wait for clean env and check again

**Comment by tobberydberg** [comment]
Hi! 
Situation resolved ... sorry for the inconvenience in this matter. Is this always happening while using the Cinder CSI driver or have you seen this in general? Haven't heard of any other customer reports having these issues, thats why I'm asking.

I've updated your quota for volumes to a 100 ... is there any other quota that is an issue for you today that I should look into as well?

Also, can you pleases tell me how you have reported this before reaching out to me? Would like to investigate why you haven't gotten any response...

Cheers,
Tobias

**Comment by bzhaoopenstack** [comment]
Hi, @tobberydberg .

Thank you very much for the quick action. 
This issue looks a long time when we exec our task job, which test volumes, I think @jichenjc might know more. 

Thanks, the volume quota is enough for now. And no requests for other resource quota.

I opened 2 tickets via https://citycloud.com/support/ , I find there are some automatic emails sent the openlab gmail. The first ticket was closed very quick only few days without any help, and just asking me the affected volumes. But the second ticket didn't get response till now.

Thanks,
Bo Zhao

**Comment by jichenjc** [comment]
I suspect https://github.com/kubernetes/cloud-provider-openstack/pull/1175 but have no evidence
so might need additional help if we re - run the test (currently it's on hold)

**Comment by tobberydberg** [comment]
Ok, thanks for the information! And, you should of course get response the official way, but if not, keep pinging me :-)

**Comment by wangxiyuan** [comment]
@tobberydberg Big thanks!. Let's keep this issue open. I'll close it if there is no related issues in next few days.

**Comment by wangxiyuan** [comment]
looks everything goes well.  Thanks, all
