### ISSUE TITLE
PyTorch Arm64 CI has been failing since late Oct

### ISSUE THREAD

**Issue by AshokBhat** [theopenlab/openlab#630]
### Describe the bug
PyTorch AArch64 master CI has been failing - https://status.openlabtesting.org/builds/builds?project=pytorch%2Fpytorch

### Related Job information
If the bug is related a CI job, put the job information below:
* job name: pytorch-arm64-build-daily-master-py36 
* job build log link:  https://logs.openlabtesting.org/logs/periodic-0/github.com/pytorch/pytorch/master/pytorch-arm64-build-daily-master-py36/051c6fa/job-output.txt.gz

**Comment by wangxiyuan** [comment]
yeah, I noticed the error. I'll try my best to fix it recently. I'm not sure it is the problem in openlab infra or not. If it's a pytorch bug, could you please take a look fix it as well?

**Comment by wangxiyuan** [comment]
when XNNPACK was bumped from `1b354636b5942826547055252f3b359b54acff95` to `f703d4f6ad97039bc6fb38c9fd59df35d9f87df6`, the error happened.  I guess there is some change between these two commit that break arm64.

**Comment by AshokBhat** [comment]
@wangxiyuan I think you are right. The issue is mostly like to do with PyTorch upstream. Can you please let me know which GCC version do you use for compiling? There seems to be an using GCC 8 and earlier.

**Comment by wangxiyuan** [comment]
There is some issuse for gcc buiding pytorch previously. So I uses clang in openlab https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/pytorch-arm-build/run.yaml#L82  It's 6.0.0 I think

**Comment by wangxiyuan** [comment]
I think this change breaks arm64 https://github.com/google/XNNPACK/commit/a9644738a457f6353cec741f763a6c7b7ac49a73

**Comment by AshokBhat** [comment]
@wangxiyuan, I think the issue could be the GCC version. From table https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/architecture-support, I see that GCC8 is the first version that supported dot-product instruction.

**Comment by wangxiyuan** [comment]
when change to gcc 7.6, the build is pass now. I'll try to use gcc8 later to see what'll happen http://status.openlabtesting.org/builds?job_name=pytorch%2Fpytorch

**Comment by AshokBhat** [comment]
Got fixed.
