### ISSUE TITLE
Lots of jobs are in unknown status for over 20 hours

### ISSUE THREAD

**Issue by ozerovandrei** [theopenlab/openlab#642]
Hello team!

There seems to be some issue with the OpenLab since there are some jobs that got stuck in the "unknown" status for over 20 hours:

http://status.openlabtesting.org/status

Also typing "recheck" does not work for terraform-provider-openstack jobs.

**Comment by wangxiyuan** [comment]
yeah, thanks for bring this up. We'll fix it soon. @bzhaoopenstack

**Comment by bzhaoopenstack** [comment]
Thanks, I think openlab will be back soon. The issue had beed addressed.

**Comment by bzhaoopenstack** [comment]
OpenLab is back now, please recheck and so apology for the error.

**Comment by ozerovandrei** [comment]
It works! Thanks!
