### ISSUE TITLE
TensorFlow and PyTorch on AArch64 CI failing due to NODE_FAILURE since beginning of Jan.

### ISSUE THREAD

**Issue by AshokBhat** [theopenlab/openlab#654]
Thank you for reporting bug!

### Describe the bug
TF and PyTorch CI are failing due to NODE_FAILURE since the beginning of Jan.

### Related Job information
TensorFlow and PyTorch on AArch64 CI

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by wangxiyuan** [comment]
The reason is that some policy is changed from new year. It is fixed today. Please check it.

**Comment by bzhaoopenstack** [comment]
Issue is gone
