### ISSUE TITLE
Branch renaming in terraform-provider-openstack

### ISSUE THREAD

**Issue by ozerovandrei** [theopenlab/openlab#661]
Hello.

We renamed `master` branch to `main` in [terraform-provider-openstack](https://github.com/terraform-provider-openstack/terraform-provider-openstack) according to Github guidance [github/renaming](https://github.com/github/renaming#renaming-the-default-branch-from-master).

Currently OpenLab checks are not running and I don't see how can I update the branch name in [openlab-zuul-jobs](https://github.com/theopenlab/openlab-zuul-jobs).

Could you please help?

**Comment by wangxiyuan** [comment]
Let us check. @bzhaoopenstack

**Comment by wangxiyuan** [comment]
https://github.com/theopenlab/openlab-zuul-jobs/pull/1080

**Comment by wangxiyuan** [comment]
https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1131 fixed

**Comment by ozerovandrei** [comment]
@wangxiyuan there is an error about branch name in the logs:

https://logs.openlabtesting.org/logs/31/1131/06319f7d00b0aab36401e55a7a524f4086aa0d34/check/terraform-provider-openstack-acceptance-test/af41be9/job-output.txt.gz

```
2021-01-18 08:03:47.774302 | ubuntu-bionic | 2021-01-18 08:03:47,774 ERROR: branch not allowed by features matrix: main
2021-01-18 08:03:47.778681 | ubuntu-bionic | + MY_ENABLED_SERVICES=
2021-01-18 08:03:47.779312 | ubuntu-bionic | ERROR: the main setup script run by this job failed - exit code: 1
2021-01-18 08:03:47.779364 | ubuntu-bionic |     please look at the relevant log files to determine the root cause
```

**Comment by wangxiyuan** [comment]
I guess it's fixed by https://github.com/theopenlab/openlab-zuul-jobs/commit/e5a33ffd9c796f0da3a0b41e49cb622f448be17c  Let me know if there is any other issue

**Comment by ozerovandrei** [comment]
Thank you!
