### ISSUE TITLE
occm: update ubuntu to focal

### ISSUE THREAD

**Issue by kayrus** [theopenlab/openlab#667]
Thank you for reporting bug!

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:

### Steps to reproduce the issue

At least two jobs are failing because they require bash version >= 5.0
Updating ubuntu images from xenial to focal should solve this issue.

### Additional context

See https://logs.openlabtesting.org/logs/82/1382/7ea35e198b6ceef689589372b8bd1686eff12207/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/6dc2ab5/
https://github.com/kubernetes/cloud-provider-openstack/pull/1382

**Comment by jichenjc** [comment]
should be affected by 
```
commit feecef7795012ed24c90e83cb4c0283d1a1e7beb
Author: Davanum Srinivas <davanum@gmail.com>
Date:   Fri Jan 22 08:29:42 2021 -0500

    Ensure bash version at least 5.x

    Co-authored-by: Stephen Augustus <justaugustus@users.noreply.github.com>
    Signed-off-by: Davanum Srinivas <davanum@gmail.com>


```

**Comment by jichenjc** [comment]
@wangxiyuan I think openlab is using 16.04 now? can you upgrade to 18.04 if possible?

**Comment by wangxiyuan** [comment]
sure We'll update it soon @bzhaoopenstack

**Comment by wangxiyuan** [comment]
currently, all CPO jobs run on ubuntu 16.04. So you just need  change `cloud-provider-openstack-acceptance-test-csi-cinder` to 18.04 or all CPO jobs need update to 18.04? @kayrus @jichenjc

**Comment by bzhaoopenstack** [comment]
@jichenjc Do we need to upgrade the all testnode from 1604 to 1804? Or just a single job "cloud-provider-openstack-acceptance-test-csi-cinder" which mentioned above?

**Comment by jichenjc** [comment]
from https://github.com/kubernetes/cloud-provider-openstack/pull/1384
seems those 4 need update

 @theopenlab-ci
openlab/cloud-provider-openstack-acceptance-test-csi-cinder — cloud-provider-openstack-acceptance-test-csi-cinder status: failure
@theopenlab-ci
openlab/cloud-provider-openstack-acceptance-test-csi-manila — cloud-provider-openstack-acceptance-test-csi-manila status: failure
@theopenlab-ci
openlab/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization — cloud-provider-openstack-acceptance-test-keystone-authentication-authorization status: failure
@theopenlab-ci
openlab/cloud-provider-openstack-e2e-test-csi-cinder — cloud-provider-openstack-e2e-test-csi-cinder status: failure

**Comment by bzhaoopenstack** [comment]
@jichenjc Ok, got it. Thanks

**Comment by bzhaoopenstack** [comment]
Notes: `cloud-provider-openstack-acceptance-test-csi-manila` and `cloud-provider-openstack-acceptance-test-keystone-authentication-authorization` are already ubuntu bionic.

So this time, I will upgrade the others testnodes from 1604 to 1804, which are `cloud-provider-openstack-acceptance-test-csi-cinder` and `cloud-provider-openstack-e2e-test-csi-cinder`

**Comment by bzhaoopenstack** [comment]
Zuul server restarting

**Comment by kayrus** [comment]
Still doesn't work: https://logs.openlabtesting.org/logs/82/1382/7ea35e198b6ceef689589372b8bd1686eff12207/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/1d7cb09/job-output.txt.gz

```
2021-01-26 07:09:25.581315 | ubuntu-bionic-citynetwork | make[1]: Entering directory '/home/zuul/src/k8s.io/kubernetes'
2021-01-26 07:09:26.801362 | ubuntu-bionic-citynetwork | ERROR: This script requires a minimum bash version of 5.0
2021-01-26 07:09:26.814053 | ubuntu-bionic-citynetwork | ERROR: This script requires a minimum bash version of 5.0
```

**Comment by jichenjc** [comment]
@kayrus I did another check, I am using bionic, but seems it's 4.4.x which doesn't satisfy the requirement
can you confirm whether your env (bionic) can solve the problem ? otherwise we might need add some scripts to
increase version of bash...


```
root@jjtest1:~# uname -a
Linux jjtest1 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@jjtest1:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@jjtest1:~# bash help
bash: help: No such file or directory
root@jjtest1:~# /bin/bash -version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by kayrus** [comment]
@jichenjc my bad. My local env is 20.04, which is focal, not bionic.

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

therefore we need to upgrade all VMs to focal.

**Comment by jichenjc** [comment]
@bzhaoopenstack @wangxiyuan can you help to see whether you can increase to focal (20.04) not sure devstack support or not .. thanks

**Comment by wangxiyuan** [comment]
@jichenjc yeah, we can. While there is no available 20.04 image for zuul, we need to build a new one first. It may cost some time. Please give us one or two day. Thanks.

**Comment by jichenjc** [comment]
> 
> 
> @jichenjc yeah, we can. While there is no available 20.04 image for zuul, we need to build a new one first. It may cost some time. Please give us one or two day. Thanks.

thanks :) , please let us know when it's ready so we can retirgger our original test, thanks

**Comment by bzhaoopenstack** [comment]
Need restart zuul, but there is a on-going test which raise by kubernetes-sigs/cluster-api-provider-openstack#732

**Comment by kayrus** [comment]
when the change will be available in openlab?

**Comment by bzhaoopenstack** [comment]
@kayrus Already enabled. See https://github.com/theopenlab/openlab-zuul-jobs/pull/1089

**Comment by bzhaoopenstack** [comment]
Hmm, for the new test image ubuntu-focal, if some specific test jobs need reply on docker, then the docker version need to upgrade also.. see https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/ , the lowest docker version is 19.03， but the job configured is still 18.09

**Comment by jichenjc** [comment]
@bzhaoopenstack so you mean we need update the job file? I will check what I can do ...

**Comment by jichenjc** [comment]
@bzhaoopenstack looks like the docker logic is 
https://github.com/theopenlab/openlab-zuul-jobs/blob/master/roles/install-k8s/tasks/main.yaml#L5

which is common one ... is it possible to create another docker role to 19.03? 
seems it's not in provider specific folder..

**Comment by bzhaoopenstack** [comment]
@jichenjc Hi

https://github.com/theopenlab/openlab-zuul-jobs/pull/1093/files , I had adapted the install-k8s role for the new test image.

I test only 1 jobs in https://github.com/kubernetes/cloud-provider-openstack/pull/1382#issuecomment-770123889 , seem works. So you can try other jobs, then change the test nodeset and config the new options for the test jobs if possible.

**Comment by jichenjc** [comment]
Thanks , please close this and I will reopen if further question found :) thanks

**Comment by bzhaoopenstack** [comment]
OK, thanks
