### ISSUE TITLE
Make tests know which OpenStack release is provided by OpenLab

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#67]
Add envrionment variable `OS_BRANCH` into testing context when OpenLab launch a project integration tests, that make test cases have chance to know which OpenStack release test against, in order to skip some test cases that is not supported in some old OpenStack release.

**Comment by kiwik** [comment]
assign @liu-sheng

**Comment by liu-sheng** [comment]
address by https://github.com/gophercloud/gophercloud/pull/1023

**Comment by kiwik** [comment]
Finished
