### ISSUE TITLE
occm: functional tests fail

### ISSUE THREAD

**Issue by kayrus** [theopenlab/openlab#674]
Thank you for reporting bug!

### Describe the bug

A lot of functional tests fail. One of the issue is:

```
k8s-node-1 | [preflight] Reading configuration from the cluster...
k8s-node-1 | [preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
k8s-node-1 | error execution phase kubelet-start: a Node with name "ubuntu" and status "Ready" already exists in the cluster. You must delete the existing Node or change the name of this new joining Node
k8s-node-1 | To see the stack trace of this error execute with --v=5 or higher
```

### Related Job information

https://github.com/kubernetes/cloud-provider-openstack/pull/1384

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by kayrus** [comment]
Looks like automation uses default `ubuntu` hostname for all nodes, instead of `k8s-master`, `k8s-node-1` and `k8s-node-2`

**Comment by wangxiyuan** [comment]
yes, the hostname is ubuntu. If you want to change it, just update the job file.

**Comment by bzhaoopenstack** [comment]
@kayrus Hi, `k8s-master`, `k8s-node-1` and `k8s-node-2` are just the zuul test node names, they are not hostnames. The underly test VMs are other hostnames. And that's right, the hostname `ubuntu` is the way for forbiding the connection with hostname. We suggest that you can reconfigure `/etc/hosts/` on the 3 testnodes. And I also don't think zuul support this.

**Comment by kayrus** [comment]
Unfortunately I don't know how the hostnames were configured before. Do you have an idea what was changed? Is it caused by ubuntu upgrade to focal? All new PRs fail the tests, OCCM development is completely blocked and opensource community cannot proceed.
cc @ramineni @jichenjc @lingxiankong

**Comment by lingxiankong** [comment]
I am looking into this now.

**Comment by kayrus** [comment]
@lingxiankong any findings or updates?

**Comment by lingxiankong** [comment]
> @lingxiankong any findings or updates?

Still troubleshooting. Almost there.

**Comment by jichenjc** [comment]
@bzhaoopenstack I think your openstack image original hostname is ubuntu? 
should `cloud-init` handle the hostname re-configure when you deploy VMs ? 
I think it's in even before the devstack start, we may refer to previous (18.04 ) output to compare 

this are in playbooks/init-test/pre.yaml and one node is ok but multiple should fail 
```
2021-02-01 11:19:03.277475 | TASK [Get local hostname]
2021-02-01 11:19:03.966242 | k8s-node-2 | ubuntu
2021-02-01 11:19:03.966879 | k8s-node-1 | ubuntu
2021-02-01 11:19:04.094353 | k8s-master | ubuntu
```

**Comment by lingxiankong** [comment]
I've already submitted a few patches to fix this (hopefully), now I can see the conformance test is running, let's wait for the result.

**Comment by lingxiankong** [comment]
> cloud-provider-openstack-acceptance-test-e2e-conformance : SUCCESS in 2h 24m 34s

Yay!

**Comment by lingxiankong** [comment]
This issue (for occm) can be closed, I will look at the others.

**Comment by kayrus** [comment]
The issue still exists in [some cases](https://logs.openlabtesting.org/logs/84/1384/a2a6c42d771b29e4a364b78145904ec971e28072/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.19/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.19/e527603/):

````
2021-02-05 12:44:27.158844 | TASK [Set hostname]
2021-02-05 12:44:28.245739 | k8s-node-1 | ERROR
2021-02-05 12:44:28.246317 | k8s-node-1 | {
2021-02-05 12:44:28.246414 | k8s-node-1 |   "msg": "Command failed rc=1, out=, err=Failed to create bus connection: No such file or directory\n"
2021-02-05 12:44:28.246500 | k8s-node-1 | }
2021-02-05 12:44:28.332393 | k8s-master | changed
2021-02-05 12:44:28.373630 | k8s-node-2 | changed
```

**Comment by kayrus** [comment]
Also we have this error:

```
2021-02-05 12:48:00.182515 | k8s-master | + docker tag k8scloudprovider/openstack-cloud-controller-manager-amd64:latest k8scloudprovider/openstack-cloud-controller-manager:latest
2021-02-05 12:48:00.247896 | k8s-master | Error response from daemon: No such image: k8scloudprovider/openstack-cloud-controller-manager-amd64:latest
```

**Comment by kayrus** [comment]
I see that devstack is failing to install:

```
2021-02-05 14:49:25.392 | Installing collected packages: linecache2, traceback2, pbr, argparse, wcwidth, unittest2, python-mimeparse, pyperclip, fixtures, extras, colorama, attrs, testtools, stevedore, PyYAML, PrettyTable, cmd2, voluptuous, python-subunit, future, cliff, stestr, os-testr
2021-02-05 14:49:27.149 |   Attempting uninstall: colorama
2021-02-05 14:49:27.150 |     Found existing installation: colorama 0.4.3
2021-02-05 14:49:27.353 |     Uninstalling colorama-0.4.3:
2021-02-05 14:49:29.338 |       Successfully uninstalled colorama-0.4.3
2021-02-05 14:49:29.519 |   Attempting uninstall: attrs
2021-02-05 14:49:29.521 |     Found existing installation: attrs 19.3.0
2021-02-05 14:49:29.544 |     Uninstalling attrs-19.3.0:
2021-02-05 14:49:29.590 |       Successfully uninstalled attrs-19.3.0
2021-02-05 14:49:30.918 |   Attempting uninstall: PyYAML
2021-02-05 14:49:30.920 |     Found existing installation: PyYAML 5.3.1
2021-02-05 14:49:30.922 | ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
2021-02-05 14:49:30.968 | WARNING: You are using pip version 21.0; however, version 21.0.1 is available.
2021-02-05 14:49:30.968 | You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
```

Relates to https://bugs.launchpad.net/devstack/+bug/1891694

**Comment by lingxiankong** [comment]
> Also we have this error:
> 
> ```
> 2021-02-05 12:48:00.182515 | k8s-master | + docker tag k8scloudprovider/openstack-cloud-controller-manager-amd64:latest k8scloudprovider/openstack-cloud-controller-manager:latest
> 2021-02-05 12:48:00.247896 | k8s-master | Error response from daemon: No such image: k8scloudprovider/openstack-cloud-controller-manager-amd64:latest
> ```

This is not error, in the task `Build openstack-cloud-controller-manager image`, we are using `make image-controller-manager` which builds image `k8scloudprovider/openstack-cloud-controller-manager:latest` instead of `k8scloudprovider/openstack-cloud-controller-manager-$ARCH:latest`. That's why the task `Tag image` has `ignore_errors: yes`. In the future, we will change `make image-controller-manager` to `make image-openstack-cloud-controller-manager`.

So you can ignore this ERROR.

**Comment by lingxiankong** [comment]
> I see that devstack is failing to install:
> 
> ```
> 2021-02-05 14:49:25.392 | Installing collected packages: linecache2, traceback2, pbr, argparse, wcwidth, unittest2, python-mimeparse, pyperclip, fixtures, extras, colorama, attrs, testtools, stevedore, PyYAML, PrettyTable, cmd2, voluptuous, python-subunit, future, cliff, stestr, os-testr
> 2021-02-05 14:49:27.149 |   Attempting uninstall: colorama
> 2021-02-05 14:49:27.150 |     Found existing installation: colorama 0.4.3
> 2021-02-05 14:49:27.353 |     Uninstalling colorama-0.4.3:
> 2021-02-05 14:49:29.338 |       Successfully uninstalled colorama-0.4.3
> 2021-02-05 14:49:29.519 |   Attempting uninstall: attrs
> 2021-02-05 14:49:29.521 |     Found existing installation: attrs 19.3.0
> 2021-02-05 14:49:29.544 |     Uninstalling attrs-19.3.0:
> 2021-02-05 14:49:29.590 |       Successfully uninstalled attrs-19.3.0
> 2021-02-05 14:49:30.918 |   Attempting uninstall: PyYAML
> 2021-02-05 14:49:30.920 |     Found existing installation: PyYAML 5.3.1
> 2021-02-05 14:49:30.922 | ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> 2021-02-05 14:49:30.968 | WARNING: You are using pip version 21.0; however, version 21.0.1 is available.
> 2021-02-05 14:49:30.968 | You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
> ```
> 
> Relates to https://bugs.launchpad.net/devstack/+bug/1891694

Which job is this relating to?

**Comment by lingxiankong** [comment]
> The issue still exists in [some cases](https://logs.openlabtesting.org/logs/84/1384/a2a6c42d771b29e4a364b78145904ec971e28072/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.19/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.19/e527603/):
> 
> ```
> 2021-02-05 12:44:27.158844 | TASK [Set hostname]
> 2021-02-05 12:44:28.245739 | k8s-node-1 | ERROR
> 2021-02-05 12:44:28.246317 | k8s-node-1 | {
> 2021-02-05 12:44:28.246414 | k8s-node-1 |   "msg": "Command failed rc=1, out=, err=Failed to create bus connection: No such file or directory\n"
> ```

In your PR, could you change the task `[Set hostname]` to:

```
    - name: Set hostname
      hostname:
        name: "{{ hostname_output.stdout }}"
        use: debian
```

**Comment by kayrus** [comment]
> Which job is this relating to?

every job, which depends on devstack task

**Comment by jichenjc** [comment]
@bzhaoopenstack @lingxiankong @kayrus I think the issue is not fixed yet? should we reopen this issue?

**Comment by kayrus** [comment]
there are many issues, caused by the bash version requirement. ubuntu, pip pyyaml, now pip constraints. looks like my latest [patch]https://github.com/theopenlab/openlab-zuul-jobs/pull/1105() didn't find the issue due to wrong path used.

**Comment by lingxiankong** [comment]
> @bzhaoopenstack @lingxiankong @kayrus I think the issue is not fixed yet? should we reopen this issue?

Hi, when we talking about job failure, can we paste some error logs so that people know what happened?

My previous PRs have fixed the hostname issue, @kayrus was trying to fix the devstack issue.

**Comment by kayrus** [comment]
@lingxiankong you can see error logs in devstack.txt output, e.g.:
https://logs.openlabtesting.org/logs/84/1384/a2a6c42d771b29e4a364b78145904ec971e28072/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/9a1565a/logs/devstacklog.txt
