### ISSUE TITLE
[issues] Citynetwork volumes can not be removed.

### ISSUE THREAD

**Issue by bzhaoopenstack** [theopenlab/openlab#679]
Citynetwork Volumes can not be deleted due to the all volume assciated with a snapshot, which status is error_deleting, and openlab has no right to operate. 
@tobberydberg  Sorry for disturbing you again. ;-) Could you please help to process? Thank you very much.
Currently, there are 4 volumes can not be removed. Details is:
# openstack --os-cloud citynetwork volume list
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------+
| ID                                   | Name                                     | Status    | Size | Attached to                                       |
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------+
| 02a12a66-219c-41a7-ba59-233e5749718f | pvc-bb34f49e-5b61-495c-ba54-2d11003c4de2 | available |    1 |                                                   |
| 9d07e670-d652-4e73-9f91-7eab29791713 | pvc-24e5058e-a6b4-4636-b243-ffcfffb89c6d | available |    1 |                                                   |
| 8fc5d000-c93a-4fd5-95b1-a66fc5ea9626 | pvc-fc060fc7-a0bc-47c7-9b6f-22bfd4f4044e | available |    1 |                                                   |
| f13d6caa-1197-46fe-a56d-adc106a7a660 | pvc-9dc9ea20-8d4b-43d4-a9f0-70d2ed35d999 | available |    1 |                                                   |
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------+

# openstack --os-cloud citynetwork snapshot list
This command has been deprecated. Please use "volume snapshot list" instead.
+--------------------------------------+-----------------------------------------------+----------------------------------------+----------------+------+
| ID                                   | Name                                          | Description                            | Status         | Size |
+--------------------------------------+-----------------------------------------------+----------------------------------------+----------------+------+
| b449c1bc-48bd-4b3f-b26a-fbaa22930b5f | snapshot-1cb7f0d9-6fd8-4678-aa4f-5ae0a6e95f93 | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| 22c259a5-e943-4901-add5-9c97637261a5 | snapshot-5e5c8aa0-6c80-4bd3-ae6b-b438cbdd1d40 | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| 113fc712-a708-4178-b9ad-824a934fe4d3 | snapshot-ea2d13cb-8306-4323-970b-38c131038ca9 | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
| eb1676be-37f0-40de-a5d4-9a30da9abd09 | snapshot-1597f714-d05b-4fc0-9b0f-d41eaa74fc4b | Created by OpenStack Cinder CSI driver | error_deleting |    1 |
+--------------------------------------+-----------------------------------------------+----------------------------------------+----------------+------+

**Comment by tobberydberg** [comment]
Hi,

I have now deleted the volume snapshots, so please try again and delete the volumes.

BR,
Tobias

**Comment by bzhaoopenstack** [comment]
@tobberydberg Big thanks, the said volumes had been removed successfully. ;-)
