### ISSUE TITLE
Ansible format issue

### ISSUE THREAD

**Issue by wangxiyuan** [theopenlab/openlab#689]
ansbile-lint raised a lot of new format issue. See: 
https://logs.openlabtesting.org/logs/16/1116/ff5ac1dd1af47167280586fd373b9ae6e6a2c54a/check/openlab-zuul-jobs-check/e4d10af/job-output.txt.gz

**Comment by bzhaoopenstack** [comment]
Fixed in https://github.com/theopenlab/openlab-zuul-jobs/pull/1120
