### ISSUE TITLE
OpenStack SDKs

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#7]
One SDK per language focus:

Go - [gophercloud](https://github.com/gophercloud/gophercloud)
Python - [python-openstacksdk](http://git.openstack.org/cgit/openstack/python-openstacksdk)
Ruby - [fog-openstack](https://github.com/fog/fog-openstack)
Java - [jclouds](https://github.com/jclouds/jclouds)
JavaScript - [pkgcloud](https://github.com/pkgcloud/pkgcloud)

**Comment by kiwik** [comment]
Splited task have been traced in https://github.com/theopenlab/openlab/issues
