### ISSUE TITLE
[cpo] no tests are triggered

### ISSUE THREAD

**Issue by chrigl** [theopenlab/openlab#706]
### Describe the bug

The last triggered test run for any cloud-provider-openstack (repo: https://github.com/kubernetes/cloud-provider-openstack)  is from 21.03. TheOpenLab CI integration is still configured on the repo.

### Steps to reproduce the issue
Describe how to reproduce the issue:

Modify some go file in https://github.com/kubernetes/cloud-provider-openstack and create a PR on the repo. This should trigger a test run, and openlab test should pop up in the "checks" section of the PR. Also the test is not started on http://status.openlabtesting.org/status.

Is there maybe anything in visible in the logs of zuul?

Thanks!

**Comment by wangxiyuan** [comment]
OK, there is must some issue with zuul. We'll check it at once.

**Comment by bzhaoopenstack** [comment]
https://github.com/kubernetes/cloud-provider-openstack/pull/1456#issuecomment-807974618

The test PR can trigger the openlab Jobs. @chrigl please try if there is any other issue we missed. Thank you

**Comment by chrigl** [comment]
Thanks! Works as expected.
