### ISSUE TITLE
Please Re-enable Gophercloud

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#707]
### Describe the bug

Gophercloud was disabled in OpenLab. Please see https://github.com/theopenlab/openlab-zuul-jobs/pull/1137 for more information.

### Additional context

Additionally, similar to #706, prior to Gophercloud being disabled we also were having problems with tests being triggered via Pull Requests. I can troubleshoot this more once Gophercloud has been re-enabled.

**Comment by wangxiyuan** [comment]
https://github.com/gophercloud/gophercloud/pull/2131 it works now. 

And for period job, I'll restart zuul and re-enable it later.
