### ISSUE TITLE
Please update governance members on About page.

### ISSUE THREAD

**Issue by yihleong** [theopenlab/openlab#715]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [x ] Other

### Brief project description
The about page is outdate. https://openlabtesting.org/about-us/ 
Please remove Yih Leong Sun (Intel) from About page.

### Will you publish blog or paper from your testing?

- [ ] Yes
- [ ] No - if no, how will you present your results?

**Comment by wangxiyuan** [comment]
Done
