### ISSUE TITLE
Job not running for terraform-provider-openstack

### ISSUE THREAD

**Issue by nikParasyr** [theopenlab/openlab#717]
Hello

I recently added a new job for terraform-provider-openstack to run with admin credentials. The PR on openlab-zuul-jobs is [here](https://github.com/theopenlab/openlab-zuul-jobs/pull/1136). After that I created an PR on terraform-provider-openstack to include that job [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1213). In that PR the job is running as expected. On a follow-up PR [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1223) the job **does not run.**
- I have checked if any new changes were made that could affect it but couldn't find anything. Also checked around http://status.openlabtesting.org/jobs for any clue or logs to indicate why it doesn't run. 
- As the job doesnt run at-all i can't find any relevant logs to see what is happening
- I have doublechecked the new PR and it has the latest commits from upstream that include the job definition etc

Any ideas why the job doesn't run? Thanks

**Comment by nikParasyr** [comment]
@wangxiyuan @bzhaoopenstack Any ideas?

**Comment by wangxiyuan** [comment]
The job is added in TPO already. https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/.zuul.yaml

But it's not in zuul page:
http://status.openlabtesting.org/project/github.com/terraform-provider-openstack/terraform-provider-openstack

So I guess this need a zuul restart. @bzhaoopenstack Please check it. Thanks.

**Comment by bzhaoopenstack** [comment]
The same I found, the new configuration had been loaded into zuul. We can see the website of the job page. But it's true, there is only 2 jobs triggered.

Already restart, let's wait.

**Comment by wangxiyuan** [comment]
@bzhaoopenstack Thanks. It appear now. @nikParasyr Please recheck your PR.

**Comment by nikParasyr** [comment]
hi. I triggered a re-check on two PRs i have:
- https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1223
- https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1225

On the site i dont see any buildset/build running for these:
- http://status.openlabtesting.org/buildsets?project=terraform-provider-openstack%2Fterraform-provider-openstack
- http://status.openlabtesting.org/builds?job_name=terraform-provider-openstack-acceptance-test-admin

**Comment by wangxiyuan** [comment]
@nikParasyr They are running now. Not finished yet
http://status.openlabtesting.org/status/change/1223,25b5763dd0f9e5f26f88cad2de0d6ad765f486cb
http://status.openlabtesting.org/status/change/1225,ea26d70a2f7efdea1077265597d360d8c788caaf

**Comment by nikParasyr** [comment]
oh great! sorry im not fully used to the openlab status website.
Thanks for all your help :)

**Comment by wangxiyuan** [comment]
That's fine. Let us know if there still other problem

**Comment by nikParasyr** [comment]
Both jobs ran fine. Thanks for your help! Closing
