### ISSUE TITLE
containerd/containerd has 3 jobs, but only one is executed on PRs

### ISSUE THREAD

**Issue by dims** [theopenlab/openlab#728]
Here are the 3 jobs:
https://github.com/containerd/containerd/blob/master/.zuul.yaml#L6-L8

the corresponding yaml files are here:
https://github.com/containerd/containerd/tree/master/.zuul/playbooks/containerd-build

Example PR where only the old job was run:
- https://github.com/containerd/containerd/pull/5422
- https://github.com/containerd/containerd/pull/5422#issuecomment-826140722

Can you please help?

**Comment by wangxiyuan** [comment]
@bzhaoopenstack It needs a zuul restart I guess.

**Comment by dims** [comment]
thanks @wangxiyuan @bzhaoopenstack !!

**Comment by dims** [comment]
@bzhaoopenstack looks like this has not been restarted yet? can't see the new jobs on this page:
http://status.openlabtesting.org/project/github.com/containerd/containerd

We have a containerd 1.5 release coming up really soon and this is the final blocker to get ARM64 release artifacts officially for containerd:
https://github.com/containerd/containerd/pull/5329

**Comment by wangxiyuan** [comment]
pytorch hit some problem, I'll fix it at once.

**Comment by wangxiyuan** [comment]
fixed now.

**Comment by dims** [comment]
thanks a ton @wangxiyuan @bzhaoopenstack !!
