### ISSUE TITLE
Q: How to deal with orphaned resources

### ISSUE THREAD

**Issue by chrigl** [theopenlab/openlab#746]
Let's clean things up :)

### Is your feature enhancement related to a problem? Please describe.

At the moment, especially csi tests frequently leaves orphaned volumes for various reasons. For example, the test suite as it crashes, or just times out for whatever reason, and the VMs are killed, or just a bug in the "controlling" software. However, it seems to be impossible from within the test suite or playbook to proper clean up.

At the moment this applies to cinder-csi tests at citynetworks. But would be true for any backing openstack.

### Describe the solution you'd like

I would write a cleanup job, that walks each volume that starts with `pvc-`, owning the property `cinder.csi.openstack.org/cluster` where the value starts with `kubernetes`, and being older than 4h(arbitrary number).

I would place this code  in the [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) repo.

I would run this job e.g. `periodic-10/22`

### Describe alternatives you've considered

I could also write the same in an ansible playbook/role and place it in the [theopenlab/openlab-zuul-jobs](https://github.com/theopenlab/openlab-zuul-jobs) repo. Because of restricting the cleanup to well known naming scheme (starts with `pvc`) and the well known property, I thought kubernetes/cloud-provider-openstack might be the better place.

What do you think?

Thanks, Chris

**Comment by wangxiyuan** [comment]
There are two kinds of orphan resource.

1. the volumes which created by the job but forgeted to clean up.
    For this kind of resource, we have the cleanup task already. Maybe the code is not strong enough, you can update it as you like.
https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-test/post.yaml

2.  The state of volume is in `error-deleting`.
    For this kind of resource, we can do nothing but ask citynetwork administrator for help.

**Comment by chrigl** [comment]
Thanks @wangxiyuan 

Understand. I was talking specifically about the first case.  I was thinking about the case when this post.yaml doesn't properly run for whatever reason. This leads to orphaned volumes. Cleanups of other (or later running) jobs won't clean those up.

The idea was to have a similar job like post.yaml, but running periodically for all `pvc-`-volumes.

**Comment by wangxiyuan** [comment]
Make sense. Feel free to commit the PR. Thanks.
