### ISSUE TITLE
"VolumeLimitExceeded: Maximum number of volumes allowed (100) exceeded for quota 'volumes in openstack Cinder CSI test

### ISSUE THREAD

**Issue by jichenjc** [theopenlab/openlab#749]
Thank you for reporting bug!

### Describe the bug

```
looks like gate is failing again on CSI? I am seeing following error at https://logs.openlabtesting.org/logs/96/1496/db8f01aea95814521c64e2451e61db7c15067930/cl[…]r-openstack-e2e-test-csi-cinder/17ff91b/job-output.txt.gz and maybe it lead to TIMEOUT in e2e test, not sure it's something related to env on openlab again?

cinder-controllerplugin-0_ade13c40-118f-4fe0-bdf0-7d32120318fa } ProvisioningFailed: failed to provision volume with StorageClass "provisioning-8675fwx76": rpc error: code = Internal desc = CreateVolume failed with error Expected HTTP response code [202] when accessing [POST https://lon1.citycloud.com:8776/v3/06ce5499f716488d985845cddcabdc16/volumes], but got 413 instead
2021-05-17 09:20:45.415836 | ubuntu-focal-citynetwork | {"overLimit": {"message": "VolumeLimitExceeded: Maximum number of volumes allowed (100) exceeded for quota 'volumes'.", "code": 413, "retryAfter": "0"}}
```

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by lingxiankong** [comment]
Does this https://github.com/theopenlab/openlab-zuul-jobs/pull/1149 help?

**Comment by jichenjc** [comment]
I am still seeing errors after retest, may need check whether it's same error soon

**Comment by lingxiankong** [comment]
https://github.com/theopenlab/openlab-zuul-jobs/pull/1149 needs to restart zuul

**Comment by jichenjc** [comment]
@wangxiyuan @lingxiankong can you help to restart the zuul?

**Comment by lingxiankong** [comment]
> @wangxiyuan @lingxiankong can you help to restart the zuul?

Restarted, we need to wait for the periodic job run.

**Comment by jichenjc** [comment]
@lingxiankong @wangxiyuan the CI is still failing with same error
can anyone help on this ?

**Comment by lingxiankong** [comment]
@jichenjc @chrigl The periodic job cloud-provider-openstack-cleanup-volumes is failing, log https://logs.openlabtesting.org/logs/periodic-22/github.com/theopenlab/openlab-zuul-jobs/master/cloud-provider-openstack-cleanup-volumes/bfa3fbe/job-output.txt.gz

**Comment by jichenjc** [comment]
```
2021-05-30 22:01:32.136003 | TASK [export-cloud-openrc : Set fact for opentelekomcloud openrc]
2021-05-30 22:01:32.236683 | ubuntu-focal-citynetwork | Output suppressed because no_log was given
2021-05-30 22:01:32.277160 | 
2021-05-30 22:01:32.277303 | PLAY RECAP
2021-05-30 22:01:32.277431 | ubuntu-focal-citynetwork | ok: 0 changed: 0 unreachable: 0 failed: 1 skipped: 0 rescued: 0 ignored: 0
```

don't understand this ..  @chrigl any comments?

**Comment by lingxiankong** [comment]
@jichenjc https://github.com/theopenlab/openlab-zuul-jobs/pull/1182, I will restart zuul after merge.

**Comment by lingxiankong** [comment]
The job has been run but there are lots of volumes not in removable status, https://logs.openlabtesting.org/logs/periodic-22/github.com/theopenlab/openlab-zuul-jobs/master/cloud-provider-openstack-cleanup-volumes/f93e4f4/job-output.txt.gz

**Comment by jichenjc** [comment]
@lingxiankong so the only way in short term is to ask manual removal of those volumes? 
seems no other immediate actions can help us in pass CI..

**Comment by bzhaoopenstack** [comment]
@tobberydberg  Hi sir, citynetwork volumes hit the same issue again, which is about the snapshot in error deleting status.

The affected volumes and snapshots are like below

**Comment by lingxiankong** [comment]
> @lingxiankong so the only way in short term is to ask manual removal of those volumes?
> seems no other immediate actions can help us in pass CI..

At the same time, we may really need to refactor the CI job to not reply on citynetwork for cinder-csi.

**Comment by tobberydberg** [comment]
All the snapshots that failed to get deleted are not actually deleted.

**Comment by lingxiankong** [comment]
> All the snapshots that failed to get deleted are not actually deleted.

Hi @tobberydberg, so how could we remove those snapshots in `error_deleting` status?

**Comment by tobberydberg** [comment]
Missed to answer you here @lingxiankong ... Unfortunate it is admin task only, reset state from admin and then delete them. So for now, lets keep pinging me when you have issues :-)
