### ISSUE TITLE
Open Service Broker

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#75]
- test against Open Service Broker of Huawei cloud
- test against OpenStack Murano (**no use case now, ignore this scenairo**)

https://www.openservicebrokerapi.org
https://github.com/openservicebrokerapi/osb-checker
https://github.com/huaweicloud/huaweicloud-service-broker

（8.20~8.31）

**Comment by kiwik** [comment]
Wait until PR https://github.com/openservicebrokerapi/osb-checker/issues/46 merged, we will retest Open Service Broker of Huawei Cloud with new released osb-checker.

**Comment by kiwik** [comment]
@liu-sheng have updated OpenLab osb-checker job and huaweicloud/huaweicloud-service-broker code, now all of test cases passed. http://status.openlabtesting.org/build/bb164fc7865b4ae39c1fa83522991942
