### ISSUE TITLE
containerd/containerd jobs all resulting in `NODE_FAILURE` recently

### ISSUE THREAD

**Issue by estesp** [theopenlab/openlab#789]
Thank you for reporting bug!

### Describe the bug
For the past few weeks it seems our OpenLab runs always result in `NODE_FAILURE` and since the link for node failure status doesn't lead to an actual log it is hard for us to determine what is wrong. We have not changed our zuul/OpenLab CI configuration at all recently.

### Related Job information
If the bug is related a CI job, put the job information below:
* job name:
* job build log link:
* error log piece:

(Since there is no job information generated for `NODE_FAILURE` you can see the overall build state for the past week showing `NODE_FAILURE` on every run here: http://status.openlabtesting.org/builds?job_name=containerd-build-arm64 )

### Steps to reproduce the issue
Describe how to reproduce the issue:
Any newly opened or updated PR generates an entry from OpenLab CI in the PR that all 3 of our jobs ended with `NODE_FAILURE`; there is no job ID or link provided when this happens. An example of this in the past 24 hours: https://github.com/containerd/containerd/pull/5701#issuecomment-876641500

**Comment by wangxiyuan** [comment]
Linaro resource pool in openlab is disconnected. I'll ask Linaro for help.

**Comment by wangxiyuan** [comment]
Fixing now. It'll be back soon

**Comment by bzhaoopenstack** [comment]
They don't use linaro resources. Containerd uses the huawei cloud resources. Recently the said resource pool is sold out.

**Comment by bzhaoopenstack** [comment]
Right now, the job is running.

**Comment by estesp** [comment]
Looks like we have 12 successful runs now in the last several hours; will close. Thank you!
