### ISSUE TITLE
[Citynetwork] Citynetwork region resources will be closed before 8.20

### ISSUE THREAD

**Issue by bzhaoopenstack** [theopenlab/openlab#801]
Due to the force majeure, we are so said that the region resource we used in citynetwork will be closed before 8.20 . Very thanks to citynetwork's kind support in these years.

@tobberydberg Hi sir, Could you please verify this? I can still login the dashboard, and see the resources, but can not login. So can openlab still use the free resource on other region?

BR

Thank you

**Comment by bzhaoopenstack** [comment]
@tobberydberg Hi sir, are you around recently? We are all waiting for your kind suggest. Thanks

**Comment by tobberydberg** [comment]
Sorry for the absence here, vacation and totally missed this mention. Yes, I can verify that Lon1 as a region will be closed as you say. With that said, that does not mean that we will stop providing you with resources for your project. 

I will get back to you on which region we prefer you to use moving forward.

**Comment by tobberydberg** [comment]
Hi again! @bzhaoopenstack Feel free to start using Fra1 region instead of Lon1 :-)

**Comment by bzhaoopenstack** [comment]
@tobberydberg Thank you very much, sir. We have more resources from citynetwork. Cool!
