### ISSUE TITLE
Duplicate job define cause all cloud-provider-openstack jobs RETRY_LIMIT

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#88]
See PR https://github.com/kubernetes/cloud-provider-openstack/pull/331, all cloud-provider-openstack jobs RETRY_LIMIT. There is a duplicate job name define in https://github.com/theopenlab/openlab-zuul-jobs/pull/335/files#diff-dbd9cd0ce7e9a5628770143f1488ff59R351, that cause these issues.

**Comment by adisky** [comment]
@kiwik Thanks!!!!
