### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by wangchenghub** [theopenlab/openlab#957]
Thank you for your donation!

### Which kind of resource you will donate?
- [ ] Virtual machine    
- [ ] Physical machine

### If Virtual machine will be donated, fill out the quota limits of tenant:
  * maxTotalInstances:
  * maxTotalCores:
  * maxTotalRAMSize:
  * maxTotalFloatingIps:
  * maxTotalVolumes:
  * maxTotalVolumeGigabytes:

### If physical machine will be donated, fill out the flavor and count:
  * flavor: XX Core, XX RAM, XX GB disk
  * special hardware: GPU, FPGA, SSD

### Can logo be placed on openlabtesting.org?
- [ ] Yes
- [ ] No

### An issue feedback way
Sometimes we can find out online issue in public cloud that donate to OpenLab, where and how we should to report it:
* Development team email of public cloud:
* Issue report link:
* Or any other ways to report the issue:

After commit this donation information, OpenLab governance member @theopenlab/governance will contact you as soon as possible to get the access information, like: tenant name, password and so on. You can talk with @theopenlab/governance member using email or other way, and only @theopenlab/governance and @theopenlab/ops team will know this access info.

**Comment by bzhaoopenstack** [comment]
@wangchenghub Hi, sorry for late reply. We are very interested that you openup donate issue in openlab channel. Could you please tell us how much size and resource type you want donate?

Thanks very much, appreciated. ;-)
