### ISSUE TITLE
OpenLab CI jobs persistently getting `RETRY_LIMIT` for 1 week

### ISSUE THREAD

**Issue by estesp** [theopenlab/openlab#967]
Thank you for reporting bug!

### Describe the bug
Our GH project [containerd/containerd](https://github.com/containerd/containerd) CI that runs on OpenLab has been failing for 7 days with `RETRY_LIMIT` for all 3 job definitions. If I go back 8 days it was working fine prior to that.

### Related Job information
Example output from a pull request [here](https://github.com/containerd/containerd/pull/6605#issuecomment-1057268499); with `RETRY_LIMIT` we don't get a link to any logs

```
containerd-build-arm64 : RETRY_LIMIT in 3m 53s (non-voting)
containerd-test-arm64 : RETRY_LIMIT in 6m 24s (non-voting)
containerd-integration-test-arm64 : RETRY_LIMIT in 28m 52s (non-voting)
```

### Steps to reproduce the issue

Run CI on any PR in the containerd repo from the last week.

### Additional context
N/A

**Comment by wangxiyuan** [comment]
Fixing now.

**Comment by wangxiyuan** [comment]
For security reason, we updated the openlab net topology recently, but forgot to update the related DNS record. So the log server can't be visit by zuul. The result is that when the job finished, the log can't be uploaded.

We have fixed the issue now. Please wait more to let the DNS record refreshed. Then I guess all will go well. 

Sorry for the problem.
